// Code generated by go-swagger; DO NOT EDIT.

package achievements

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAchievementsIDParams creates a new DeleteAchievementsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAchievementsIDParams() *DeleteAchievementsIDParams {
	return &DeleteAchievementsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAchievementsIDParamsWithTimeout creates a new DeleteAchievementsIDParams object
// with the ability to set a timeout on a request.
func NewDeleteAchievementsIDParamsWithTimeout(timeout time.Duration) *DeleteAchievementsIDParams {
	return &DeleteAchievementsIDParams{
		timeout: timeout,
	}
}

// NewDeleteAchievementsIDParamsWithContext creates a new DeleteAchievementsIDParams object
// with the ability to set a context for a request.
func NewDeleteAchievementsIDParamsWithContext(ctx context.Context) *DeleteAchievementsIDParams {
	return &DeleteAchievementsIDParams{
		Context: ctx,
	}
}

// NewDeleteAchievementsIDParamsWithHTTPClient creates a new DeleteAchievementsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAchievementsIDParamsWithHTTPClient(client *http.Client) *DeleteAchievementsIDParams {
	return &DeleteAchievementsIDParams{
		HTTPClient: client,
	}
}

/*
DeleteAchievementsIDParams contains all the parameters to send to the API endpoint

	for the delete achievements ID operation.

	Typically these are written to a http.Request.
*/
type DeleteAchievementsIDParams struct {

	/* Authorization.

	   Bearer JWT token
	*/
	Authorization *string

	/* ID.

	   Achievement UUID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete achievements ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAchievementsIDParams) WithDefaults() *DeleteAchievementsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete achievements ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAchievementsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete achievements ID params
func (o *DeleteAchievementsIDParams) WithTimeout(timeout time.Duration) *DeleteAchievementsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete achievements ID params
func (o *DeleteAchievementsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete achievements ID params
func (o *DeleteAchievementsIDParams) WithContext(ctx context.Context) *DeleteAchievementsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete achievements ID params
func (o *DeleteAchievementsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete achievements ID params
func (o *DeleteAchievementsIDParams) WithHTTPClient(client *http.Client) *DeleteAchievementsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete achievements ID params
func (o *DeleteAchievementsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the delete achievements ID params
func (o *DeleteAchievementsIDParams) WithAuthorization(authorization *string) *DeleteAchievementsIDParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the delete achievements ID params
func (o *DeleteAchievementsIDParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithID adds the id to the delete achievements ID params
func (o *DeleteAchievementsIDParams) WithID(id string) *DeleteAchievementsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete achievements ID params
func (o *DeleteAchievementsIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAchievementsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
