// Code generated by go-swagger; DO NOT EDIT.

package achievements

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAchievementsUsersParams creates a new GetAchievementsUsersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAchievementsUsersParams() *GetAchievementsUsersParams {
	return &GetAchievementsUsersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAchievementsUsersParamsWithTimeout creates a new GetAchievementsUsersParams object
// with the ability to set a timeout on a request.
func NewGetAchievementsUsersParamsWithTimeout(timeout time.Duration) *GetAchievementsUsersParams {
	return &GetAchievementsUsersParams{
		timeout: timeout,
	}
}

// NewGetAchievementsUsersParamsWithContext creates a new GetAchievementsUsersParams object
// with the ability to set a context for a request.
func NewGetAchievementsUsersParamsWithContext(ctx context.Context) *GetAchievementsUsersParams {
	return &GetAchievementsUsersParams{
		Context: ctx,
	}
}

// NewGetAchievementsUsersParamsWithHTTPClient creates a new GetAchievementsUsersParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAchievementsUsersParamsWithHTTPClient(client *http.Client) *GetAchievementsUsersParams {
	return &GetAchievementsUsersParams{
		HTTPClient: client,
	}
}

/*
GetAchievementsUsersParams contains all the parameters to send to the API endpoint

	for the get achievements users operation.

	Typically these are written to a http.Request.
*/
type GetAchievementsUsersParams struct {

	/* Authorization.

	   Bearer JWT token
	*/
	Authorization *string

	/* Limit.

	   Pagination limit

	   Default: 10
	*/
	Limit *int64

	/* Offset.

	   Pagination offset
	*/
	Offset *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get achievements users params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAchievementsUsersParams) WithDefaults() *GetAchievementsUsersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get achievements users params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAchievementsUsersParams) SetDefaults() {
	var (
		limitDefault = int64(10)

		offsetDefault = int64(0)
	)

	val := GetAchievementsUsersParams{
		Limit:  &limitDefault,
		Offset: &offsetDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get achievements users params
func (o *GetAchievementsUsersParams) WithTimeout(timeout time.Duration) *GetAchievementsUsersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get achievements users params
func (o *GetAchievementsUsersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get achievements users params
func (o *GetAchievementsUsersParams) WithContext(ctx context.Context) *GetAchievementsUsersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get achievements users params
func (o *GetAchievementsUsersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get achievements users params
func (o *GetAchievementsUsersParams) WithHTTPClient(client *http.Client) *GetAchievementsUsersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get achievements users params
func (o *GetAchievementsUsersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get achievements users params
func (o *GetAchievementsUsersParams) WithAuthorization(authorization *string) *GetAchievementsUsersParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get achievements users params
func (o *GetAchievementsUsersParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithLimit adds the limit to the get achievements users params
func (o *GetAchievementsUsersParams) WithLimit(limit *int64) *GetAchievementsUsersParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get achievements users params
func (o *GetAchievementsUsersParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the get achievements users params
func (o *GetAchievementsUsersParams) WithOffset(offset *int64) *GetAchievementsUsersParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get achievements users params
func (o *GetAchievementsUsersParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *GetAchievementsUsersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
