// Code generated by go-swagger; DO NOT EDIT.

package achievements

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kozlov-ma/sesc-backend/apiclient/models"
)

// NewPostAchievementsIDSubmitWithNewPointsParams creates a new PostAchievementsIDSubmitWithNewPointsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAchievementsIDSubmitWithNewPointsParams() *PostAchievementsIDSubmitWithNewPointsParams {
	return &PostAchievementsIDSubmitWithNewPointsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAchievementsIDSubmitWithNewPointsParamsWithTimeout creates a new PostAchievementsIDSubmitWithNewPointsParams object
// with the ability to set a timeout on a request.
func NewPostAchievementsIDSubmitWithNewPointsParamsWithTimeout(timeout time.Duration) *PostAchievementsIDSubmitWithNewPointsParams {
	return &PostAchievementsIDSubmitWithNewPointsParams{
		timeout: timeout,
	}
}

// NewPostAchievementsIDSubmitWithNewPointsParamsWithContext creates a new PostAchievementsIDSubmitWithNewPointsParams object
// with the ability to set a context for a request.
func NewPostAchievementsIDSubmitWithNewPointsParamsWithContext(ctx context.Context) *PostAchievementsIDSubmitWithNewPointsParams {
	return &PostAchievementsIDSubmitWithNewPointsParams{
		Context: ctx,
	}
}

// NewPostAchievementsIDSubmitWithNewPointsParamsWithHTTPClient creates a new PostAchievementsIDSubmitWithNewPointsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAchievementsIDSubmitWithNewPointsParamsWithHTTPClient(client *http.Client) *PostAchievementsIDSubmitWithNewPointsParams {
	return &PostAchievementsIDSubmitWithNewPointsParams{
		HTTPClient: client,
	}
}

/*
PostAchievementsIDSubmitWithNewPointsParams contains all the parameters to send to the API endpoint

	for the post achievements ID submit with new points operation.

	Typically these are written to a http.Request.
*/
type PostAchievementsIDSubmitWithNewPointsParams struct {

	/* Authorization.

	   Bearer JWT token
	*/
	Authorization *string

	/* ID.

	   Achievement UUID
	*/
	ID string

	/* Request.

	   Points update data
	*/
	Request *models.ParamUpdateAchievementPointsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post achievements ID submit with new points params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAchievementsIDSubmitWithNewPointsParams) WithDefaults() *PostAchievementsIDSubmitWithNewPointsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post achievements ID submit with new points params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAchievementsIDSubmitWithNewPointsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post achievements ID submit with new points params
func (o *PostAchievementsIDSubmitWithNewPointsParams) WithTimeout(timeout time.Duration) *PostAchievementsIDSubmitWithNewPointsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post achievements ID submit with new points params
func (o *PostAchievementsIDSubmitWithNewPointsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post achievements ID submit with new points params
func (o *PostAchievementsIDSubmitWithNewPointsParams) WithContext(ctx context.Context) *PostAchievementsIDSubmitWithNewPointsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post achievements ID submit with new points params
func (o *PostAchievementsIDSubmitWithNewPointsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post achievements ID submit with new points params
func (o *PostAchievementsIDSubmitWithNewPointsParams) WithHTTPClient(client *http.Client) *PostAchievementsIDSubmitWithNewPointsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post achievements ID submit with new points params
func (o *PostAchievementsIDSubmitWithNewPointsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the post achievements ID submit with new points params
func (o *PostAchievementsIDSubmitWithNewPointsParams) WithAuthorization(authorization *string) *PostAchievementsIDSubmitWithNewPointsParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the post achievements ID submit with new points params
func (o *PostAchievementsIDSubmitWithNewPointsParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithID adds the id to the post achievements ID submit with new points params
func (o *PostAchievementsIDSubmitWithNewPointsParams) WithID(id string) *PostAchievementsIDSubmitWithNewPointsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post achievements ID submit with new points params
func (o *PostAchievementsIDSubmitWithNewPointsParams) SetID(id string) {
	o.ID = id
}

// WithRequest adds the request to the post achievements ID submit with new points params
func (o *PostAchievementsIDSubmitWithNewPointsParams) WithRequest(request *models.ParamUpdateAchievementPointsRequest) *PostAchievementsIDSubmitWithNewPointsParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post achievements ID submit with new points params
func (o *PostAchievementsIDSubmitWithNewPointsParams) SetRequest(request *models.ParamUpdateAchievementPointsRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostAchievementsIDSubmitWithNewPointsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
