// Code generated by go-swagger; DO NOT EDIT.

package achievements

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAchievementsIDSubmitParams creates a new PostAchievementsIDSubmitParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAchievementsIDSubmitParams() *PostAchievementsIDSubmitParams {
	return &PostAchievementsIDSubmitParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAchievementsIDSubmitParamsWithTimeout creates a new PostAchievementsIDSubmitParams object
// with the ability to set a timeout on a request.
func NewPostAchievementsIDSubmitParamsWithTimeout(timeout time.Duration) *PostAchievementsIDSubmitParams {
	return &PostAchievementsIDSubmitParams{
		timeout: timeout,
	}
}

// NewPostAchievementsIDSubmitParamsWithContext creates a new PostAchievementsIDSubmitParams object
// with the ability to set a context for a request.
func NewPostAchievementsIDSubmitParamsWithContext(ctx context.Context) *PostAchievementsIDSubmitParams {
	return &PostAchievementsIDSubmitParams{
		Context: ctx,
	}
}

// NewPostAchievementsIDSubmitParamsWithHTTPClient creates a new PostAchievementsIDSubmitParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAchievementsIDSubmitParamsWithHTTPClient(client *http.Client) *PostAchievementsIDSubmitParams {
	return &PostAchievementsIDSubmitParams{
		HTTPClient: client,
	}
}

/*
PostAchievementsIDSubmitParams contains all the parameters to send to the API endpoint

	for the post achievements ID submit operation.

	Typically these are written to a http.Request.
*/
type PostAchievementsIDSubmitParams struct {

	/* Authorization.

	   Bearer JWT token
	*/
	Authorization *string

	/* ID.

	   Achievement UUID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post achievements ID submit params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAchievementsIDSubmitParams) WithDefaults() *PostAchievementsIDSubmitParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post achievements ID submit params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAchievementsIDSubmitParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post achievements ID submit params
func (o *PostAchievementsIDSubmitParams) WithTimeout(timeout time.Duration) *PostAchievementsIDSubmitParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post achievements ID submit params
func (o *PostAchievementsIDSubmitParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post achievements ID submit params
func (o *PostAchievementsIDSubmitParams) WithContext(ctx context.Context) *PostAchievementsIDSubmitParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post achievements ID submit params
func (o *PostAchievementsIDSubmitParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post achievements ID submit params
func (o *PostAchievementsIDSubmitParams) WithHTTPClient(client *http.Client) *PostAchievementsIDSubmitParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post achievements ID submit params
func (o *PostAchievementsIDSubmitParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the post achievements ID submit params
func (o *PostAchievementsIDSubmitParams) WithAuthorization(authorization *string) *PostAchievementsIDSubmitParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the post achievements ID submit params
func (o *PostAchievementsIDSubmitParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithID adds the id to the post achievements ID submit params
func (o *PostAchievementsIDSubmitParams) WithID(id string) *PostAchievementsIDSubmitParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post achievements ID submit params
func (o *PostAchievementsIDSubmitParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostAchievementsIDSubmitParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
