services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: sesc
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sesc-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      ldap:
        condition: service_healthy
    environment:
      SESC_DATABASE_ADDRESS: postgres://pguser:pgpassword@postgres:5432/sesc?sslmode=disable
      SESC_MINIO_ENDPOINT: minio:9000
      SESC_MINIO_ACCESS_KEY: minioadmin
      SESC_MINIO_SECRET_KEY: minioadmin
      SESC_MINIO_USE_SSL: "false"
      SESC_MINIO_BUCKET_NAME: sesc-files

  ldap:
    image: osixia/openldap:1.5.0
    container_name: lyceum-ldap
    hostname: ldap1
    environment:
      LDAP_ORGANISATION: "Lyceum"
      LDAP_DOMAIN: "lyceum.usu.ru"
      LDAP_ADMIN_PASSWORD: "Admin123!Pass"
      LDAP_CONFIG_PASSWORD: "Admin123!Pass"
      LDAP_RFC2307BIS_SCHEMA: "true"
    ports:
      - "389:389"
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d
      - ./scripts/bootstrap.ldif:/ldif/bootstrap.ldif:ro
      - ./scripts/import.sh:/container/environment/01-custom/import.sh:ro
    restart: unless-stopped

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - ldap

volumes:
  postgres:
  minio-data:
  ldap-data:
  ldap-config:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
