services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  pgsetup:
    build:
      dockerfile: ./cmd/pgsetup/Dockerfile
      context: .
    container_name: pgsetup
    restart: no
    depends_on:
      - postgres
    environment:
      - POSTGRES_ADDRESS=postgres://postgres:password@postgres:5432/postgres

volumes:
  postgres:
