services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address :9001

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sesc-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SESC_DATABASE_ADDRESS: postgres://postgres:password@postgres:5432/postgres?sslmode=disable
      SESC_S3_ENDPOINT: minio:9000
      SESC_S3_ACCESS_KEY: minio
      SESC_S3_SECRET_KEY: minio123
      SESC_S3_BUCKET: documents
      SESC_S3_USE_SSL: "false"

volumes:
  postgres:
  minio_data:
