// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kozlov-ma/sesc-backend/apiclient/models"
)

// GetUsersMeReader is a Reader for the GetUsersMe structure.
type GetUsersMeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUsersMeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetUsersMeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetUsersMeUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetUsersMeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetUsersMeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /users/me] GetUsersMe", response, response.Code())
	}
}

// NewGetUsersMeOK creates a GetUsersMeOK with default headers values
func NewGetUsersMeOK() *GetUsersMeOK {
	return &GetUsersMeOK{}
}

/*
GetUsersMeOK describes a response with status code 200, with default header values.

OK
*/
type GetUsersMeOK struct {
	Payload *models.APIUserResponse
}

// IsSuccess returns true when this get users me o k response has a 2xx status code
func (o *GetUsersMeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get users me o k response has a 3xx status code
func (o *GetUsersMeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get users me o k response has a 4xx status code
func (o *GetUsersMeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get users me o k response has a 5xx status code
func (o *GetUsersMeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get users me o k response a status code equal to that given
func (o *GetUsersMeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get users me o k response
func (o *GetUsersMeOK) Code() int {
	return 200
}

func (o *GetUsersMeOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/me][%d] getUsersMeOK %s", 200, payload)
}

func (o *GetUsersMeOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/me][%d] getUsersMeOK %s", 200, payload)
}

func (o *GetUsersMeOK) GetPayload() *models.APIUserResponse {
	return o.Payload
}

func (o *GetUsersMeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIUserResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUsersMeUnauthorized creates a GetUsersMeUnauthorized with default headers values
func NewGetUsersMeUnauthorized() *GetUsersMeUnauthorized {
	return &GetUsersMeUnauthorized{}
}

/*
GetUsersMeUnauthorized describes a response with status code 401, with default header values.

Unauthorized or invalid token
*/
type GetUsersMeUnauthorized struct {
	Payload *models.APIUnauthorizedError
}

// IsSuccess returns true when this get users me unauthorized response has a 2xx status code
func (o *GetUsersMeUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get users me unauthorized response has a 3xx status code
func (o *GetUsersMeUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get users me unauthorized response has a 4xx status code
func (o *GetUsersMeUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get users me unauthorized response has a 5xx status code
func (o *GetUsersMeUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get users me unauthorized response a status code equal to that given
func (o *GetUsersMeUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get users me unauthorized response
func (o *GetUsersMeUnauthorized) Code() int {
	return 401
}

func (o *GetUsersMeUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/me][%d] getUsersMeUnauthorized %s", 401, payload)
}

func (o *GetUsersMeUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/me][%d] getUsersMeUnauthorized %s", 401, payload)
}

func (o *GetUsersMeUnauthorized) GetPayload() *models.APIUnauthorizedError {
	return o.Payload
}

func (o *GetUsersMeUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIUnauthorizedError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUsersMeNotFound creates a GetUsersMeNotFound with default headers values
func NewGetUsersMeNotFound() *GetUsersMeNotFound {
	return &GetUsersMeNotFound{}
}

/*
GetUsersMeNotFound describes a response with status code 404, with default header values.

User not found
*/
type GetUsersMeNotFound struct {
	Payload *models.APIUserNotFoundError
}

// IsSuccess returns true when this get users me not found response has a 2xx status code
func (o *GetUsersMeNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get users me not found response has a 3xx status code
func (o *GetUsersMeNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get users me not found response has a 4xx status code
func (o *GetUsersMeNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get users me not found response has a 5xx status code
func (o *GetUsersMeNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get users me not found response a status code equal to that given
func (o *GetUsersMeNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get users me not found response
func (o *GetUsersMeNotFound) Code() int {
	return 404
}

func (o *GetUsersMeNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/me][%d] getUsersMeNotFound %s", 404, payload)
}

func (o *GetUsersMeNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/me][%d] getUsersMeNotFound %s", 404, payload)
}

func (o *GetUsersMeNotFound) GetPayload() *models.APIUserNotFoundError {
	return o.Payload
}

func (o *GetUsersMeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIUserNotFoundError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUsersMeInternalServerError creates a GetUsersMeInternalServerError with default headers values
func NewGetUsersMeInternalServerError() *GetUsersMeInternalServerError {
	return &GetUsersMeInternalServerError{}
}

/*
GetUsersMeInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetUsersMeInternalServerError struct {
	Payload *models.APIServerError
}

// IsSuccess returns true when this get users me internal server error response has a 2xx status code
func (o *GetUsersMeInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get users me internal server error response has a 3xx status code
func (o *GetUsersMeInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get users me internal server error response has a 4xx status code
func (o *GetUsersMeInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get users me internal server error response has a 5xx status code
func (o *GetUsersMeInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get users me internal server error response a status code equal to that given
func (o *GetUsersMeInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get users me internal server error response
func (o *GetUsersMeInternalServerError) Code() int {
	return 500
}

func (o *GetUsersMeInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/me][%d] getUsersMeInternalServerError %s", 500, payload)
}

func (o *GetUsersMeInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /users/me][%d] getUsersMeInternalServerError %s", 500, payload)
}

func (o *GetUsersMeInternalServerError) GetPayload() *models.APIServerError {
	return o.Payload
}

func (o *GetUsersMeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
