// Code generated by go-swagger; DO NOT EDIT.

package documents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetDocumentsStatsParams creates a new GetDocumentsStatsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDocumentsStatsParams() *GetDocumentsStatsParams {
	return &GetDocumentsStatsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDocumentsStatsParamsWithTimeout creates a new GetDocumentsStatsParams object
// with the ability to set a timeout on a request.
func NewGetDocumentsStatsParamsWithTimeout(timeout time.Duration) *GetDocumentsStatsParams {
	return &GetDocumentsStatsParams{
		timeout: timeout,
	}
}

// NewGetDocumentsStatsParamsWithContext creates a new GetDocumentsStatsParams object
// with the ability to set a context for a request.
func NewGetDocumentsStatsParamsWithContext(ctx context.Context) *GetDocumentsStatsParams {
	return &GetDocumentsStatsParams{
		Context: ctx,
	}
}

// NewGetDocumentsStatsParamsWithHTTPClient creates a new GetDocumentsStatsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDocumentsStatsParamsWithHTTPClient(client *http.Client) *GetDocumentsStatsParams {
	return &GetDocumentsStatsParams{
		HTTPClient: client,
	}
}

/*
GetDocumentsStatsParams contains all the parameters to send to the API endpoint

	for the get documents stats operation.

	Typically these are written to a http.Request.
*/
type GetDocumentsStatsParams struct {

	/* Authorization.

	   Bearer JWT token
	*/
	Authorization *string

	/* IsCommon.

	   If true, return stats for common files only; if false, return stats for user files only
	*/
	IsCommon *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get documents stats params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDocumentsStatsParams) WithDefaults() *GetDocumentsStatsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get documents stats params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDocumentsStatsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get documents stats params
func (o *GetDocumentsStatsParams) WithTimeout(timeout time.Duration) *GetDocumentsStatsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get documents stats params
func (o *GetDocumentsStatsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get documents stats params
func (o *GetDocumentsStatsParams) WithContext(ctx context.Context) *GetDocumentsStatsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get documents stats params
func (o *GetDocumentsStatsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get documents stats params
func (o *GetDocumentsStatsParams) WithHTTPClient(client *http.Client) *GetDocumentsStatsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get documents stats params
func (o *GetDocumentsStatsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get documents stats params
func (o *GetDocumentsStatsParams) WithAuthorization(authorization *string) *GetDocumentsStatsParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get documents stats params
func (o *GetDocumentsStatsParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithIsCommon adds the isCommon to the get documents stats params
func (o *GetDocumentsStatsParams) WithIsCommon(isCommon *bool) *GetDocumentsStatsParams {
	o.SetIsCommon(isCommon)
	return o
}

// SetIsCommon adds the isCommon to the get documents stats params
func (o *GetDocumentsStatsParams) SetIsCommon(isCommon *bool) {
	o.IsCommon = isCommon
}

// WriteToRequest writes these params to a swagger request
func (o *GetDocumentsStatsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}
	}

	if o.IsCommon != nil {

		// query param isCommon
		var qrIsCommon bool

		if o.IsCommon != nil {
			qrIsCommon = *o.IsCommon
		}
		qIsCommon := swag.FormatBool(qrIsCommon)
		if qIsCommon != "" {

			if err := r.SetQueryParam("isCommon", qIsCommon); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
