// Code generated by go-swagger; DO NOT EDIT.

package documents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kozlov-ma/sesc-backend/apiclient/models"
)

// GetDocumentsStatsReader is a Reader for the GetDocumentsStats structure.
type GetDocumentsStatsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDocumentsStatsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDocumentsStatsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetDocumentsStatsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetDocumentsStatsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetDocumentsStatsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /documents/stats] GetDocumentsStats", response, response.Code())
	}
}

// NewGetDocumentsStatsOK creates a GetDocumentsStatsOK with default headers values
func NewGetDocumentsStatsOK() *GetDocumentsStatsOK {
	return &GetDocumentsStatsOK{}
}

/*
GetDocumentsStatsOK describes a response with status code 200, with default header values.

OK
*/
type GetDocumentsStatsOK struct {
	Payload *models.RespondDocumentStats
}

// IsSuccess returns true when this get documents stats o k response has a 2xx status code
func (o *GetDocumentsStatsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get documents stats o k response has a 3xx status code
func (o *GetDocumentsStatsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get documents stats o k response has a 4xx status code
func (o *GetDocumentsStatsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get documents stats o k response has a 5xx status code
func (o *GetDocumentsStatsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get documents stats o k response a status code equal to that given
func (o *GetDocumentsStatsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get documents stats o k response
func (o *GetDocumentsStatsOK) Code() int {
	return 200
}

func (o *GetDocumentsStatsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /documents/stats][%d] getDocumentsStatsOK %s", 200, payload)
}

func (o *GetDocumentsStatsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /documents/stats][%d] getDocumentsStatsOK %s", 200, payload)
}

func (o *GetDocumentsStatsOK) GetPayload() *models.RespondDocumentStats {
	return o.Payload
}

func (o *GetDocumentsStatsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RespondDocumentStats)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDocumentsStatsUnauthorized creates a GetDocumentsStatsUnauthorized with default headers values
func NewGetDocumentsStatsUnauthorized() *GetDocumentsStatsUnauthorized {
	return &GetDocumentsStatsUnauthorized{}
}

/*
GetDocumentsStatsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetDocumentsStatsUnauthorized struct {
	Payload *models.RespondError
}

// IsSuccess returns true when this get documents stats unauthorized response has a 2xx status code
func (o *GetDocumentsStatsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get documents stats unauthorized response has a 3xx status code
func (o *GetDocumentsStatsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get documents stats unauthorized response has a 4xx status code
func (o *GetDocumentsStatsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get documents stats unauthorized response has a 5xx status code
func (o *GetDocumentsStatsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get documents stats unauthorized response a status code equal to that given
func (o *GetDocumentsStatsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get documents stats unauthorized response
func (o *GetDocumentsStatsUnauthorized) Code() int {
	return 401
}

func (o *GetDocumentsStatsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /documents/stats][%d] getDocumentsStatsUnauthorized %s", 401, payload)
}

func (o *GetDocumentsStatsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /documents/stats][%d] getDocumentsStatsUnauthorized %s", 401, payload)
}

func (o *GetDocumentsStatsUnauthorized) GetPayload() *models.RespondError {
	return o.Payload
}

func (o *GetDocumentsStatsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RespondError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDocumentsStatsForbidden creates a GetDocumentsStatsForbidden with default headers values
func NewGetDocumentsStatsForbidden() *GetDocumentsStatsForbidden {
	return &GetDocumentsStatsForbidden{}
}

/*
GetDocumentsStatsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetDocumentsStatsForbidden struct {
	Payload *models.RespondError
}

// IsSuccess returns true when this get documents stats forbidden response has a 2xx status code
func (o *GetDocumentsStatsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get documents stats forbidden response has a 3xx status code
func (o *GetDocumentsStatsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get documents stats forbidden response has a 4xx status code
func (o *GetDocumentsStatsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get documents stats forbidden response has a 5xx status code
func (o *GetDocumentsStatsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get documents stats forbidden response a status code equal to that given
func (o *GetDocumentsStatsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get documents stats forbidden response
func (o *GetDocumentsStatsForbidden) Code() int {
	return 403
}

func (o *GetDocumentsStatsForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /documents/stats][%d] getDocumentsStatsForbidden %s", 403, payload)
}

func (o *GetDocumentsStatsForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /documents/stats][%d] getDocumentsStatsForbidden %s", 403, payload)
}

func (o *GetDocumentsStatsForbidden) GetPayload() *models.RespondError {
	return o.Payload
}

func (o *GetDocumentsStatsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RespondError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDocumentsStatsInternalServerError creates a GetDocumentsStatsInternalServerError with default headers values
func NewGetDocumentsStatsInternalServerError() *GetDocumentsStatsInternalServerError {
	return &GetDocumentsStatsInternalServerError{}
}

/*
GetDocumentsStatsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetDocumentsStatsInternalServerError struct {
	Payload *models.RespondError
}

// IsSuccess returns true when this get documents stats internal server error response has a 2xx status code
func (o *GetDocumentsStatsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get documents stats internal server error response has a 3xx status code
func (o *GetDocumentsStatsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get documents stats internal server error response has a 4xx status code
func (o *GetDocumentsStatsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get documents stats internal server error response has a 5xx status code
func (o *GetDocumentsStatsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get documents stats internal server error response a status code equal to that given
func (o *GetDocumentsStatsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get documents stats internal server error response
func (o *GetDocumentsStatsInternalServerError) Code() int {
	return 500
}

func (o *GetDocumentsStatsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /documents/stats][%d] getDocumentsStatsInternalServerError %s", 500, payload)
}

func (o *GetDocumentsStatsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /documents/stats][%d] getDocumentsStatsInternalServerError %s", 500, payload)
}

func (o *GetDocumentsStatsInternalServerError) GetPayload() *models.RespondError {
	return o.Payload
}

func (o *GetDocumentsStatsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RespondError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
