// This file is auto-generated by @hey-api/openapi-ts

export const api_CredentialsRequestSchema = {
  type: "object",
  required: ["password", "username"],
  properties: {
    password: {
      type: "string",
      example: "secret123",
    },
    username: {
      type: "string",
      example: "johndoe",
    },
  },
} as const;

export const api_RolesResponseSchema = {
  type: "object",
  properties: {
    roles: {
      type: "array",
      items: {
        $ref: "#/definitions/respond.Role",
      },
    },
  },
} as const;

export const api_TokenResponseSchema = {
  type: "object",
  required: ["token"],
  properties: {
    token: {
      type: "string",
      example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
    },
  },
} as const;

export const param_AddDocumentRequestSchema = {
  type: "object",
  required: ["fileId", "name"],
  properties: {
    fileId: {
      type: "string",
      example: "550e8400-e29b-41d4-a716-446655440000",
    },
    name: {
      type: "string",
      example: "Publication proof",
    },
  },
} as const;

export const param_CreateAchievementGroupRequestSchema = {
  type: "object",
  required: ["description", "name"],
  properties: {
    description: {
      type: "string",
      example: "Достижения в научной деятельности",
    },
    name: {
      type: "string",
      example: "Научная деятельность",
    },
  },
} as const;

export const param_CreateAchievementRequestSchema = {
  type: "object",
  required: ["templateId"],
  properties: {
    templateId: {
      type: "string",
      example: "550e8400-e29b-41d4-a716-446655440000",
    },
  },
} as const;

export const param_CreateAchievementTemplateRequestSchema = {
  type: "object",
  required: ["description", "groupId", "name", "pointsLimit", "reviewerRole"],
  properties: {
    description: {
      type: "string",
      example: "Публикация статьи в научном журнале",
    },
    groupId: {
      type: "string",
      example: "550e8400-e29b-41d4-a716-446655440000",
    },
    name: {
      type: "string",
      example: "Публикация в журнале",
    },
    pointsLimit: {
      type: "integer",
      example: 10,
    },
    reviewerRole: {
      type: "string",
      example: "dephead",
    },
  },
} as const;

export const param_PatchAchievementGroupRequestSchema = {
  type: "object",
  properties: {
    active: {
      type: "boolean",
      example: true,
    },
    description: {
      type: "string",
      example: "Достижения в научной деятельности",
    },
    name: {
      type: "string",
      example: "Научная деятельность",
    },
  },
} as const;

export const param_PatchAchievementTemplateRequestSchema = {
  type: "object",
  properties: {
    active: {
      type: "boolean",
      example: true,
    },
    description: {
      type: "string",
      example: "Публикация статьи в научном журнале",
    },
    name: {
      type: "string",
      example: "Публикация в журнале",
    },
    pointsLimit: {
      type: "integer",
      example: 10,
    },
    reviewerRole: {
      type: "string",
      example: "dephead",
    },
  },
} as const;

export const param_ReviewAchievementRequestSchema = {
  type: "object",
  required: ["action"],
  properties: {
    action: {
      type: "string",
      enum: ["approve", "disapprove", "request_changes"],
      example: "approve",
    },
    comment: {
      type: "string",
      example: "Good job, but could be better",
    },
  },
} as const;

export const param_UpdateAchievementPointsRequestSchema = {
  type: "object",
  required: ["points"],
  properties: {
    comment: {
      type: "string",
      example: "Updated based on feedback",
    },
    points: {
      type: "integer",
      minimum: 0,
      example: 8,
    },
  },
} as const;

export const respond_AchievementSchema = {
  type: "object",
  required: [
    "departmentId",
    "documents",
    "id",
    "maxPoints",
    "ownerId",
    "points",
    "reviews",
    "status",
    "templateId",
    "templateName",
  ],
  properties: {
    departmentId: {
      type: "string",
      example: "kaf_bio",
    },
    documents: {
      type: "array",
      items: {
        $ref: "#/definitions/respond.Document",
      },
    },
    id: {
      type: "string",
      example: "550e8400-e29b-41d4-a716-446655440000",
    },
    maxPoints: {
      type: "integer",
      example: 10,
    },
    ownerId: {
      type: "string",
      example: "ivanivanov",
    },
    points: {
      type: "integer",
      example: 7,
    },
    reviews: {
      type: "array",
      items: {
        $ref: "#/definitions/respond.Review",
      },
    },
    status: {
      type: "string",
      example: "draft",
    },
    templateId: {
      type: "string",
      example: "550e8400-e29b-41d4-a716-446655440000",
    },
    templateName: {
      type: "string",
      example: "регионального уровня",
    },
  },
} as const;

export const respond_AchievementGroupSchema = {
  type: "object",
  required: ["active", "description", "id", "name"],
  properties: {
    active: {
      type: "boolean",
      example: true,
    },
    description: {
      type: "string",
      example: "Достижения в научной деятельности",
    },
    id: {
      type: "string",
      example: "550e8400-e29b-41d4-a716-446655440000",
    },
    name: {
      type: "string",
      example: "Научная деятельность",
    },
  },
} as const;

export const respond_AchievementTemplateSchema = {
  type: "object",
  required: [
    "active",
    "description",
    "groupId",
    "id",
    "name",
    "pointsLimit",
    "reviewerRoleID",
  ],
  properties: {
    active: {
      type: "boolean",
      example: true,
    },
    description: {
      type: "string",
      example: "Публикация статьи в научном журнале",
    },
    groupId: {
      type: "string",
      example: "550e8400-e29b-41d4-a716-446655440000",
    },
    id: {
      type: "string",
      example: "550e8400-e29b-41d4-a716-446655440000",
    },
    name: {
      type: "string",
      example: "Публикация в журнале",
    },
    pointsLimit: {
      type: "integer",
      example: 10,
    },
    reviewerRoleID: {
      type: "string",
    },
  },
} as const;

export const respond_AchievementsSchema = {
  type: "object",
  required: ["achievements", "total"],
  properties: {
    achievements: {
      type: "array",
      items: {
        $ref: "#/definitions/respond.Achievement",
      },
    },
    total: {
      type: "integer",
    },
  },
} as const;

export const respond_DepartmentSchema = {
  type: "object",
  required: ["description", "id", "name"],
  properties: {
    description: {
      type: "string",
      example:
        "Мы в сунце очень любим делать string id. Потому что зачем нам uuid?",
    },
    id: {
      type: "string",
      example: "kaf_bio",
    },
    name: {
      type: "string",
      example: "Кафедра Химии и Биологии",
    },
  },
} as const;

export const respond_DepartmentsSchema = {
  type: "object",
  required: ["departments", "total"],
  properties: {
    departments: {
      type: "array",
      items: {
        $ref: "#/definitions/respond.Department",
      },
    },
    total: {
      type: "integer",
    },
  },
} as const;

export const respond_DocumentSchema = {
  type: "object",
  required: ["fileId", "id", "name"],
  properties: {
    fileId: {
      type: "string",
      example: "550e8400-e29b-41d4-a716-446655440000",
    },
    id: {
      type: "string",
      example: "550e8400-e29b-41d4-a716-446655440000",
    },
    name: {
      type: "string",
      example: "Publication proof",
    },
  },
} as const;

export const respond_ErrorSchema = {
  type: "object",
  properties: {
    code: {
      type: "string",
    },
    message: {
      type: "string",
    },
    statusCode: {
      type: "integer",
    },
    traceId: {
      type: "string",
    },
  },
} as const;

export const respond_FileSchema = {
  type: "object",
  properties: {
    fileName: {
      type: "string",
    },
    fileSize: {
      type: "integer",
    },
    id: {
      type: "string",
    },
    ownerId: {
      type: "string",
    },
  },
} as const;

export const respond_FilesSchema = {
  type: "object",
  properties: {
    files: {
      type: "array",
      items: {
        $ref: "#/definitions/respond.File",
      },
    },
    total: {
      type: "integer",
    },
  },
} as const;

export const respond_ReviewSchema = {
  type: "object",
  required: ["id", "pointsAssigned", "reviewerId"],
  properties: {
    comment: {
      type: "string",
      example: "Good job, but could be better",
    },
    id: {
      type: "string",
      example: "550e8400-e29b-41d4-a716-446655440000",
    },
    pointsAssigned: {
      type: "integer",
      example: 8,
    },
    reviewerId: {
      type: "string",
      example: "ivanivanov",
    },
  },
} as const;

export const respond_RoleSchema = {
  type: "object",
  required: ["codeName", "name"],
  properties: {
    codeName: {
      type: "string",
      example: "teacher",
    },
    name: {
      type: "string",
      example: "Преподаватель",
    },
  },
} as const;

export const respond_UserSchema = {
  type: "object",
  required: [
    "employmentRate",
    "employmentType",
    "fullName",
    "id",
    "jobTitle",
    "personnelCategory",
    "pictureUrl",
    "role",
  ],
  properties: {
    academicDegree: {
      type: "string",
      example: "Доктор наук",
    },
    academicTitle: {
      type: "string",
      example: "Профессор",
    },
    category: {
      type: "string",
      example: "Высшая",
    },
    dateOfEmployment: {
      type: "string",
      example: "24.02.2022",
    },
    departmentId: {
      type: "string",
    },
    employmentRate: {
      type: "string",
      example: "1.0",
    },
    employmentType: {
      type: "string",
      example: "Внешнее совместительство",
    },
    fullName: {
      type: "string",
      example: "Ivanov Ivan Ivanovich",
    },
    honors: {
      type: "string",
      example: "Заслуженный деятель науки",
    },
    id: {
      type: "string",
      example: "ivanivanov",
    },
    jobTitle: {
      type: "string",
      example: "Профессор",
    },
    personnelCategory: {
      type: "string",
      example: "Административно-управленческий персонал",
    },
    pictureUrl: {
      type: "string",
      example: "/images/users/ivan.jpg",
    },
    role: {
      $ref: "#/definitions/respond.Role",
    },
  },
} as const;

export const respond_UsersSchema = {
  type: "object",
  required: ["total", "users"],
  properties: {
    total: {
      type: "integer",
    },
    users: {
      type: "array",
      items: {
        $ref: "#/definitions/respond.User",
      },
    },
  },
} as const;
