// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: string;
};

export type ApiCredentialsRequest = {
  password: string;
  username: string;
};

export type ApiRolesResponse = {
  roles?: Array<RespondRole>;
};

export type ApiTokenResponse = {
  token: string;
  user: RespondUser;
};

export type ParamAddDocumentRequest = {
  fileId: string;
  name: string;
};

export type ParamCreateAchievementGroupRequest = {
  description: string;
  name: string;
};

export type ParamCreateAchievementRequest = {
  templateId: string;
};

export type ParamCreateAchievementTemplateRequest = {
  description: string;
  groupId: string;
  name: string;
  pointsLimit: number;
  reviewerRole: string;
};

export type ParamPatchAchievementGroupRequest = {
  active?: boolean;
  description?: string;
  name?: string;
};

export type ParamPatchAchievementTemplateRequest = {
  active?: boolean;
  description?: string;
  name?: string;
  pointsLimit?: number;
  reviewerRole?: string;
};

export type ParamReviewAchievementRequest = {
  action: "approve" | "disapprove" | "request_changes";
  comment?: string;
};

export type ParamUpdateAchievementPointsRequest = {
  comment?: string;
  points: number;
};

export type RespondAchievement = {
  departmentId: string;
  documents: Array<RespondDocument>;
  id: string;
  maxPoints: number;
  ownerId: string;
  points: number;
  reviews: Array<RespondReview>;
  status: string;
  templateId: string;
  templateName: string;
};

export type RespondAchievementGroup = {
  active: boolean;
  description: string;
  id: string;
  name: string;
};

export type RespondAchievementTemplate = {
  active: boolean;
  description: string;
  groupId: string;
  id: string;
  name: string;
  pointsLimit: number;
  reviewerRoleID: string;
};

export type RespondAchievements = {
  achievements: Array<RespondAchievement>;
  total: number;
};

export type RespondDepartment = {
  description: string;
  id: string;
  name: string;
};

export type RespondDepartments = {
  departments: Array<RespondDepartment>;
  total: number;
};

export type RespondDocument = {
  fileId: string;
  id: string;
  name: string;
};

export type RespondError = {
  code?: string;
  message?: string;
  statusCode?: number;
  traceId?: string;
};

export type RespondFile = {
  fileName?: string;
  fileSize?: number;
  id?: string;
  ownerId?: string;
};

export type RespondFiles = {
  files?: Array<RespondFile>;
  total?: number;
};

export type RespondReview = {
  comment?: string;
  id: string;
  pointsAssigned: number;
  reviewerId: string;
};

export type RespondRole = {
  codeName: string;
  name: string;
};

export type RespondUser = {
  academicDegree?: string;
  academicTitle?: string;
  category?: string;
  dateOfEmployment?: string;
  departmentId?: string;
  employmentRate: string;
  employmentType: string;
  fullName: string;
  honors?: string;
  id: string;
  jobTitle: string;
  personnelCategory: string;
  pictureUrl: string;
  roles: Array<RespondRole>;
};

export type RespondUsers = {
  total: number;
  users: Array<RespondUser>;
};

export type GetAchievementGroupsData = {
  body?: never;
  headers?: {
    /**
     * Bearer JWT token
     */
    Authorization?: string;
  };
  path?: never;
  query?: {
    /**
     * Show inactive groups
     */
    show_inactive?: boolean;
    /**
     * Search by name
     */
    search?: string;
  };
  url: "/achievement-groups";
};

export type GetAchievementGroupsErrors = {
  /**
   * Unauthorized
   */
  401: RespondError;
  /**
   * Internal server error
   */
  500: RespondError;
};

export type GetAchievementGroupsError =
  GetAchievementGroupsErrors[keyof GetAchievementGroupsErrors];

export type GetAchievementGroupsResponses = {
  /**
   * OK
   */
  200: Array<RespondAchievementGroup>;
};

export type GetAchievementGroupsResponse =
  GetAchievementGroupsResponses[keyof GetAchievementGroupsResponses];

export type PostAchievementGroupsData = {
  /**
   * Group details
   */
  body: ParamCreateAchievementGroupRequest;
  headers?: {
    /**
     * Bearer JWT token
     */
    Authorization?: string;
  };
  path?: never;
  query?: never;
  url: "/achievement-groups";
};

export type PostAchievementGroupsErrors = {
  /**
   * Invalid request format
   */
  400: RespondError;
  /**
   * Unauthorized
   */
  401: RespondError;
  /**
   * Forbidden - admin role required
   */
  403: RespondError;
  /**
   * Internal server error
   */
  500: RespondError;
};

export type PostAchievementGroupsError =
  PostAchievementGroupsErrors[keyof PostAchievementGroupsErrors];

export type PostAchievementGroupsResponses = {
  /**
   * Created
   */
  201: RespondAchievementGroup;
};

export type PostAchievementGroupsResponse =
  PostAchievementGroupsResponses[keyof PostAchievementGroupsResponses];

export type PatchAchievementGroupsByIdData = {
  /**
   * Group fields to update
   */
  body: ParamPatchAchievementGroupRequest;
  headers?: {
    /**
     * Bearer JWT token
     */
    Authorization?: string;
  };
  path: {
    /**
     * Group UUID
     */
    id: string;
  };
  query?: never;
  url: "/achievement-groups/{id}";
};

export type PatchAchievementGroupsByIdErrors = {
  /**
   * Invalid request format
   */
  400: RespondError;
  /**
   * Unauthorized
   */
  401: RespondError;
  /**
   * Forbidden - admin role required
   */
  403: RespondError;
  /**
   * Group not found
   */
  404: RespondError;
  /**
   * Internal server error
   */
  500: RespondError;
};

export type PatchAchievementGroupsByIdError =
  PatchAchievementGroupsByIdErrors[keyof PatchAchievementGroupsByIdErrors];

export type PatchAchievementGroupsByIdResponses = {
  /**
   * OK
   */
  200: RespondAchievementGroup;
};

export type PatchAchievementGroupsByIdResponse =
  PatchAchievementGroupsByIdResponses[keyof PatchAchievementGroupsByIdResponses];

export type GetAchievementTemplatesData = {
  body?: never;
  headers?: {
    /**
     * Bearer JWT token
     */
    Authorization?: string;
  };
  path?: never;
  query?: {
    /**
     * Show inactive templates
     */
    show_inactive?: boolean;
    /**
     * Search by name
     */
    search?: string;
  };
  url: "/achievement-templates";
};

export type GetAchievementTemplatesErrors = {
  /**
   * Unauthorized
   */
  401: RespondError;
  /**
   * Internal server error
   */
  500: RespondError;
};

export type GetAchievementTemplatesError =
  GetAchievementTemplatesErrors[keyof GetAchievementTemplatesErrors];

export type GetAchievementTemplatesResponses = {
  /**
   * OK
   */
  200: Array<RespondAchievementTemplate>;
};

export type GetAchievementTemplatesResponse =
  GetAchievementTemplatesResponses[keyof GetAchievementTemplatesResponses];

export type PostAchievementTemplatesData = {
  /**
   * Template details
   */
  body: ParamCreateAchievementTemplateRequest;
  headers?: {
    /**
     * Bearer JWT token
     */
    Authorization?: string;
  };
  path?: never;
  query?: never;
  url: "/achievement-templates";
};

export type PostAchievementTemplatesErrors = {
  /**
   * Invalid request format
   */
  400: RespondError;
  /**
   * Unauthorized
   */
  401: RespondError;
  /**
   * Forbidden - admin role required
   */
  403: RespondError;
  /**
   * Group not found
   */
  404: RespondError;
  /**
   * Internal server error
   */
  500: RespondError;
};

export type PostAchievementTemplatesError =
  PostAchievementTemplatesErrors[keyof PostAchievementTemplatesErrors];

export type PostAchievementTemplatesResponses = {
  /**
   * Created
   */
  201: RespondAchievementTemplate;
};

export type PostAchievementTemplatesResponse =
  PostAchievementTemplatesResponses[keyof PostAchievementTemplatesResponses];

export type PatchAchievementTemplatesByIdData = {
  /**
   * Template fields to update
   */
  body: ParamPatchAchievementTemplateRequest;
  headers?: {
    /**
     * Bearer JWT token
     */
    Authorization?: string;
  };
  path: {
    /**
     * Template UUID
     */
    id: string;
  };
  query?: never;
  url: "/achievement-templates/{id}";
};

export type PatchAchievementTemplatesByIdErrors = {
  /**
   * Invalid request format
   */
  400: RespondError;
  /**
   * Unauthorized
   */
  401: RespondError;
  /**
   * Forbidden - admin role required
   */
  403: RespondError;
  /**
   * Template not found
   */
  404: RespondError;
  /**
   * Internal server error
   */
  500: RespondError;
};

export type PatchAchievementTemplatesByIdError =
  PatchAchievementTemplatesByIdErrors[keyof PatchAchievementTemplatesByIdErrors];

export type PatchAchievementTemplatesByIdResponses = {
  /**
   * OK
   */
  200: RespondAchievementTemplate;
};

export type PatchAchievementTemplatesByIdResponse =
  PatchAchievementTemplatesByIdResponses[keyof PatchAchievementTemplatesByIdResponses];

export type GetAchievementsData = {
  body?: never;
  headers?: {
    /**
     * Bearer JWT token
     */
    Authorization?: string;
  };
  path?: never;
  query?: {
    /**
     * Pagination offset
     */
    offset?: number;
    /**
     * Pagination limit
     */
    limit?: number;
    /**
     * User's ID
     */
    id?: string;
    /**
     * Filter achievements requiring changes
     */
    requiring_changes?: boolean;
  };
  url: "/achievements";
};

export type GetAchievementsErrors = {
  /**
   * Invalid request parameters
   */
  400: RespondError;
  /**
   * Unauthorized
   */
  401: RespondError;
  /**
   * Internal server error
   */
  500: RespondError;
};

export type GetAchievementsError =
  GetAchievementsErrors[keyof GetAchievementsErrors];

export type GetAchievementsResponses = {
  /**
   * OK
   */
  200: RespondAchievements;
};

export type GetAchievementsResponse =
  GetAchievementsResponses[keyof GetAchievementsResponses];

export type PostAchievementsData = {
  /**
   * Achievement creation data
   */
  body: ParamCreateAchievementRequest;
  headers?: {
    /**
     * Bearer JWT token
     */
    Authorization?: string;
  };
  path?: never;
  query?: never;
  url: "/achievements";
};

export type PostAchievementsErrors = {
  /**
   * Invalid request format
   */
  400: RespondError;
  /**
   * Unauthorized
   */
  401: RespondError;
  /**
   * Template not found
   */
  404: RespondError;
  /**
   * Internal server error
   */
  500: RespondError;
};

export type PostAchievementsError =
  PostAchievementsErrors[keyof PostAchievementsErrors];

export type PostAchievementsResponses = {
  /**
   * Created
   */
  201: RespondAchievement;
};

export type PostAchievementsResponse =
  PostAchievementsResponses[keyof PostAchievementsResponses];

export type GetAchievementsUsersData = {
  body?: never;
  headers?: {
    /**
     * Bearer JWT token
     */
    Authorization?: string;
  };
  path?: never;
  query?: {
    /**
     * Pagination offset
     */
    offset?: number;
    /**
     * Pagination limit
     */
    limit?: number;
    /**
     * Search by name
     */
    search?: string;
  };
  url: "/achievements/users";
};

export type GetAchievementsUsersErrors = {
  /**
   * Invalid request parameters
   */
  400: RespondError;
  /**
   * Unauthorized
   */
  401: RespondError;
  /**
   * Forbidden
   */
  403: RespondError;
  /**
   * Internal server error
   */
  500: RespondError;
};

export type GetAchievementsUsersError =
  GetAchievementsUsersErrors[keyof GetAchievementsUsersErrors];

export type GetAchievementsUsersResponses = {
  /**
   * OK
   */
  200: RespondUsers;
};

export type GetAchievementsUsersResponse =
  GetAchievementsUsersResponses[keyof GetAchievementsUsersResponses];

export type DeleteAchievementsByIdData = {
  body?: never;
  headers?: {
    /**
     * Bearer JWT token
     */
    Authorization?: string;
  };
  path: {
    /**
     * Achievement UUID
     */
    id: string;
  };
  query?: never;
  url: "/achievements/{id}";
};

export type DeleteAchievementsByIdErrors = {
  /**
   * Invalid UUID format
   */
  400: RespondError;
  /**
   * Unauthorized
   */
  401: RespondError;
  /**
   * Achievement not found
   */
  404: RespondError;
  /**
   * Wrong achievement status
   */
  409: RespondError;
  /**
   * Internal server error
   */
  500: RespondError;
};

export type DeleteAchievementsByIdError =
  DeleteAchievementsByIdErrors[keyof DeleteAchievementsByIdErrors];

export type DeleteAchievementsByIdResponses = {
  /**
   * No Content
   */
  204: unknown;
};

export type GetAchievementsByIdData = {
  body?: never;
  headers?: {
    /**
     * Bearer JWT token
     */
    Authorization?: string;
  };
  path: {
    /**
     * Achievement UUID
     */
    id: string;
  };
  query?: never;
  url: "/achievements/{id}";
};

export type GetAchievementsByIdErrors = {
  /**
   * Invalid UUID format
   */
  400: RespondError;
  /**
   * Unauthorized
   */
  401: RespondError;
  /**
   * Achievement not found
   */
  404: RespondError;
  /**
   * Internal server error
   */
  500: RespondError;
};

export type GetAchievementsByIdError =
  GetAchievementsByIdErrors[keyof GetAchievementsByIdErrors];

export type GetAchievementsByIdResponses = {
  /**
   * OK
   */
  200: RespondAchievement;
};

export type GetAchievementsByIdResponse =
  GetAchievementsByIdResponses[keyof GetAchievementsByIdResponses];

export type PostAchievementsByIdDocumentsData = {
  /**
   * Document data
   */
  body: ParamAddDocumentRequest;
  headers?: {
    /**
     * Bearer JWT token
     */
    Authorization?: string;
  };
  path: {
    /**
     * Achievement UUID
     */
    id: string;
  };
  query?: never;
  url: "/achievements/{id}/documents";
};

export type PostAchievementsByIdDocumentsErrors = {
  /**
   * Invalid request format
   */
  400: RespondError;
  /**
   * Unauthorized
   */
  401: RespondError;
  /**
   * Achievement not found
   */
  404: RespondError;
  /**
   * Wrong achievement status
   */
  409: RespondError;
  /**
   * Internal server error
   */
  500: RespondError;
};

export type PostAchievementsByIdDocumentsError =
  PostAchievementsByIdDocumentsErrors[keyof PostAchievementsByIdDocumentsErrors];

export type PostAchievementsByIdDocumentsResponses = {
  /**
   * Created
   */
  201: RespondDocument;
};

export type PostAchievementsByIdDocumentsResponse =
  PostAchievementsByIdDocumentsResponses[keyof PostAchievementsByIdDocumentsResponses];

export type DeleteAchievementsByIdDocumentsByDocumentIdData = {
  body?: never;
  headers?: {
    /**
     * Bearer JWT token
     */
    Authorization?: string;
  };
  path: {
    /**
     * Achievement UUID
     */
    id: string;
    /**
     * Document UUID
     */
    documentId: string;
  };
  query?: never;
  url: "/achievements/{id}/documents/{documentId}";
};

export type DeleteAchievementsByIdDocumentsByDocumentIdErrors = {
  /**
   * Invalid UUID format
   */
  400: RespondError;
  /**
   * Unauthorized
   */
  401: RespondError;
  /**
   * Document not found
   */
  404: RespondError;
  /**
   * Wrong achievement status
   */
  409: RespondError;
  /**
   * Internal server error
   */
  500: RespondError;
};

export type DeleteAchievementsByIdDocumentsByDocumentIdError =
  DeleteAchievementsByIdDocumentsByDocumentIdErrors[keyof DeleteAchievementsByIdDocumentsByDocumentIdErrors];

export type DeleteAchievementsByIdDocumentsByDocumentIdResponses = {
  /**
   * No Content
   */
  204: unknown;
};

export type PostAchievementsByIdReviewData = {
  /**
   * Review data
   */
  body: ParamReviewAchievementRequest;
  headers?: {
    /**
     * Bearer JWT token
     */
    Authorization?: string;
  };
  path: {
    /**
     * Achievement UUID
     */
    id: string;
  };
  query?: never;
  url: "/achievements/{id}/review";
};

export type PostAchievementsByIdReviewErrors = {
  /**
   * Invalid review action
   */
  400: RespondError;
  /**
   * Unauthorized
   */
  401: RespondError;
  /**
   * Forbidden - reviewer role required
   */
  403: RespondError;
  /**
   * Achievement not found
   */
  404: RespondError;
  /**
   * Wrong achievement status
   */
  409: RespondError;
  /**
   * Internal server error
   */
  500: RespondError;
};

export type PostAchievementsByIdReviewError =
  PostAchievementsByIdReviewErrors[keyof PostAchievementsByIdReviewErrors];

export type PostAchievementsByIdReviewResponses = {
  /**
   * OK
   */
  200: RespondAchievement;
};

export type PostAchievementsByIdReviewResponse =
  PostAchievementsByIdReviewResponses[keyof PostAchievementsByIdReviewResponses];

export type PostAchievementsByIdSubmitData = {
  body?: never;
  headers?: {
    /**
     * Bearer JWT token
     */
    Authorization?: string;
  };
  path: {
    /**
     * Achievement UUID
     */
    id: string;
  };
  query?: never;
  url: "/achievements/{id}/submit";
};

export type PostAchievementsByIdSubmitErrors = {
  /**
   * Invalid UUID format
   */
  400: RespondError;
  /**
   * Unauthorized
   */
  401: RespondError;
  /**
   * Achievement not found
   */
  404: RespondError;
  /**
   * Wrong achievement status
   */
  409: RespondError;
  /**
   * Internal server error
   */
  500: RespondError;
};

export type PostAchievementsByIdSubmitError =
  PostAchievementsByIdSubmitErrors[keyof PostAchievementsByIdSubmitErrors];

export type PostAchievementsByIdSubmitResponses = {
  /**
   * OK
   */
  200: RespondAchievement;
};

export type PostAchievementsByIdSubmitResponse =
  PostAchievementsByIdSubmitResponses[keyof PostAchievementsByIdSubmitResponses];

export type PostAchievementsByIdSubmitWithNewPointsData = {
  /**
   * Points update data
   */
  body: ParamUpdateAchievementPointsRequest;
  headers?: {
    /**
     * Bearer JWT token
     */
    Authorization?: string;
  };
  path: {
    /**
     * Achievement UUID
     */
    id: string;
  };
  query?: never;
  url: "/achievements/{id}/submit-with-new-points";
};

export type PostAchievementsByIdSubmitWithNewPointsErrors = {
  /**
   * Points exceed template limit
   */
  400: RespondError;
  /**
   * Unauthorized
   */
  401: RespondError;
  /**
   * Forbidden - only achievement owner can update points
   */
  403: RespondError;
  /**
   * Achievement not found
   */
  404: RespondError;
  /**
   * Wrong achievement status - changes not requested
   */
  409: RespondError;
  /**
   * Internal server error
   */
  500: RespondError;
};

export type PostAchievementsByIdSubmitWithNewPointsError =
  PostAchievementsByIdSubmitWithNewPointsErrors[keyof PostAchievementsByIdSubmitWithNewPointsErrors];

export type PostAchievementsByIdSubmitWithNewPointsResponses = {
  /**
   * OK
   */
  200: RespondAchievement;
};

export type PostAchievementsByIdSubmitWithNewPointsResponse =
  PostAchievementsByIdSubmitWithNewPointsResponses[keyof PostAchievementsByIdSubmitWithNewPointsResponses];

export type PostAuthLoginData = {
  /**
   * User credentials
   */
  body: ApiCredentialsRequest;
  path?: never;
  query?: never;
  url: "/auth/login";
};

export type PostAuthLoginErrors = {
  /**
   * Invalid request format
   */
  400: RespondError;
  /**
   * Invalid credentials or user does not exist
   */
  401: RespondError;
  /**
   * Internal server error
   */
  500: RespondError;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
  /**
   * OK
   */
  200: ApiTokenResponse;
};

export type PostAuthLoginResponse =
  PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type GetAuthValidateData = {
  body?: never;
  headers?: {
    /**
     * Bearer JWT token
     */
    Authorization?: string;
  };
  path?: never;
  query?: never;
  url: "/auth/validate";
};

export type GetAuthValidateErrors = {
  /**
   * Invalid token
   */
  401: RespondError;
  /**
   * Internal server error
   */
  500: RespondError;
};

export type GetAuthValidateError =
  GetAuthValidateErrors[keyof GetAuthValidateErrors];

export type GetAuthValidateResponses = {
  /**
   * OK
   */
  200: RespondUser;
};

export type GetAuthValidateResponse =
  GetAuthValidateResponses[keyof GetAuthValidateResponses];

export type GetDepartmentsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/departments";
};

export type GetDepartmentsErrors = {
  /**
   * Internal server error
   */
  500: RespondError;
};

export type GetDepartmentsError =
  GetDepartmentsErrors[keyof GetDepartmentsErrors];

export type GetDepartmentsResponses = {
  /**
   * OK
   */
  200: RespondDepartments;
};

export type GetDepartmentsResponse =
  GetDepartmentsResponses[keyof GetDepartmentsResponses];

export type GetDepartmentsByIdData = {
  body?: never;
  headers?: {
    /**
     * Bearer JWT token
     */
    Authorization?: string;
  };
  path: {
    /**
     * Department ID
     */
    id: string;
  };
  query?: never;
  url: "/departments/{id}";
};

export type GetDepartmentsByIdErrors = {
  /**
   * Invalid UUID format
   */
  400: RespondError;
  /**
   * Department not found
   */
  404: RespondError;
  /**
   * Internal server error
   */
  500: RespondError;
};

export type GetDepartmentsByIdError =
  GetDepartmentsByIdErrors[keyof GetDepartmentsByIdErrors];

export type GetDepartmentsByIdResponses = {
  /**
   * OK
   */
  200: RespondDepartment;
};

export type GetDepartmentsByIdResponse =
  GetDepartmentsByIdResponses[keyof GetDepartmentsByIdResponses];

export type GetFilesData = {
  body?: never;
  headers?: {
    /**
     * Bearer JWT token
     */
    Authorization?: string;
  };
  path?: never;
  query?: {
    /**
     * File name to search for
     */
    name?: string;
    /**
     * Owner ID to filter by
     */
    owner_id?: string;
    /**
     * If true, return only common files
     */
    common?: boolean;
    /**
     * Pagination offset
     */
    offset?: number;
    /**
     * Pagination limit
     */
    limit?: number;
  };
  url: "/files";
};

export type GetFilesErrors = {
  /**
   * Bad Request
   */
  400: RespondError;
  /**
   * Internal Server Error
   */
  500: RespondError;
};

export type GetFilesError = GetFilesErrors[keyof GetFilesErrors];

export type GetFilesResponses = {
  /**
   * OK
   */
  200: RespondFiles;
};

export type GetFilesResponse = GetFilesResponses[keyof GetFilesResponses];

export type PostFilesData = {
  body: {
    /**
     * File to upload
     */
    file: Blob | File;
  };
  headers?: {
    /**
     * Bearer JWT token
     */
    Authorization?: string;
  };
  path?: never;
  query?: never;
  url: "/files";
};

export type PostFilesErrors = {
  /**
   * Bad Request
   */
  400: RespondError;
  /**
   * Unauthorized
   */
  401: RespondError;
  /**
   * Internal Server Error
   */
  500: RespondError;
};

export type PostFilesError = PostFilesErrors[keyof PostFilesErrors];

export type PostFilesResponses = {
  /**
   * Created
   */
  201: RespondFile;
};

export type PostFilesResponse = PostFilesResponses[keyof PostFilesResponses];

export type DeleteFilesByIdData = {
  body?: never;
  headers?: {
    /**
     * Bearer JWT token
     */
    Authorization?: string;
  };
  path: {
    /**
     * File ID
     */
    id: string;
  };
  query?: never;
  url: "/files/{id}";
};

export type DeleteFilesByIdErrors = {
  /**
   * Bad Request
   */
  400: RespondError;
  /**
   * Unauthorized
   */
  401: RespondError;
  /**
   * Forbidden
   */
  403: RespondError;
  /**
   * Not Found
   */
  404: RespondError;
  /**
   * Internal Server Error
   */
  500: RespondError;
};

export type DeleteFilesByIdError =
  DeleteFilesByIdErrors[keyof DeleteFilesByIdErrors];

export type DeleteFilesByIdResponses = {
  /**
   * No Content
   */
  204: unknown;
};

export type GetFilesByIdData = {
  body?: never;
  headers?: {
    /**
     * Bearer JWT token
     */
    Authorization?: string;
  };
  path: {
    /**
     * File ID
     */
    id: string;
  };
  query?: never;
  url: "/files/{id}";
};

export type GetFilesByIdErrors = {
  /**
   * Bad Request
   */
  400: RespondError;
  /**
   * Unauthorized
   */
  401: RespondError;
  /**
   * Not Found
   */
  404: RespondError;
  /**
   * Internal Server Error
   */
  500: RespondError;
};

export type GetFilesByIdError = GetFilesByIdErrors[keyof GetFilesByIdErrors];

export type GetFilesByIdResponses = {
  /**
   * OK
   */
  200: RespondFile;
};

export type GetFilesByIdResponse =
  GetFilesByIdResponses[keyof GetFilesByIdResponses];

export type GetFilesByIdDownloadData = {
  body?: never;
  headers?: {
    /**
     * Bearer JWT token
     */
    Authorization?: string;
  };
  path: {
    /**
     * File ID
     */
    id: string;
  };
  query?: never;
  url: "/files/{id}/download";
};

export type GetFilesByIdDownloadErrors = {
  /**
   * Bad Request
   */
  400: RespondError;
  /**
   * Unauthorized
   */
  401: RespondError;
  /**
   * Forbidden
   */
  403: RespondError;
  /**
   * Not Found
   */
  404: RespondError;
  /**
   * Internal Server Error
   */
  500: RespondError;
};

export type GetFilesByIdDownloadError =
  GetFilesByIdDownloadErrors[keyof GetFilesByIdDownloadErrors];

export type PostReportsMarkAllAccountedData = {
  body?: never;
  headers?: {
    /**
     * Bearer JWT token
     */
    Authorization?: string;
  };
  path?: never;
  query?: never;
  url: "/reports/mark-all-accounted";
};

export type PostReportsMarkAllAccountedErrors = {
  /**
   * Unauthorized
   */
  401: RespondError;
  /**
   * Forbidden - Economist access required
   */
  403: RespondError;
  /**
   * Internal server error
   */
  500: RespondError;
};

export type PostReportsMarkAllAccountedError =
  PostReportsMarkAllAccountedErrors[keyof PostReportsMarkAllAccountedErrors];

export type PostReportsMarkAllAccountedResponses = {
  /**
   * Success response
   */
  200: {
    [key: string]: unknown;
  };
};

export type PostReportsMarkAllAccountedResponse =
  PostReportsMarkAllAccountedResponses[keyof PostReportsMarkAllAccountedResponses];

export type GetReportsUserPointsData = {
  body?: never;
  headers?: {
    /**
     * Bearer JWT token
     */
    Authorization?: string;
  };
  path?: never;
  query?: never;
  url: "/reports/user-points";
};

export type GetReportsUserPointsErrors = {
  /**
   * Unauthorized
   */
  401: RespondError;
  /**
   * Forbidden - Admin access required
   */
  403: RespondError;
  /**
   * Internal server error
   */
  500: RespondError;
};

export type GetReportsUserPointsError =
  GetReportsUserPointsErrors[keyof GetReportsUserPointsErrors];

export type GetReportsUserPointsResponses = {
  /**
   * Excel file with user points report
   */
  200: unknown;
};

export type GetRolesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/roles";
};

export type GetRolesErrors = {
  /**
   * Internal server error
   */
  500: RespondError;
};

export type GetRolesError = GetRolesErrors[keyof GetRolesErrors];

export type GetRolesResponses = {
  /**
   * OK
   */
  200: ApiRolesResponse;
};

export type GetRolesResponse = GetRolesResponses[keyof GetRolesResponses];

export type GetUsersData = {
  body?: never;
  headers?: {
    /**
     * Bearer JWT token
     */
    Authorization?: string;
  };
  path?: never;
  query?: {
    /**
     * Search by name
     */
    search?: string;
  };
  url: "/users";
};

export type GetUsersErrors = {
  /**
   * Unauthorized
   */
  401: RespondError;
  /**
   * Internal server error
   */
  500: RespondError;
};

export type GetUsersError = GetUsersErrors[keyof GetUsersErrors];

export type GetUsersResponses = {
  /**
   * OK
   */
  200: RespondUsers;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type GetUsersMeData = {
  body?: never;
  headers?: {
    /**
     * Bearer JWT token
     */
    Authorization?: string;
  };
  path?: never;
  query?: never;
  url: "/users/me";
};

export type GetUsersMeErrors = {
  /**
   * Unauthorized or invalid token
   */
  401: RespondError;
  /**
   * User not found
   */
  404: RespondError;
  /**
   * Internal server error
   */
  500: RespondError;
};

export type GetUsersMeError = GetUsersMeErrors[keyof GetUsersMeErrors];

export type GetUsersMeResponses = {
  /**
   * OK
   */
  200: RespondUser;
};

export type GetUsersMeResponse = GetUsersMeResponses[keyof GetUsersMeResponses];

export type GetUsersByIdData = {
  body?: never;
  headers?: {
    /**
     * Bearer JWT token
     */
    Authorization?: string;
  };
  path: {
    /**
     * User ID
     */
    id: string;
  };
  query?: never;
  url: "/users/{id}";
};

export type GetUsersByIdErrors = {
  /**
   * Invalid UUID format
   */
  400: RespondError;
  /**
   * Unauthorized
   */
  401: RespondError;
  /**
   * User not found
   */
  404: RespondError;
  /**
   * Internal server error
   */
  500: RespondError;
};

export type GetUsersByIdError = GetUsersByIdErrors[keyof GetUsersByIdErrors];

export type GetUsersByIdResponses = {
  /**
   * OK
   */
  200: RespondUser;
};

export type GetUsersByIdResponse =
  GetUsersByIdResponses[keyof GetUsersByIdResponses];
