// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/kozlov-ma/sesc-backend/db/entdb/ent/accountingperiod"
	"github.com/kozlov-ma/sesc-backend/db/entdb/ent/file"
	"github.com/kozlov-ma/sesc-backend/db/entdb/ent/predicate"
)

// AccountingPeriodUpdate is the builder for updating AccountingPeriod entities.
type AccountingPeriodUpdate struct {
	config
	hooks    []Hook
	mutation *AccountingPeriodMutation
}

// Where appends a list predicates to the AccountingPeriodUpdate builder.
func (apu *AccountingPeriodUpdate) Where(ps ...predicate.AccountingPeriod) *AccountingPeriodUpdate {
	apu.mutation.Where(ps...)
	return apu
}

// SetName sets the "name" field.
func (apu *AccountingPeriodUpdate) SetName(s string) *AccountingPeriodUpdate {
	apu.mutation.SetName(s)
	return apu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (apu *AccountingPeriodUpdate) SetNillableName(s *string) *AccountingPeriodUpdate {
	if s != nil {
		apu.SetName(*s)
	}
	return apu
}

// SetDescription sets the "description" field.
func (apu *AccountingPeriodUpdate) SetDescription(s string) *AccountingPeriodUpdate {
	apu.mutation.SetDescription(s)
	return apu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (apu *AccountingPeriodUpdate) SetNillableDescription(s *string) *AccountingPeriodUpdate {
	if s != nil {
		apu.SetDescription(*s)
	}
	return apu
}

// ClearDescription clears the value of the "description" field.
func (apu *AccountingPeriodUpdate) ClearDescription() *AccountingPeriodUpdate {
	apu.mutation.ClearDescription()
	return apu
}

// SetStartPlanningDate sets the "start_planning_date" field.
func (apu *AccountingPeriodUpdate) SetStartPlanningDate(t time.Time) *AccountingPeriodUpdate {
	apu.mutation.SetStartPlanningDate(t)
	return apu
}

// SetNillableStartPlanningDate sets the "start_planning_date" field if the given value is not nil.
func (apu *AccountingPeriodUpdate) SetNillableStartPlanningDate(t *time.Time) *AccountingPeriodUpdate {
	if t != nil {
		apu.SetStartPlanningDate(*t)
	}
	return apu
}

// ClearStartPlanningDate clears the value of the "start_planning_date" field.
func (apu *AccountingPeriodUpdate) ClearStartPlanningDate() *AccountingPeriodUpdate {
	apu.mutation.ClearStartPlanningDate()
	return apu
}

// SetStartAchievementCollectionDate sets the "start_achievement_collection_date" field.
func (apu *AccountingPeriodUpdate) SetStartAchievementCollectionDate(t time.Time) *AccountingPeriodUpdate {
	apu.mutation.SetStartAchievementCollectionDate(t)
	return apu
}

// SetNillableStartAchievementCollectionDate sets the "start_achievement_collection_date" field if the given value is not nil.
func (apu *AccountingPeriodUpdate) SetNillableStartAchievementCollectionDate(t *time.Time) *AccountingPeriodUpdate {
	if t != nil {
		apu.SetStartAchievementCollectionDate(*t)
	}
	return apu
}

// ClearStartAchievementCollectionDate clears the value of the "start_achievement_collection_date" field.
func (apu *AccountingPeriodUpdate) ClearStartAchievementCollectionDate() *AccountingPeriodUpdate {
	apu.mutation.ClearStartAchievementCollectionDate()
	return apu
}

// SetFinishDate sets the "finish_date" field.
func (apu *AccountingPeriodUpdate) SetFinishDate(t time.Time) *AccountingPeriodUpdate {
	apu.mutation.SetFinishDate(t)
	return apu
}

// SetNillableFinishDate sets the "finish_date" field if the given value is not nil.
func (apu *AccountingPeriodUpdate) SetNillableFinishDate(t *time.Time) *AccountingPeriodUpdate {
	if t != nil {
		apu.SetFinishDate(*t)
	}
	return apu
}

// ClearFinishDate clears the value of the "finish_date" field.
func (apu *AccountingPeriodUpdate) ClearFinishDate() *AccountingPeriodUpdate {
	apu.mutation.ClearFinishDate()
	return apu
}

// SetCancelDate sets the "cancel_date" field.
func (apu *AccountingPeriodUpdate) SetCancelDate(t time.Time) *AccountingPeriodUpdate {
	apu.mutation.SetCancelDate(t)
	return apu
}

// SetNillableCancelDate sets the "cancel_date" field if the given value is not nil.
func (apu *AccountingPeriodUpdate) SetNillableCancelDate(t *time.Time) *AccountingPeriodUpdate {
	if t != nil {
		apu.SetCancelDate(*t)
	}
	return apu
}

// ClearCancelDate clears the value of the "cancel_date" field.
func (apu *AccountingPeriodUpdate) ClearCancelDate() *AccountingPeriodUpdate {
	apu.mutation.ClearCancelDate()
	return apu
}

// SetBecameNonExecutedDate sets the "became_non_executed_date" field.
func (apu *AccountingPeriodUpdate) SetBecameNonExecutedDate(t time.Time) *AccountingPeriodUpdate {
	apu.mutation.SetBecameNonExecutedDate(t)
	return apu
}

// SetNillableBecameNonExecutedDate sets the "became_non_executed_date" field if the given value is not nil.
func (apu *AccountingPeriodUpdate) SetNillableBecameNonExecutedDate(t *time.Time) *AccountingPeriodUpdate {
	if t != nil {
		apu.SetBecameNonExecutedDate(*t)
	}
	return apu
}

// ClearBecameNonExecutedDate clears the value of the "became_non_executed_date" field.
func (apu *AccountingPeriodUpdate) ClearBecameNonExecutedDate() *AccountingPeriodUpdate {
	apu.mutation.ClearBecameNonExecutedDate()
	return apu
}

// SetStatus sets the "status" field.
func (apu *AccountingPeriodUpdate) SetStatus(s string) *AccountingPeriodUpdate {
	apu.mutation.SetStatus(s)
	return apu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (apu *AccountingPeriodUpdate) SetNillableStatus(s *string) *AccountingPeriodUpdate {
	if s != nil {
		apu.SetStatus(*s)
	}
	return apu
}

// AddFileIDs adds the "files" edge to the File entity by IDs.
func (apu *AccountingPeriodUpdate) AddFileIDs(ids ...uuid.UUID) *AccountingPeriodUpdate {
	apu.mutation.AddFileIDs(ids...)
	return apu
}

// AddFiles adds the "files" edges to the File entity.
func (apu *AccountingPeriodUpdate) AddFiles(f ...*File) *AccountingPeriodUpdate {
	ids := make([]uuid.UUID, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return apu.AddFileIDs(ids...)
}

// Mutation returns the AccountingPeriodMutation object of the builder.
func (apu *AccountingPeriodUpdate) Mutation() *AccountingPeriodMutation {
	return apu.mutation
}

// ClearFiles clears all "files" edges to the File entity.
func (apu *AccountingPeriodUpdate) ClearFiles() *AccountingPeriodUpdate {
	apu.mutation.ClearFiles()
	return apu
}

// RemoveFileIDs removes the "files" edge to File entities by IDs.
func (apu *AccountingPeriodUpdate) RemoveFileIDs(ids ...uuid.UUID) *AccountingPeriodUpdate {
	apu.mutation.RemoveFileIDs(ids...)
	return apu
}

// RemoveFiles removes "files" edges to File entities.
func (apu *AccountingPeriodUpdate) RemoveFiles(f ...*File) *AccountingPeriodUpdate {
	ids := make([]uuid.UUID, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return apu.RemoveFileIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (apu *AccountingPeriodUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, apu.sqlSave, apu.mutation, apu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (apu *AccountingPeriodUpdate) SaveX(ctx context.Context) int {
	affected, err := apu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (apu *AccountingPeriodUpdate) Exec(ctx context.Context) error {
	_, err := apu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (apu *AccountingPeriodUpdate) ExecX(ctx context.Context) {
	if err := apu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (apu *AccountingPeriodUpdate) check() error {
	if v, ok := apu.mutation.Name(); ok {
		if err := accountingperiod.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccountingPeriod.name": %w`, err)}
		}
	}
	if v, ok := apu.mutation.Status(); ok {
		if err := accountingperiod.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AccountingPeriod.status": %w`, err)}
		}
	}
	return nil
}

func (apu *AccountingPeriodUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := apu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountingperiod.Table, accountingperiod.Columns, sqlgraph.NewFieldSpec(accountingperiod.FieldID, field.TypeInt))
	if ps := apu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := apu.mutation.Name(); ok {
		_spec.SetField(accountingperiod.FieldName, field.TypeString, value)
	}
	if value, ok := apu.mutation.Description(); ok {
		_spec.SetField(accountingperiod.FieldDescription, field.TypeString, value)
	}
	if apu.mutation.DescriptionCleared() {
		_spec.ClearField(accountingperiod.FieldDescription, field.TypeString)
	}
	if value, ok := apu.mutation.StartPlanningDate(); ok {
		_spec.SetField(accountingperiod.FieldStartPlanningDate, field.TypeTime, value)
	}
	if apu.mutation.StartPlanningDateCleared() {
		_spec.ClearField(accountingperiod.FieldStartPlanningDate, field.TypeTime)
	}
	if value, ok := apu.mutation.StartAchievementCollectionDate(); ok {
		_spec.SetField(accountingperiod.FieldStartAchievementCollectionDate, field.TypeTime, value)
	}
	if apu.mutation.StartAchievementCollectionDateCleared() {
		_spec.ClearField(accountingperiod.FieldStartAchievementCollectionDate, field.TypeTime)
	}
	if value, ok := apu.mutation.FinishDate(); ok {
		_spec.SetField(accountingperiod.FieldFinishDate, field.TypeTime, value)
	}
	if apu.mutation.FinishDateCleared() {
		_spec.ClearField(accountingperiod.FieldFinishDate, field.TypeTime)
	}
	if value, ok := apu.mutation.CancelDate(); ok {
		_spec.SetField(accountingperiod.FieldCancelDate, field.TypeTime, value)
	}
	if apu.mutation.CancelDateCleared() {
		_spec.ClearField(accountingperiod.FieldCancelDate, field.TypeTime)
	}
	if value, ok := apu.mutation.BecameNonExecutedDate(); ok {
		_spec.SetField(accountingperiod.FieldBecameNonExecutedDate, field.TypeTime, value)
	}
	if apu.mutation.BecameNonExecutedDateCleared() {
		_spec.ClearField(accountingperiod.FieldBecameNonExecutedDate, field.TypeTime)
	}
	if value, ok := apu.mutation.Status(); ok {
		_spec.SetField(accountingperiod.FieldStatus, field.TypeString, value)
	}
	if apu.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accountingperiod.FilesTable,
			Columns: []string{accountingperiod.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := apu.mutation.RemovedFilesIDs(); len(nodes) > 0 && !apu.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accountingperiod.FilesTable,
			Columns: []string{accountingperiod.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := apu.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accountingperiod.FilesTable,
			Columns: []string{accountingperiod.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, apu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountingperiod.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	apu.mutation.done = true
	return n, nil
}

// AccountingPeriodUpdateOne is the builder for updating a single AccountingPeriod entity.
type AccountingPeriodUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountingPeriodMutation
}

// SetName sets the "name" field.
func (apuo *AccountingPeriodUpdateOne) SetName(s string) *AccountingPeriodUpdateOne {
	apuo.mutation.SetName(s)
	return apuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (apuo *AccountingPeriodUpdateOne) SetNillableName(s *string) *AccountingPeriodUpdateOne {
	if s != nil {
		apuo.SetName(*s)
	}
	return apuo
}

// SetDescription sets the "description" field.
func (apuo *AccountingPeriodUpdateOne) SetDescription(s string) *AccountingPeriodUpdateOne {
	apuo.mutation.SetDescription(s)
	return apuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (apuo *AccountingPeriodUpdateOne) SetNillableDescription(s *string) *AccountingPeriodUpdateOne {
	if s != nil {
		apuo.SetDescription(*s)
	}
	return apuo
}

// ClearDescription clears the value of the "description" field.
func (apuo *AccountingPeriodUpdateOne) ClearDescription() *AccountingPeriodUpdateOne {
	apuo.mutation.ClearDescription()
	return apuo
}

// SetStartPlanningDate sets the "start_planning_date" field.
func (apuo *AccountingPeriodUpdateOne) SetStartPlanningDate(t time.Time) *AccountingPeriodUpdateOne {
	apuo.mutation.SetStartPlanningDate(t)
	return apuo
}

// SetNillableStartPlanningDate sets the "start_planning_date" field if the given value is not nil.
func (apuo *AccountingPeriodUpdateOne) SetNillableStartPlanningDate(t *time.Time) *AccountingPeriodUpdateOne {
	if t != nil {
		apuo.SetStartPlanningDate(*t)
	}
	return apuo
}

// ClearStartPlanningDate clears the value of the "start_planning_date" field.
func (apuo *AccountingPeriodUpdateOne) ClearStartPlanningDate() *AccountingPeriodUpdateOne {
	apuo.mutation.ClearStartPlanningDate()
	return apuo
}

// SetStartAchievementCollectionDate sets the "start_achievement_collection_date" field.
func (apuo *AccountingPeriodUpdateOne) SetStartAchievementCollectionDate(t time.Time) *AccountingPeriodUpdateOne {
	apuo.mutation.SetStartAchievementCollectionDate(t)
	return apuo
}

// SetNillableStartAchievementCollectionDate sets the "start_achievement_collection_date" field if the given value is not nil.
func (apuo *AccountingPeriodUpdateOne) SetNillableStartAchievementCollectionDate(t *time.Time) *AccountingPeriodUpdateOne {
	if t != nil {
		apuo.SetStartAchievementCollectionDate(*t)
	}
	return apuo
}

// ClearStartAchievementCollectionDate clears the value of the "start_achievement_collection_date" field.
func (apuo *AccountingPeriodUpdateOne) ClearStartAchievementCollectionDate() *AccountingPeriodUpdateOne {
	apuo.mutation.ClearStartAchievementCollectionDate()
	return apuo
}

// SetFinishDate sets the "finish_date" field.
func (apuo *AccountingPeriodUpdateOne) SetFinishDate(t time.Time) *AccountingPeriodUpdateOne {
	apuo.mutation.SetFinishDate(t)
	return apuo
}

// SetNillableFinishDate sets the "finish_date" field if the given value is not nil.
func (apuo *AccountingPeriodUpdateOne) SetNillableFinishDate(t *time.Time) *AccountingPeriodUpdateOne {
	if t != nil {
		apuo.SetFinishDate(*t)
	}
	return apuo
}

// ClearFinishDate clears the value of the "finish_date" field.
func (apuo *AccountingPeriodUpdateOne) ClearFinishDate() *AccountingPeriodUpdateOne {
	apuo.mutation.ClearFinishDate()
	return apuo
}

// SetCancelDate sets the "cancel_date" field.
func (apuo *AccountingPeriodUpdateOne) SetCancelDate(t time.Time) *AccountingPeriodUpdateOne {
	apuo.mutation.SetCancelDate(t)
	return apuo
}

// SetNillableCancelDate sets the "cancel_date" field if the given value is not nil.
func (apuo *AccountingPeriodUpdateOne) SetNillableCancelDate(t *time.Time) *AccountingPeriodUpdateOne {
	if t != nil {
		apuo.SetCancelDate(*t)
	}
	return apuo
}

// ClearCancelDate clears the value of the "cancel_date" field.
func (apuo *AccountingPeriodUpdateOne) ClearCancelDate() *AccountingPeriodUpdateOne {
	apuo.mutation.ClearCancelDate()
	return apuo
}

// SetBecameNonExecutedDate sets the "became_non_executed_date" field.
func (apuo *AccountingPeriodUpdateOne) SetBecameNonExecutedDate(t time.Time) *AccountingPeriodUpdateOne {
	apuo.mutation.SetBecameNonExecutedDate(t)
	return apuo
}

// SetNillableBecameNonExecutedDate sets the "became_non_executed_date" field if the given value is not nil.
func (apuo *AccountingPeriodUpdateOne) SetNillableBecameNonExecutedDate(t *time.Time) *AccountingPeriodUpdateOne {
	if t != nil {
		apuo.SetBecameNonExecutedDate(*t)
	}
	return apuo
}

// ClearBecameNonExecutedDate clears the value of the "became_non_executed_date" field.
func (apuo *AccountingPeriodUpdateOne) ClearBecameNonExecutedDate() *AccountingPeriodUpdateOne {
	apuo.mutation.ClearBecameNonExecutedDate()
	return apuo
}

// SetStatus sets the "status" field.
func (apuo *AccountingPeriodUpdateOne) SetStatus(s string) *AccountingPeriodUpdateOne {
	apuo.mutation.SetStatus(s)
	return apuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (apuo *AccountingPeriodUpdateOne) SetNillableStatus(s *string) *AccountingPeriodUpdateOne {
	if s != nil {
		apuo.SetStatus(*s)
	}
	return apuo
}

// AddFileIDs adds the "files" edge to the File entity by IDs.
func (apuo *AccountingPeriodUpdateOne) AddFileIDs(ids ...uuid.UUID) *AccountingPeriodUpdateOne {
	apuo.mutation.AddFileIDs(ids...)
	return apuo
}

// AddFiles adds the "files" edges to the File entity.
func (apuo *AccountingPeriodUpdateOne) AddFiles(f ...*File) *AccountingPeriodUpdateOne {
	ids := make([]uuid.UUID, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return apuo.AddFileIDs(ids...)
}

// Mutation returns the AccountingPeriodMutation object of the builder.
func (apuo *AccountingPeriodUpdateOne) Mutation() *AccountingPeriodMutation {
	return apuo.mutation
}

// ClearFiles clears all "files" edges to the File entity.
func (apuo *AccountingPeriodUpdateOne) ClearFiles() *AccountingPeriodUpdateOne {
	apuo.mutation.ClearFiles()
	return apuo
}

// RemoveFileIDs removes the "files" edge to File entities by IDs.
func (apuo *AccountingPeriodUpdateOne) RemoveFileIDs(ids ...uuid.UUID) *AccountingPeriodUpdateOne {
	apuo.mutation.RemoveFileIDs(ids...)
	return apuo
}

// RemoveFiles removes "files" edges to File entities.
func (apuo *AccountingPeriodUpdateOne) RemoveFiles(f ...*File) *AccountingPeriodUpdateOne {
	ids := make([]uuid.UUID, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return apuo.RemoveFileIDs(ids...)
}

// Where appends a list predicates to the AccountingPeriodUpdate builder.
func (apuo *AccountingPeriodUpdateOne) Where(ps ...predicate.AccountingPeriod) *AccountingPeriodUpdateOne {
	apuo.mutation.Where(ps...)
	return apuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (apuo *AccountingPeriodUpdateOne) Select(field string, fields ...string) *AccountingPeriodUpdateOne {
	apuo.fields = append([]string{field}, fields...)
	return apuo
}

// Save executes the query and returns the updated AccountingPeriod entity.
func (apuo *AccountingPeriodUpdateOne) Save(ctx context.Context) (*AccountingPeriod, error) {
	return withHooks(ctx, apuo.sqlSave, apuo.mutation, apuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (apuo *AccountingPeriodUpdateOne) SaveX(ctx context.Context) *AccountingPeriod {
	node, err := apuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (apuo *AccountingPeriodUpdateOne) Exec(ctx context.Context) error {
	_, err := apuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (apuo *AccountingPeriodUpdateOne) ExecX(ctx context.Context) {
	if err := apuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (apuo *AccountingPeriodUpdateOne) check() error {
	if v, ok := apuo.mutation.Name(); ok {
		if err := accountingperiod.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AccountingPeriod.name": %w`, err)}
		}
	}
	if v, ok := apuo.mutation.Status(); ok {
		if err := accountingperiod.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AccountingPeriod.status": %w`, err)}
		}
	}
	return nil
}

func (apuo *AccountingPeriodUpdateOne) sqlSave(ctx context.Context) (_node *AccountingPeriod, err error) {
	if err := apuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountingperiod.Table, accountingperiod.Columns, sqlgraph.NewFieldSpec(accountingperiod.FieldID, field.TypeInt))
	id, ok := apuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountingPeriod.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := apuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountingperiod.FieldID)
		for _, f := range fields {
			if !accountingperiod.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountingperiod.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := apuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := apuo.mutation.Name(); ok {
		_spec.SetField(accountingperiod.FieldName, field.TypeString, value)
	}
	if value, ok := apuo.mutation.Description(); ok {
		_spec.SetField(accountingperiod.FieldDescription, field.TypeString, value)
	}
	if apuo.mutation.DescriptionCleared() {
		_spec.ClearField(accountingperiod.FieldDescription, field.TypeString)
	}
	if value, ok := apuo.mutation.StartPlanningDate(); ok {
		_spec.SetField(accountingperiod.FieldStartPlanningDate, field.TypeTime, value)
	}
	if apuo.mutation.StartPlanningDateCleared() {
		_spec.ClearField(accountingperiod.FieldStartPlanningDate, field.TypeTime)
	}
	if value, ok := apuo.mutation.StartAchievementCollectionDate(); ok {
		_spec.SetField(accountingperiod.FieldStartAchievementCollectionDate, field.TypeTime, value)
	}
	if apuo.mutation.StartAchievementCollectionDateCleared() {
		_spec.ClearField(accountingperiod.FieldStartAchievementCollectionDate, field.TypeTime)
	}
	if value, ok := apuo.mutation.FinishDate(); ok {
		_spec.SetField(accountingperiod.FieldFinishDate, field.TypeTime, value)
	}
	if apuo.mutation.FinishDateCleared() {
		_spec.ClearField(accountingperiod.FieldFinishDate, field.TypeTime)
	}
	if value, ok := apuo.mutation.CancelDate(); ok {
		_spec.SetField(accountingperiod.FieldCancelDate, field.TypeTime, value)
	}
	if apuo.mutation.CancelDateCleared() {
		_spec.ClearField(accountingperiod.FieldCancelDate, field.TypeTime)
	}
	if value, ok := apuo.mutation.BecameNonExecutedDate(); ok {
		_spec.SetField(accountingperiod.FieldBecameNonExecutedDate, field.TypeTime, value)
	}
	if apuo.mutation.BecameNonExecutedDateCleared() {
		_spec.ClearField(accountingperiod.FieldBecameNonExecutedDate, field.TypeTime)
	}
	if value, ok := apuo.mutation.Status(); ok {
		_spec.SetField(accountingperiod.FieldStatus, field.TypeString, value)
	}
	if apuo.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accountingperiod.FilesTable,
			Columns: []string{accountingperiod.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := apuo.mutation.RemovedFilesIDs(); len(nodes) > 0 && !apuo.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accountingperiod.FilesTable,
			Columns: []string{accountingperiod.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := apuo.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   accountingperiod.FilesTable,
			Columns: []string{accountingperiod.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AccountingPeriod{config: apuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, apuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountingperiod.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	apuo.mutation.done = true
	return _node, nil
}
