// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/kozlov-ma/sesc-backend/db/entdb/ent/accountingperiod"
)

// AccountingPeriod is the model entity for the AccountingPeriod schema.
type AccountingPeriod struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// StartPlanningDate holds the value of the "start_planning_date" field.
	StartPlanningDate *time.Time `json:"start_planning_date,omitempty"`
	// StartAchievementCollectionDate holds the value of the "start_achievement_collection_date" field.
	StartAchievementCollectionDate *time.Time `json:"start_achievement_collection_date,omitempty"`
	// FinishDate holds the value of the "finish_date" field.
	FinishDate *time.Time `json:"finish_date,omitempty"`
	// CancelDate holds the value of the "cancel_date" field.
	CancelDate *time.Time `json:"cancel_date,omitempty"`
	// BecameNonExecutedDate holds the value of the "became_non_executed_date" field.
	BecameNonExecutedDate *time.Time `json:"became_non_executed_date,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccountingPeriodQuery when eager-loading is set.
	Edges        AccountingPeriodEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AccountingPeriodEdges holds the relations/edges for other nodes in the graph.
type AccountingPeriodEdges struct {
	// Files holds the value of the files edge.
	Files []*File `json:"files,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// FilesOrErr returns the Files value or an error if the edge
// was not loaded in eager-loading.
func (e AccountingPeriodEdges) FilesOrErr() ([]*File, error) {
	if e.loadedTypes[0] {
		return e.Files, nil
	}
	return nil, &NotLoadedError{edge: "files"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountingPeriod) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountingperiod.FieldID:
			values[i] = new(sql.NullInt64)
		case accountingperiod.FieldName, accountingperiod.FieldDescription, accountingperiod.FieldStatus:
			values[i] = new(sql.NullString)
		case accountingperiod.FieldStartPlanningDate, accountingperiod.FieldStartAchievementCollectionDate, accountingperiod.FieldFinishDate, accountingperiod.FieldCancelDate, accountingperiod.FieldBecameNonExecutedDate:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountingPeriod fields.
func (ap *AccountingPeriod) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountingperiod.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ap.ID = int(value.Int64)
		case accountingperiod.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				ap.Name = value.String
			}
		case accountingperiod.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				ap.Description = new(string)
				*ap.Description = value.String
			}
		case accountingperiod.FieldStartPlanningDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_planning_date", values[i])
			} else if value.Valid {
				ap.StartPlanningDate = new(time.Time)
				*ap.StartPlanningDate = value.Time
			}
		case accountingperiod.FieldStartAchievementCollectionDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_achievement_collection_date", values[i])
			} else if value.Valid {
				ap.StartAchievementCollectionDate = new(time.Time)
				*ap.StartAchievementCollectionDate = value.Time
			}
		case accountingperiod.FieldFinishDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finish_date", values[i])
			} else if value.Valid {
				ap.FinishDate = new(time.Time)
				*ap.FinishDate = value.Time
			}
		case accountingperiod.FieldCancelDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field cancel_date", values[i])
			} else if value.Valid {
				ap.CancelDate = new(time.Time)
				*ap.CancelDate = value.Time
			}
		case accountingperiod.FieldBecameNonExecutedDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field became_non_executed_date", values[i])
			} else if value.Valid {
				ap.BecameNonExecutedDate = new(time.Time)
				*ap.BecameNonExecutedDate = value.Time
			}
		case accountingperiod.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				ap.Status = value.String
			}
		default:
			ap.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountingPeriod.
// This includes values selected through modifiers, order, etc.
func (ap *AccountingPeriod) Value(name string) (ent.Value, error) {
	return ap.selectValues.Get(name)
}

// QueryFiles queries the "files" edge of the AccountingPeriod entity.
func (ap *AccountingPeriod) QueryFiles() *FileQuery {
	return NewAccountingPeriodClient(ap.config).QueryFiles(ap)
}

// Update returns a builder for updating this AccountingPeriod.
// Note that you need to call AccountingPeriod.Unwrap() before calling this method if this AccountingPeriod
// was returned from a transaction, and the transaction was committed or rolled back.
func (ap *AccountingPeriod) Update() *AccountingPeriodUpdateOne {
	return NewAccountingPeriodClient(ap.config).UpdateOne(ap)
}

// Unwrap unwraps the AccountingPeriod entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ap *AccountingPeriod) Unwrap() *AccountingPeriod {
	_tx, ok := ap.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountingPeriod is not a transactional entity")
	}
	ap.config.driver = _tx.drv
	return ap
}

// String implements the fmt.Stringer.
func (ap *AccountingPeriod) String() string {
	var builder strings.Builder
	builder.WriteString("AccountingPeriod(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ap.ID))
	builder.WriteString("name=")
	builder.WriteString(ap.Name)
	builder.WriteString(", ")
	if v := ap.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := ap.StartPlanningDate; v != nil {
		builder.WriteString("start_planning_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := ap.StartAchievementCollectionDate; v != nil {
		builder.WriteString("start_achievement_collection_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := ap.FinishDate; v != nil {
		builder.WriteString("finish_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := ap.CancelDate; v != nil {
		builder.WriteString("cancel_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := ap.BecameNonExecutedDate; v != nil {
		builder.WriteString("became_non_executed_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(ap.Status)
	builder.WriteByte(')')
	return builder.String()
}

// AccountingPeriods is a parsable slice of AccountingPeriod.
type AccountingPeriods []*AccountingPeriod
