// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kozlov-ma/sesc-backend/db/entdb/ent/accountingperiod"
	"github.com/kozlov-ma/sesc-backend/db/entdb/ent/predicate"
)

// AccountingPeriodDelete is the builder for deleting a AccountingPeriod entity.
type AccountingPeriodDelete struct {
	config
	hooks    []Hook
	mutation *AccountingPeriodMutation
}

// Where appends a list predicates to the AccountingPeriodDelete builder.
func (apd *AccountingPeriodDelete) Where(ps ...predicate.AccountingPeriod) *AccountingPeriodDelete {
	apd.mutation.Where(ps...)
	return apd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (apd *AccountingPeriodDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, apd.sqlExec, apd.mutation, apd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (apd *AccountingPeriodDelete) ExecX(ctx context.Context) int {
	n, err := apd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (apd *AccountingPeriodDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accountingperiod.Table, sqlgraph.NewFieldSpec(accountingperiod.FieldID, field.TypeInt))
	if ps := apd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, apd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	apd.mutation.done = true
	return affected, err
}

// AccountingPeriodDeleteOne is the builder for deleting a single AccountingPeriod entity.
type AccountingPeriodDeleteOne struct {
	apd *AccountingPeriodDelete
}

// Where appends a list predicates to the AccountingPeriodDelete builder.
func (apdo *AccountingPeriodDeleteOne) Where(ps ...predicate.AccountingPeriod) *AccountingPeriodDeleteOne {
	apdo.apd.mutation.Where(ps...)
	return apdo
}

// Exec executes the deletion query.
func (apdo *AccountingPeriodDeleteOne) Exec(ctx context.Context) error {
	n, err := apdo.apd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accountingperiod.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (apdo *AccountingPeriodDeleteOne) ExecX(ctx context.Context) {
	if err := apdo.Exec(ctx); err != nil {
		panic(err)
	}
}
