// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/kozlov-ma/sesc-backend/db/entdb/ent/achievementgroup"
	"github.com/kozlov-ma/sesc-backend/db/entdb/ent/achievementtemplate"
	"github.com/kozlov-ma/sesc-backend/db/entdb/ent/predicate"
)

// AchievementTemplateUpdate is the builder for updating AchievementTemplate entities.
type AchievementTemplateUpdate struct {
	config
	hooks    []Hook
	mutation *AchievementTemplateMutation
}

// Where appends a list predicates to the AchievementTemplateUpdate builder.
func (atu *AchievementTemplateUpdate) Where(ps ...predicate.AchievementTemplate) *AchievementTemplateUpdate {
	atu.mutation.Where(ps...)
	return atu
}

// SetName sets the "name" field.
func (atu *AchievementTemplateUpdate) SetName(s string) *AchievementTemplateUpdate {
	atu.mutation.SetName(s)
	return atu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (atu *AchievementTemplateUpdate) SetNillableName(s *string) *AchievementTemplateUpdate {
	if s != nil {
		atu.SetName(*s)
	}
	return atu
}

// SetDescription sets the "description" field.
func (atu *AchievementTemplateUpdate) SetDescription(s string) *AchievementTemplateUpdate {
	atu.mutation.SetDescription(s)
	return atu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (atu *AchievementTemplateUpdate) SetNillableDescription(s *string) *AchievementTemplateUpdate {
	if s != nil {
		atu.SetDescription(*s)
	}
	return atu
}

// ClearDescription clears the value of the "description" field.
func (atu *AchievementTemplateUpdate) ClearDescription() *AchievementTemplateUpdate {
	atu.mutation.ClearDescription()
	return atu
}

// SetPointsLimit sets the "points_limit" field.
func (atu *AchievementTemplateUpdate) SetPointsLimit(i int) *AchievementTemplateUpdate {
	atu.mutation.ResetPointsLimit()
	atu.mutation.SetPointsLimit(i)
	return atu
}

// SetNillablePointsLimit sets the "points_limit" field if the given value is not nil.
func (atu *AchievementTemplateUpdate) SetNillablePointsLimit(i *int) *AchievementTemplateUpdate {
	if i != nil {
		atu.SetPointsLimit(*i)
	}
	return atu
}

// AddPointsLimit adds i to the "points_limit" field.
func (atu *AchievementTemplateUpdate) AddPointsLimit(i int) *AchievementTemplateUpdate {
	atu.mutation.AddPointsLimit(i)
	return atu
}

// SetGroupID sets the "group_id" field.
func (atu *AchievementTemplateUpdate) SetGroupID(u uuid.UUID) *AchievementTemplateUpdate {
	atu.mutation.SetGroupID(u)
	return atu
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (atu *AchievementTemplateUpdate) SetNillableGroupID(u *uuid.UUID) *AchievementTemplateUpdate {
	if u != nil {
		atu.SetGroupID(*u)
	}
	return atu
}

// SetActive sets the "active" field.
func (atu *AchievementTemplateUpdate) SetActive(b bool) *AchievementTemplateUpdate {
	atu.mutation.SetActive(b)
	return atu
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (atu *AchievementTemplateUpdate) SetNillableActive(b *bool) *AchievementTemplateUpdate {
	if b != nil {
		atu.SetActive(*b)
	}
	return atu
}

// SetKind sets the "kind" field.
func (atu *AchievementTemplateUpdate) SetKind(a achievementtemplate.Kind) *AchievementTemplateUpdate {
	atu.mutation.SetKind(a)
	return atu
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (atu *AchievementTemplateUpdate) SetNillableKind(a *achievementtemplate.Kind) *AchievementTemplateUpdate {
	if a != nil {
		atu.SetKind(*a)
	}
	return atu
}

// SetGroup sets the "group" edge to the AchievementGroup entity.
func (atu *AchievementTemplateUpdate) SetGroup(a *AchievementGroup) *AchievementTemplateUpdate {
	return atu.SetGroupID(a.ID)
}

// Mutation returns the AchievementTemplateMutation object of the builder.
func (atu *AchievementTemplateUpdate) Mutation() *AchievementTemplateMutation {
	return atu.mutation
}

// ClearGroup clears the "group" edge to the AchievementGroup entity.
func (atu *AchievementTemplateUpdate) ClearGroup() *AchievementTemplateUpdate {
	atu.mutation.ClearGroup()
	return atu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (atu *AchievementTemplateUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, atu.sqlSave, atu.mutation, atu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (atu *AchievementTemplateUpdate) SaveX(ctx context.Context) int {
	affected, err := atu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (atu *AchievementTemplateUpdate) Exec(ctx context.Context) error {
	_, err := atu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (atu *AchievementTemplateUpdate) ExecX(ctx context.Context) {
	if err := atu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (atu *AchievementTemplateUpdate) check() error {
	if v, ok := atu.mutation.Name(); ok {
		if err := achievementtemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AchievementTemplate.name": %w`, err)}
		}
	}
	if v, ok := atu.mutation.PointsLimit(); ok {
		if err := achievementtemplate.PointsLimitValidator(v); err != nil {
			return &ValidationError{Name: "points_limit", err: fmt.Errorf(`ent: validator failed for field "AchievementTemplate.points_limit": %w`, err)}
		}
	}
	if v, ok := atu.mutation.Kind(); ok {
		if err := achievementtemplate.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "AchievementTemplate.kind": %w`, err)}
		}
	}
	if atu.mutation.GroupCleared() && len(atu.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AchievementTemplate.group"`)
	}
	return nil
}

func (atu *AchievementTemplateUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := atu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(achievementtemplate.Table, achievementtemplate.Columns, sqlgraph.NewFieldSpec(achievementtemplate.FieldID, field.TypeUUID))
	if ps := atu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := atu.mutation.Name(); ok {
		_spec.SetField(achievementtemplate.FieldName, field.TypeString, value)
	}
	if value, ok := atu.mutation.Description(); ok {
		_spec.SetField(achievementtemplate.FieldDescription, field.TypeString, value)
	}
	if atu.mutation.DescriptionCleared() {
		_spec.ClearField(achievementtemplate.FieldDescription, field.TypeString)
	}
	if value, ok := atu.mutation.PointsLimit(); ok {
		_spec.SetField(achievementtemplate.FieldPointsLimit, field.TypeInt, value)
	}
	if value, ok := atu.mutation.AddedPointsLimit(); ok {
		_spec.AddField(achievementtemplate.FieldPointsLimit, field.TypeInt, value)
	}
	if value, ok := atu.mutation.Active(); ok {
		_spec.SetField(achievementtemplate.FieldActive, field.TypeBool, value)
	}
	if value, ok := atu.mutation.Kind(); ok {
		_spec.SetField(achievementtemplate.FieldKind, field.TypeEnum, value)
	}
	if atu.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   achievementtemplate.GroupTable,
			Columns: []string{achievementtemplate.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(achievementgroup.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := atu.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   achievementtemplate.GroupTable,
			Columns: []string{achievementtemplate.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(achievementgroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, atu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{achievementtemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	atu.mutation.done = true
	return n, nil
}

// AchievementTemplateUpdateOne is the builder for updating a single AchievementTemplate entity.
type AchievementTemplateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AchievementTemplateMutation
}

// SetName sets the "name" field.
func (atuo *AchievementTemplateUpdateOne) SetName(s string) *AchievementTemplateUpdateOne {
	atuo.mutation.SetName(s)
	return atuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (atuo *AchievementTemplateUpdateOne) SetNillableName(s *string) *AchievementTemplateUpdateOne {
	if s != nil {
		atuo.SetName(*s)
	}
	return atuo
}

// SetDescription sets the "description" field.
func (atuo *AchievementTemplateUpdateOne) SetDescription(s string) *AchievementTemplateUpdateOne {
	atuo.mutation.SetDescription(s)
	return atuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (atuo *AchievementTemplateUpdateOne) SetNillableDescription(s *string) *AchievementTemplateUpdateOne {
	if s != nil {
		atuo.SetDescription(*s)
	}
	return atuo
}

// ClearDescription clears the value of the "description" field.
func (atuo *AchievementTemplateUpdateOne) ClearDescription() *AchievementTemplateUpdateOne {
	atuo.mutation.ClearDescription()
	return atuo
}

// SetPointsLimit sets the "points_limit" field.
func (atuo *AchievementTemplateUpdateOne) SetPointsLimit(i int) *AchievementTemplateUpdateOne {
	atuo.mutation.ResetPointsLimit()
	atuo.mutation.SetPointsLimit(i)
	return atuo
}

// SetNillablePointsLimit sets the "points_limit" field if the given value is not nil.
func (atuo *AchievementTemplateUpdateOne) SetNillablePointsLimit(i *int) *AchievementTemplateUpdateOne {
	if i != nil {
		atuo.SetPointsLimit(*i)
	}
	return atuo
}

// AddPointsLimit adds i to the "points_limit" field.
func (atuo *AchievementTemplateUpdateOne) AddPointsLimit(i int) *AchievementTemplateUpdateOne {
	atuo.mutation.AddPointsLimit(i)
	return atuo
}

// SetGroupID sets the "group_id" field.
func (atuo *AchievementTemplateUpdateOne) SetGroupID(u uuid.UUID) *AchievementTemplateUpdateOne {
	atuo.mutation.SetGroupID(u)
	return atuo
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (atuo *AchievementTemplateUpdateOne) SetNillableGroupID(u *uuid.UUID) *AchievementTemplateUpdateOne {
	if u != nil {
		atuo.SetGroupID(*u)
	}
	return atuo
}

// SetActive sets the "active" field.
func (atuo *AchievementTemplateUpdateOne) SetActive(b bool) *AchievementTemplateUpdateOne {
	atuo.mutation.SetActive(b)
	return atuo
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (atuo *AchievementTemplateUpdateOne) SetNillableActive(b *bool) *AchievementTemplateUpdateOne {
	if b != nil {
		atuo.SetActive(*b)
	}
	return atuo
}

// SetKind sets the "kind" field.
func (atuo *AchievementTemplateUpdateOne) SetKind(a achievementtemplate.Kind) *AchievementTemplateUpdateOne {
	atuo.mutation.SetKind(a)
	return atuo
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (atuo *AchievementTemplateUpdateOne) SetNillableKind(a *achievementtemplate.Kind) *AchievementTemplateUpdateOne {
	if a != nil {
		atuo.SetKind(*a)
	}
	return atuo
}

// SetGroup sets the "group" edge to the AchievementGroup entity.
func (atuo *AchievementTemplateUpdateOne) SetGroup(a *AchievementGroup) *AchievementTemplateUpdateOne {
	return atuo.SetGroupID(a.ID)
}

// Mutation returns the AchievementTemplateMutation object of the builder.
func (atuo *AchievementTemplateUpdateOne) Mutation() *AchievementTemplateMutation {
	return atuo.mutation
}

// ClearGroup clears the "group" edge to the AchievementGroup entity.
func (atuo *AchievementTemplateUpdateOne) ClearGroup() *AchievementTemplateUpdateOne {
	atuo.mutation.ClearGroup()
	return atuo
}

// Where appends a list predicates to the AchievementTemplateUpdate builder.
func (atuo *AchievementTemplateUpdateOne) Where(ps ...predicate.AchievementTemplate) *AchievementTemplateUpdateOne {
	atuo.mutation.Where(ps...)
	return atuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (atuo *AchievementTemplateUpdateOne) Select(field string, fields ...string) *AchievementTemplateUpdateOne {
	atuo.fields = append([]string{field}, fields...)
	return atuo
}

// Save executes the query and returns the updated AchievementTemplate entity.
func (atuo *AchievementTemplateUpdateOne) Save(ctx context.Context) (*AchievementTemplate, error) {
	return withHooks(ctx, atuo.sqlSave, atuo.mutation, atuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (atuo *AchievementTemplateUpdateOne) SaveX(ctx context.Context) *AchievementTemplate {
	node, err := atuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (atuo *AchievementTemplateUpdateOne) Exec(ctx context.Context) error {
	_, err := atuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (atuo *AchievementTemplateUpdateOne) ExecX(ctx context.Context) {
	if err := atuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (atuo *AchievementTemplateUpdateOne) check() error {
	if v, ok := atuo.mutation.Name(); ok {
		if err := achievementtemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AchievementTemplate.name": %w`, err)}
		}
	}
	if v, ok := atuo.mutation.PointsLimit(); ok {
		if err := achievementtemplate.PointsLimitValidator(v); err != nil {
			return &ValidationError{Name: "points_limit", err: fmt.Errorf(`ent: validator failed for field "AchievementTemplate.points_limit": %w`, err)}
		}
	}
	if v, ok := atuo.mutation.Kind(); ok {
		if err := achievementtemplate.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "AchievementTemplate.kind": %w`, err)}
		}
	}
	if atuo.mutation.GroupCleared() && len(atuo.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AchievementTemplate.group"`)
	}
	return nil
}

func (atuo *AchievementTemplateUpdateOne) sqlSave(ctx context.Context) (_node *AchievementTemplate, err error) {
	if err := atuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(achievementtemplate.Table, achievementtemplate.Columns, sqlgraph.NewFieldSpec(achievementtemplate.FieldID, field.TypeUUID))
	id, ok := atuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AchievementTemplate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := atuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, achievementtemplate.FieldID)
		for _, f := range fields {
			if !achievementtemplate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != achievementtemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := atuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := atuo.mutation.Name(); ok {
		_spec.SetField(achievementtemplate.FieldName, field.TypeString, value)
	}
	if value, ok := atuo.mutation.Description(); ok {
		_spec.SetField(achievementtemplate.FieldDescription, field.TypeString, value)
	}
	if atuo.mutation.DescriptionCleared() {
		_spec.ClearField(achievementtemplate.FieldDescription, field.TypeString)
	}
	if value, ok := atuo.mutation.PointsLimit(); ok {
		_spec.SetField(achievementtemplate.FieldPointsLimit, field.TypeInt, value)
	}
	if value, ok := atuo.mutation.AddedPointsLimit(); ok {
		_spec.AddField(achievementtemplate.FieldPointsLimit, field.TypeInt, value)
	}
	if value, ok := atuo.mutation.Active(); ok {
		_spec.SetField(achievementtemplate.FieldActive, field.TypeBool, value)
	}
	if value, ok := atuo.mutation.Kind(); ok {
		_spec.SetField(achievementtemplate.FieldKind, field.TypeEnum, value)
	}
	if atuo.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   achievementtemplate.GroupTable,
			Columns: []string{achievementtemplate.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(achievementgroup.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := atuo.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   achievementtemplate.GroupTable,
			Columns: []string{achievementtemplate.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(achievementgroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AchievementTemplate{config: atuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, atuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{achievementtemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	atuo.mutation.done = true
	return _node, nil
}
