// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/kozlov-ma/sesc-backend/db/entdb/ent/achievementgroup"
	"github.com/kozlov-ma/sesc-backend/db/entdb/ent/achievementtemplate"
)

// AchievementGroupCreate is the builder for creating a AchievementGroup entity.
type AchievementGroupCreate struct {
	config
	mutation *AchievementGroupMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (agc *AchievementGroupCreate) SetName(s string) *AchievementGroupCreate {
	agc.mutation.SetName(s)
	return agc
}

// SetDescription sets the "description" field.
func (agc *AchievementGroupCreate) SetDescription(s string) *AchievementGroupCreate {
	agc.mutation.SetDescription(s)
	return agc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (agc *AchievementGroupCreate) SetNillableDescription(s *string) *AchievementGroupCreate {
	if s != nil {
		agc.SetDescription(*s)
	}
	return agc
}

// SetActive sets the "active" field.
func (agc *AchievementGroupCreate) SetActive(b bool) *AchievementGroupCreate {
	agc.mutation.SetActive(b)
	return agc
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (agc *AchievementGroupCreate) SetNillableActive(b *bool) *AchievementGroupCreate {
	if b != nil {
		agc.SetActive(*b)
	}
	return agc
}

// SetID sets the "id" field.
func (agc *AchievementGroupCreate) SetID(u uuid.UUID) *AchievementGroupCreate {
	agc.mutation.SetID(u)
	return agc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (agc *AchievementGroupCreate) SetNillableID(u *uuid.UUID) *AchievementGroupCreate {
	if u != nil {
		agc.SetID(*u)
	}
	return agc
}

// AddTemplateIDs adds the "templates" edge to the AchievementTemplate entity by IDs.
func (agc *AchievementGroupCreate) AddTemplateIDs(ids ...uuid.UUID) *AchievementGroupCreate {
	agc.mutation.AddTemplateIDs(ids...)
	return agc
}

// AddTemplates adds the "templates" edges to the AchievementTemplate entity.
func (agc *AchievementGroupCreate) AddTemplates(a ...*AchievementTemplate) *AchievementGroupCreate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return agc.AddTemplateIDs(ids...)
}

// Mutation returns the AchievementGroupMutation object of the builder.
func (agc *AchievementGroupCreate) Mutation() *AchievementGroupMutation {
	return agc.mutation
}

// Save creates the AchievementGroup in the database.
func (agc *AchievementGroupCreate) Save(ctx context.Context) (*AchievementGroup, error) {
	agc.defaults()
	return withHooks(ctx, agc.sqlSave, agc.mutation, agc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (agc *AchievementGroupCreate) SaveX(ctx context.Context) *AchievementGroup {
	v, err := agc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (agc *AchievementGroupCreate) Exec(ctx context.Context) error {
	_, err := agc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (agc *AchievementGroupCreate) ExecX(ctx context.Context) {
	if err := agc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (agc *AchievementGroupCreate) defaults() {
	if _, ok := agc.mutation.Active(); !ok {
		v := achievementgroup.DefaultActive
		agc.mutation.SetActive(v)
	}
	if _, ok := agc.mutation.ID(); !ok {
		v := achievementgroup.DefaultID()
		agc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (agc *AchievementGroupCreate) check() error {
	if _, ok := agc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AchievementGroup.name"`)}
	}
	if v, ok := agc.mutation.Name(); ok {
		if err := achievementgroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AchievementGroup.name": %w`, err)}
		}
	}
	if _, ok := agc.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "AchievementGroup.active"`)}
	}
	return nil
}

func (agc *AchievementGroupCreate) sqlSave(ctx context.Context) (*AchievementGroup, error) {
	if err := agc.check(); err != nil {
		return nil, err
	}
	_node, _spec := agc.createSpec()
	if err := sqlgraph.CreateNode(ctx, agc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	agc.mutation.id = &_node.ID
	agc.mutation.done = true
	return _node, nil
}

func (agc *AchievementGroupCreate) createSpec() (*AchievementGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &AchievementGroup{config: agc.config}
		_spec = sqlgraph.NewCreateSpec(achievementgroup.Table, sqlgraph.NewFieldSpec(achievementgroup.FieldID, field.TypeUUID))
	)
	if id, ok := agc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := agc.mutation.Name(); ok {
		_spec.SetField(achievementgroup.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := agc.mutation.Description(); ok {
		_spec.SetField(achievementgroup.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := agc.mutation.Active(); ok {
		_spec.SetField(achievementgroup.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if nodes := agc.mutation.TemplatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   achievementgroup.TemplatesTable,
			Columns: []string{achievementgroup.TemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(achievementtemplate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AchievementGroupCreateBulk is the builder for creating many AchievementGroup entities in bulk.
type AchievementGroupCreateBulk struct {
	config
	err      error
	builders []*AchievementGroupCreate
}

// Save creates the AchievementGroup entities in the database.
func (agcb *AchievementGroupCreateBulk) Save(ctx context.Context) ([]*AchievementGroup, error) {
	if agcb.err != nil {
		return nil, agcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(agcb.builders))
	nodes := make([]*AchievementGroup, len(agcb.builders))
	mutators := make([]Mutator, len(agcb.builders))
	for i := range agcb.builders {
		func(i int, root context.Context) {
			builder := agcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AchievementGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, agcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, agcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, agcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (agcb *AchievementGroupCreateBulk) SaveX(ctx context.Context) []*AchievementGroup {
	v, err := agcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (agcb *AchievementGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := agcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (agcb *AchievementGroupCreateBulk) ExecX(ctx context.Context) {
	if err := agcb.Exec(ctx); err != nil {
		panic(err)
	}
}
