// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	uuid "github.com/gofrs/uuid/v5"
	"github.com/kozlov-ma/sesc-backend/db/entdb/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	entachievement "github.com/kozlov-ma/sesc-backend/db/entdb/ent/achievement"
	"github.com/kozlov-ma/sesc-backend/db/entdb/ent/achievementdocument"
	"github.com/kozlov-ma/sesc-backend/db/entdb/ent/achievementgroup"
	"github.com/kozlov-ma/sesc-backend/db/entdb/ent/achievementreview"
	"github.com/kozlov-ma/sesc-backend/db/entdb/ent/achievementtemplate"
	"github.com/kozlov-ma/sesc-backend/db/entdb/ent/authuser"
	"github.com/kozlov-ma/sesc-backend/db/entdb/ent/department"
	"github.com/kozlov-ma/sesc-backend/db/entdb/ent/file"
	"github.com/kozlov-ma/sesc-backend/db/entdb/ent/user"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Achievement is the client for interacting with the Achievement builders.
	Achievement *AchievementClient
	// AchievementDocument is the client for interacting with the AchievementDocument builders.
	AchievementDocument *AchievementDocumentClient
	// AchievementGroup is the client for interacting with the AchievementGroup builders.
	AchievementGroup *AchievementGroupClient
	// AchievementReview is the client for interacting with the AchievementReview builders.
	AchievementReview *AchievementReviewClient
	// AchievementTemplate is the client for interacting with the AchievementTemplate builders.
	AchievementTemplate *AchievementTemplateClient
	// AuthUser is the client for interacting with the AuthUser builders.
	AuthUser *AuthUserClient
	// Department is the client for interacting with the Department builders.
	Department *DepartmentClient
	// File is the client for interacting with the File builders.
	File *FileClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Achievement = NewAchievementClient(c.config)
	c.AchievementDocument = NewAchievementDocumentClient(c.config)
	c.AchievementGroup = NewAchievementGroupClient(c.config)
	c.AchievementReview = NewAchievementReviewClient(c.config)
	c.AchievementTemplate = NewAchievementTemplateClient(c.config)
	c.AuthUser = NewAuthUserClient(c.config)
	c.Department = NewDepartmentClient(c.config)
	c.File = NewFileClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                 ctx,
		config:              cfg,
		Achievement:         NewAchievementClient(cfg),
		AchievementDocument: NewAchievementDocumentClient(cfg),
		AchievementGroup:    NewAchievementGroupClient(cfg),
		AchievementReview:   NewAchievementReviewClient(cfg),
		AchievementTemplate: NewAchievementTemplateClient(cfg),
		AuthUser:            NewAuthUserClient(cfg),
		Department:          NewDepartmentClient(cfg),
		File:                NewFileClient(cfg),
		User:                NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                 ctx,
		config:              cfg,
		Achievement:         NewAchievementClient(cfg),
		AchievementDocument: NewAchievementDocumentClient(cfg),
		AchievementGroup:    NewAchievementGroupClient(cfg),
		AchievementReview:   NewAchievementReviewClient(cfg),
		AchievementTemplate: NewAchievementTemplateClient(cfg),
		AuthUser:            NewAuthUserClient(cfg),
		Department:          NewDepartmentClient(cfg),
		File:                NewFileClient(cfg),
		User:                NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Achievement.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Achievement, c.AchievementDocument, c.AchievementGroup, c.AchievementReview,
		c.AchievementTemplate, c.AuthUser, c.Department, c.File, c.User,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Achievement, c.AchievementDocument, c.AchievementGroup, c.AchievementReview,
		c.AchievementTemplate, c.AuthUser, c.Department, c.File, c.User,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AchievementMutation:
		return c.Achievement.mutate(ctx, m)
	case *AchievementDocumentMutation:
		return c.AchievementDocument.mutate(ctx, m)
	case *AchievementGroupMutation:
		return c.AchievementGroup.mutate(ctx, m)
	case *AchievementReviewMutation:
		return c.AchievementReview.mutate(ctx, m)
	case *AchievementTemplateMutation:
		return c.AchievementTemplate.mutate(ctx, m)
	case *AuthUserMutation:
		return c.AuthUser.mutate(ctx, m)
	case *DepartmentMutation:
		return c.Department.mutate(ctx, m)
	case *FileMutation:
		return c.File.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AchievementClient is a client for the Achievement schema.
type AchievementClient struct {
	config
}

// NewAchievementClient returns a client for the Achievement from the given config.
func NewAchievementClient(c config) *AchievementClient {
	return &AchievementClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `entachievement.Hooks(f(g(h())))`.
func (c *AchievementClient) Use(hooks ...Hook) {
	c.hooks.Achievement = append(c.hooks.Achievement, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `entachievement.Intercept(f(g(h())))`.
func (c *AchievementClient) Intercept(interceptors ...Interceptor) {
	c.inters.Achievement = append(c.inters.Achievement, interceptors...)
}

// Create returns a builder for creating a Achievement entity.
func (c *AchievementClient) Create() *AchievementCreate {
	mutation := newAchievementMutation(c.config, OpCreate)
	return &AchievementCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Achievement entities.
func (c *AchievementClient) CreateBulk(builders ...*AchievementCreate) *AchievementCreateBulk {
	return &AchievementCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AchievementClient) MapCreateBulk(slice any, setFunc func(*AchievementCreate, int)) *AchievementCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AchievementCreateBulk{err: fmt.Errorf("calling to AchievementClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AchievementCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AchievementCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Achievement.
func (c *AchievementClient) Update() *AchievementUpdate {
	mutation := newAchievementMutation(c.config, OpUpdate)
	return &AchievementUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AchievementClient) UpdateOne(a *Achievement) *AchievementUpdateOne {
	mutation := newAchievementMutation(c.config, OpUpdateOne, withAchievement(a))
	return &AchievementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AchievementClient) UpdateOneID(id uuid.UUID) *AchievementUpdateOne {
	mutation := newAchievementMutation(c.config, OpUpdateOne, withAchievementID(id))
	return &AchievementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Achievement.
func (c *AchievementClient) Delete() *AchievementDelete {
	mutation := newAchievementMutation(c.config, OpDelete)
	return &AchievementDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AchievementClient) DeleteOne(a *Achievement) *AchievementDeleteOne {
	return c.DeleteOneID(a.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AchievementClient) DeleteOneID(id uuid.UUID) *AchievementDeleteOne {
	builder := c.Delete().Where(entachievement.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AchievementDeleteOne{builder}
}

// Query returns a query builder for Achievement.
func (c *AchievementClient) Query() *AchievementQuery {
	return &AchievementQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAchievement},
		inters: c.Interceptors(),
	}
}

// Get returns a Achievement entity by its id.
func (c *AchievementClient) Get(ctx context.Context, id uuid.UUID) (*Achievement, error) {
	return c.Query().Where(entachievement.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AchievementClient) GetX(ctx context.Context, id uuid.UUID) *Achievement {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryDocuments queries the documents edge of a Achievement.
func (c *AchievementClient) QueryDocuments(a *Achievement) *AchievementDocumentQuery {
	query := (&AchievementDocumentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := a.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(entachievement.Table, entachievement.FieldID, id),
			sqlgraph.To(achievementdocument.Table, achievementdocument.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, entachievement.DocumentsTable, entachievement.DocumentsColumn),
		)
		fromV = sqlgraph.Neighbors(a.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryReviews queries the reviews edge of a Achievement.
func (c *AchievementClient) QueryReviews(a *Achievement) *AchievementReviewQuery {
	query := (&AchievementReviewClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := a.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(entachievement.Table, entachievement.FieldID, id),
			sqlgraph.To(achievementreview.Table, achievementreview.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, entachievement.ReviewsTable, entachievement.ReviewsColumn),
		)
		fromV = sqlgraph.Neighbors(a.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryOwner queries the owner edge of a Achievement.
func (c *AchievementClient) QueryOwner(a *Achievement) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := a.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(entachievement.Table, entachievement.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, entachievement.OwnerTable, entachievement.OwnerColumn),
		)
		fromV = sqlgraph.Neighbors(a.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTemplate queries the template edge of a Achievement.
func (c *AchievementClient) QueryTemplate(a *Achievement) *AchievementTemplateQuery {
	query := (&AchievementTemplateClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := a.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(entachievement.Table, entachievement.FieldID, id),
			sqlgraph.To(achievementtemplate.Table, achievementtemplate.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, entachievement.TemplateTable, entachievement.TemplateColumn),
		)
		fromV = sqlgraph.Neighbors(a.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AchievementClient) Hooks() []Hook {
	return c.hooks.Achievement
}

// Interceptors returns the client interceptors.
func (c *AchievementClient) Interceptors() []Interceptor {
	return c.inters.Achievement
}

func (c *AchievementClient) mutate(ctx context.Context, m *AchievementMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AchievementCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AchievementUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AchievementUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AchievementDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Achievement mutation op: %q", m.Op())
	}
}

// AchievementDocumentClient is a client for the AchievementDocument schema.
type AchievementDocumentClient struct {
	config
}

// NewAchievementDocumentClient returns a client for the AchievementDocument from the given config.
func NewAchievementDocumentClient(c config) *AchievementDocumentClient {
	return &AchievementDocumentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `achievementdocument.Hooks(f(g(h())))`.
func (c *AchievementDocumentClient) Use(hooks ...Hook) {
	c.hooks.AchievementDocument = append(c.hooks.AchievementDocument, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `achievementdocument.Intercept(f(g(h())))`.
func (c *AchievementDocumentClient) Intercept(interceptors ...Interceptor) {
	c.inters.AchievementDocument = append(c.inters.AchievementDocument, interceptors...)
}

// Create returns a builder for creating a AchievementDocument entity.
func (c *AchievementDocumentClient) Create() *AchievementDocumentCreate {
	mutation := newAchievementDocumentMutation(c.config, OpCreate)
	return &AchievementDocumentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AchievementDocument entities.
func (c *AchievementDocumentClient) CreateBulk(builders ...*AchievementDocumentCreate) *AchievementDocumentCreateBulk {
	return &AchievementDocumentCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AchievementDocumentClient) MapCreateBulk(slice any, setFunc func(*AchievementDocumentCreate, int)) *AchievementDocumentCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AchievementDocumentCreateBulk{err: fmt.Errorf("calling to AchievementDocumentClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AchievementDocumentCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AchievementDocumentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AchievementDocument.
func (c *AchievementDocumentClient) Update() *AchievementDocumentUpdate {
	mutation := newAchievementDocumentMutation(c.config, OpUpdate)
	return &AchievementDocumentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AchievementDocumentClient) UpdateOne(ad *AchievementDocument) *AchievementDocumentUpdateOne {
	mutation := newAchievementDocumentMutation(c.config, OpUpdateOne, withAchievementDocument(ad))
	return &AchievementDocumentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AchievementDocumentClient) UpdateOneID(id uuid.UUID) *AchievementDocumentUpdateOne {
	mutation := newAchievementDocumentMutation(c.config, OpUpdateOne, withAchievementDocumentID(id))
	return &AchievementDocumentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AchievementDocument.
func (c *AchievementDocumentClient) Delete() *AchievementDocumentDelete {
	mutation := newAchievementDocumentMutation(c.config, OpDelete)
	return &AchievementDocumentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AchievementDocumentClient) DeleteOne(ad *AchievementDocument) *AchievementDocumentDeleteOne {
	return c.DeleteOneID(ad.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AchievementDocumentClient) DeleteOneID(id uuid.UUID) *AchievementDocumentDeleteOne {
	builder := c.Delete().Where(achievementdocument.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AchievementDocumentDeleteOne{builder}
}

// Query returns a query builder for AchievementDocument.
func (c *AchievementDocumentClient) Query() *AchievementDocumentQuery {
	return &AchievementDocumentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAchievementDocument},
		inters: c.Interceptors(),
	}
}

// Get returns a AchievementDocument entity by its id.
func (c *AchievementDocumentClient) Get(ctx context.Context, id uuid.UUID) (*AchievementDocument, error) {
	return c.Query().Where(achievementdocument.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AchievementDocumentClient) GetX(ctx context.Context, id uuid.UUID) *AchievementDocument {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAchievement queries the achievement edge of a AchievementDocument.
func (c *AchievementDocumentClient) QueryAchievement(ad *AchievementDocument) *AchievementQuery {
	query := (&AchievementClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ad.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(achievementdocument.Table, achievementdocument.FieldID, id),
			sqlgraph.To(entachievement.Table, entachievement.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, achievementdocument.AchievementTable, achievementdocument.AchievementColumn),
		)
		fromV = sqlgraph.Neighbors(ad.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryFile queries the file edge of a AchievementDocument.
func (c *AchievementDocumentClient) QueryFile(ad *AchievementDocument) *FileQuery {
	query := (&FileClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ad.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(achievementdocument.Table, achievementdocument.FieldID, id),
			sqlgraph.To(file.Table, file.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, achievementdocument.FileTable, achievementdocument.FileColumn),
		)
		fromV = sqlgraph.Neighbors(ad.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AchievementDocumentClient) Hooks() []Hook {
	return c.hooks.AchievementDocument
}

// Interceptors returns the client interceptors.
func (c *AchievementDocumentClient) Interceptors() []Interceptor {
	return c.inters.AchievementDocument
}

func (c *AchievementDocumentClient) mutate(ctx context.Context, m *AchievementDocumentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AchievementDocumentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AchievementDocumentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AchievementDocumentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AchievementDocumentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AchievementDocument mutation op: %q", m.Op())
	}
}

// AchievementGroupClient is a client for the AchievementGroup schema.
type AchievementGroupClient struct {
	config
}

// NewAchievementGroupClient returns a client for the AchievementGroup from the given config.
func NewAchievementGroupClient(c config) *AchievementGroupClient {
	return &AchievementGroupClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `achievementgroup.Hooks(f(g(h())))`.
func (c *AchievementGroupClient) Use(hooks ...Hook) {
	c.hooks.AchievementGroup = append(c.hooks.AchievementGroup, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `achievementgroup.Intercept(f(g(h())))`.
func (c *AchievementGroupClient) Intercept(interceptors ...Interceptor) {
	c.inters.AchievementGroup = append(c.inters.AchievementGroup, interceptors...)
}

// Create returns a builder for creating a AchievementGroup entity.
func (c *AchievementGroupClient) Create() *AchievementGroupCreate {
	mutation := newAchievementGroupMutation(c.config, OpCreate)
	return &AchievementGroupCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AchievementGroup entities.
func (c *AchievementGroupClient) CreateBulk(builders ...*AchievementGroupCreate) *AchievementGroupCreateBulk {
	return &AchievementGroupCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AchievementGroupClient) MapCreateBulk(slice any, setFunc func(*AchievementGroupCreate, int)) *AchievementGroupCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AchievementGroupCreateBulk{err: fmt.Errorf("calling to AchievementGroupClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AchievementGroupCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AchievementGroupCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AchievementGroup.
func (c *AchievementGroupClient) Update() *AchievementGroupUpdate {
	mutation := newAchievementGroupMutation(c.config, OpUpdate)
	return &AchievementGroupUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AchievementGroupClient) UpdateOne(ag *AchievementGroup) *AchievementGroupUpdateOne {
	mutation := newAchievementGroupMutation(c.config, OpUpdateOne, withAchievementGroup(ag))
	return &AchievementGroupUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AchievementGroupClient) UpdateOneID(id uuid.UUID) *AchievementGroupUpdateOne {
	mutation := newAchievementGroupMutation(c.config, OpUpdateOne, withAchievementGroupID(id))
	return &AchievementGroupUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AchievementGroup.
func (c *AchievementGroupClient) Delete() *AchievementGroupDelete {
	mutation := newAchievementGroupMutation(c.config, OpDelete)
	return &AchievementGroupDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AchievementGroupClient) DeleteOne(ag *AchievementGroup) *AchievementGroupDeleteOne {
	return c.DeleteOneID(ag.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AchievementGroupClient) DeleteOneID(id uuid.UUID) *AchievementGroupDeleteOne {
	builder := c.Delete().Where(achievementgroup.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AchievementGroupDeleteOne{builder}
}

// Query returns a query builder for AchievementGroup.
func (c *AchievementGroupClient) Query() *AchievementGroupQuery {
	return &AchievementGroupQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAchievementGroup},
		inters: c.Interceptors(),
	}
}

// Get returns a AchievementGroup entity by its id.
func (c *AchievementGroupClient) Get(ctx context.Context, id uuid.UUID) (*AchievementGroup, error) {
	return c.Query().Where(achievementgroup.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AchievementGroupClient) GetX(ctx context.Context, id uuid.UUID) *AchievementGroup {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTemplates queries the templates edge of a AchievementGroup.
func (c *AchievementGroupClient) QueryTemplates(ag *AchievementGroup) *AchievementTemplateQuery {
	query := (&AchievementTemplateClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ag.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(achievementgroup.Table, achievementgroup.FieldID, id),
			sqlgraph.To(achievementtemplate.Table, achievementtemplate.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, achievementgroup.TemplatesTable, achievementgroup.TemplatesColumn),
		)
		fromV = sqlgraph.Neighbors(ag.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AchievementGroupClient) Hooks() []Hook {
	return c.hooks.AchievementGroup
}

// Interceptors returns the client interceptors.
func (c *AchievementGroupClient) Interceptors() []Interceptor {
	return c.inters.AchievementGroup
}

func (c *AchievementGroupClient) mutate(ctx context.Context, m *AchievementGroupMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AchievementGroupCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AchievementGroupUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AchievementGroupUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AchievementGroupDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AchievementGroup mutation op: %q", m.Op())
	}
}

// AchievementReviewClient is a client for the AchievementReview schema.
type AchievementReviewClient struct {
	config
}

// NewAchievementReviewClient returns a client for the AchievementReview from the given config.
func NewAchievementReviewClient(c config) *AchievementReviewClient {
	return &AchievementReviewClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `achievementreview.Hooks(f(g(h())))`.
func (c *AchievementReviewClient) Use(hooks ...Hook) {
	c.hooks.AchievementReview = append(c.hooks.AchievementReview, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `achievementreview.Intercept(f(g(h())))`.
func (c *AchievementReviewClient) Intercept(interceptors ...Interceptor) {
	c.inters.AchievementReview = append(c.inters.AchievementReview, interceptors...)
}

// Create returns a builder for creating a AchievementReview entity.
func (c *AchievementReviewClient) Create() *AchievementReviewCreate {
	mutation := newAchievementReviewMutation(c.config, OpCreate)
	return &AchievementReviewCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AchievementReview entities.
func (c *AchievementReviewClient) CreateBulk(builders ...*AchievementReviewCreate) *AchievementReviewCreateBulk {
	return &AchievementReviewCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AchievementReviewClient) MapCreateBulk(slice any, setFunc func(*AchievementReviewCreate, int)) *AchievementReviewCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AchievementReviewCreateBulk{err: fmt.Errorf("calling to AchievementReviewClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AchievementReviewCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AchievementReviewCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AchievementReview.
func (c *AchievementReviewClient) Update() *AchievementReviewUpdate {
	mutation := newAchievementReviewMutation(c.config, OpUpdate)
	return &AchievementReviewUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AchievementReviewClient) UpdateOne(ar *AchievementReview) *AchievementReviewUpdateOne {
	mutation := newAchievementReviewMutation(c.config, OpUpdateOne, withAchievementReview(ar))
	return &AchievementReviewUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AchievementReviewClient) UpdateOneID(id uuid.UUID) *AchievementReviewUpdateOne {
	mutation := newAchievementReviewMutation(c.config, OpUpdateOne, withAchievementReviewID(id))
	return &AchievementReviewUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AchievementReview.
func (c *AchievementReviewClient) Delete() *AchievementReviewDelete {
	mutation := newAchievementReviewMutation(c.config, OpDelete)
	return &AchievementReviewDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AchievementReviewClient) DeleteOne(ar *AchievementReview) *AchievementReviewDeleteOne {
	return c.DeleteOneID(ar.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AchievementReviewClient) DeleteOneID(id uuid.UUID) *AchievementReviewDeleteOne {
	builder := c.Delete().Where(achievementreview.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AchievementReviewDeleteOne{builder}
}

// Query returns a query builder for AchievementReview.
func (c *AchievementReviewClient) Query() *AchievementReviewQuery {
	return &AchievementReviewQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAchievementReview},
		inters: c.Interceptors(),
	}
}

// Get returns a AchievementReview entity by its id.
func (c *AchievementReviewClient) Get(ctx context.Context, id uuid.UUID) (*AchievementReview, error) {
	return c.Query().Where(achievementreview.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AchievementReviewClient) GetX(ctx context.Context, id uuid.UUID) *AchievementReview {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryAchievement queries the achievement edge of a AchievementReview.
func (c *AchievementReviewClient) QueryAchievement(ar *AchievementReview) *AchievementQuery {
	query := (&AchievementClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ar.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(achievementreview.Table, achievementreview.FieldID, id),
			sqlgraph.To(entachievement.Table, entachievement.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, achievementreview.AchievementTable, achievementreview.AchievementColumn),
		)
		fromV = sqlgraph.Neighbors(ar.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryReviewer queries the reviewer edge of a AchievementReview.
func (c *AchievementReviewClient) QueryReviewer(ar *AchievementReview) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := ar.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(achievementreview.Table, achievementreview.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, achievementreview.ReviewerTable, achievementreview.ReviewerColumn),
		)
		fromV = sqlgraph.Neighbors(ar.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AchievementReviewClient) Hooks() []Hook {
	return c.hooks.AchievementReview
}

// Interceptors returns the client interceptors.
func (c *AchievementReviewClient) Interceptors() []Interceptor {
	return c.inters.AchievementReview
}

func (c *AchievementReviewClient) mutate(ctx context.Context, m *AchievementReviewMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AchievementReviewCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AchievementReviewUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AchievementReviewUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AchievementReviewDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AchievementReview mutation op: %q", m.Op())
	}
}

// AchievementTemplateClient is a client for the AchievementTemplate schema.
type AchievementTemplateClient struct {
	config
}

// NewAchievementTemplateClient returns a client for the AchievementTemplate from the given config.
func NewAchievementTemplateClient(c config) *AchievementTemplateClient {
	return &AchievementTemplateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `achievementtemplate.Hooks(f(g(h())))`.
func (c *AchievementTemplateClient) Use(hooks ...Hook) {
	c.hooks.AchievementTemplate = append(c.hooks.AchievementTemplate, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `achievementtemplate.Intercept(f(g(h())))`.
func (c *AchievementTemplateClient) Intercept(interceptors ...Interceptor) {
	c.inters.AchievementTemplate = append(c.inters.AchievementTemplate, interceptors...)
}

// Create returns a builder for creating a AchievementTemplate entity.
func (c *AchievementTemplateClient) Create() *AchievementTemplateCreate {
	mutation := newAchievementTemplateMutation(c.config, OpCreate)
	return &AchievementTemplateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AchievementTemplate entities.
func (c *AchievementTemplateClient) CreateBulk(builders ...*AchievementTemplateCreate) *AchievementTemplateCreateBulk {
	return &AchievementTemplateCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AchievementTemplateClient) MapCreateBulk(slice any, setFunc func(*AchievementTemplateCreate, int)) *AchievementTemplateCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AchievementTemplateCreateBulk{err: fmt.Errorf("calling to AchievementTemplateClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AchievementTemplateCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AchievementTemplateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AchievementTemplate.
func (c *AchievementTemplateClient) Update() *AchievementTemplateUpdate {
	mutation := newAchievementTemplateMutation(c.config, OpUpdate)
	return &AchievementTemplateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AchievementTemplateClient) UpdateOne(at *AchievementTemplate) *AchievementTemplateUpdateOne {
	mutation := newAchievementTemplateMutation(c.config, OpUpdateOne, withAchievementTemplate(at))
	return &AchievementTemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AchievementTemplateClient) UpdateOneID(id uuid.UUID) *AchievementTemplateUpdateOne {
	mutation := newAchievementTemplateMutation(c.config, OpUpdateOne, withAchievementTemplateID(id))
	return &AchievementTemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AchievementTemplate.
func (c *AchievementTemplateClient) Delete() *AchievementTemplateDelete {
	mutation := newAchievementTemplateMutation(c.config, OpDelete)
	return &AchievementTemplateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AchievementTemplateClient) DeleteOne(at *AchievementTemplate) *AchievementTemplateDeleteOne {
	return c.DeleteOneID(at.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AchievementTemplateClient) DeleteOneID(id uuid.UUID) *AchievementTemplateDeleteOne {
	builder := c.Delete().Where(achievementtemplate.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AchievementTemplateDeleteOne{builder}
}

// Query returns a query builder for AchievementTemplate.
func (c *AchievementTemplateClient) Query() *AchievementTemplateQuery {
	return &AchievementTemplateQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAchievementTemplate},
		inters: c.Interceptors(),
	}
}

// Get returns a AchievementTemplate entity by its id.
func (c *AchievementTemplateClient) Get(ctx context.Context, id uuid.UUID) (*AchievementTemplate, error) {
	return c.Query().Where(achievementtemplate.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AchievementTemplateClient) GetX(ctx context.Context, id uuid.UUID) *AchievementTemplate {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryGroup queries the group edge of a AchievementTemplate.
func (c *AchievementTemplateClient) QueryGroup(at *AchievementTemplate) *AchievementGroupQuery {
	query := (&AchievementGroupClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := at.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(achievementtemplate.Table, achievementtemplate.FieldID, id),
			sqlgraph.To(achievementgroup.Table, achievementgroup.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, achievementtemplate.GroupTable, achievementtemplate.GroupColumn),
		)
		fromV = sqlgraph.Neighbors(at.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAchievements queries the achievements edge of a AchievementTemplate.
func (c *AchievementTemplateClient) QueryAchievements(at *AchievementTemplate) *AchievementQuery {
	query := (&AchievementClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := at.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(achievementtemplate.Table, achievementtemplate.FieldID, id),
			sqlgraph.To(entachievement.Table, entachievement.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, achievementtemplate.AchievementsTable, achievementtemplate.AchievementsColumn),
		)
		fromV = sqlgraph.Neighbors(at.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AchievementTemplateClient) Hooks() []Hook {
	return c.hooks.AchievementTemplate
}

// Interceptors returns the client interceptors.
func (c *AchievementTemplateClient) Interceptors() []Interceptor {
	return c.inters.AchievementTemplate
}

func (c *AchievementTemplateClient) mutate(ctx context.Context, m *AchievementTemplateMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AchievementTemplateCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AchievementTemplateUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AchievementTemplateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AchievementTemplateDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AchievementTemplate mutation op: %q", m.Op())
	}
}

// AuthUserClient is a client for the AuthUser schema.
type AuthUserClient struct {
	config
}

// NewAuthUserClient returns a client for the AuthUser from the given config.
func NewAuthUserClient(c config) *AuthUserClient {
	return &AuthUserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `authuser.Hooks(f(g(h())))`.
func (c *AuthUserClient) Use(hooks ...Hook) {
	c.hooks.AuthUser = append(c.hooks.AuthUser, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `authuser.Intercept(f(g(h())))`.
func (c *AuthUserClient) Intercept(interceptors ...Interceptor) {
	c.inters.AuthUser = append(c.inters.AuthUser, interceptors...)
}

// Create returns a builder for creating a AuthUser entity.
func (c *AuthUserClient) Create() *AuthUserCreate {
	mutation := newAuthUserMutation(c.config, OpCreate)
	return &AuthUserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AuthUser entities.
func (c *AuthUserClient) CreateBulk(builders ...*AuthUserCreate) *AuthUserCreateBulk {
	return &AuthUserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AuthUserClient) MapCreateBulk(slice any, setFunc func(*AuthUserCreate, int)) *AuthUserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AuthUserCreateBulk{err: fmt.Errorf("calling to AuthUserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AuthUserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AuthUserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AuthUser.
func (c *AuthUserClient) Update() *AuthUserUpdate {
	mutation := newAuthUserMutation(c.config, OpUpdate)
	return &AuthUserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AuthUserClient) UpdateOne(au *AuthUser) *AuthUserUpdateOne {
	mutation := newAuthUserMutation(c.config, OpUpdateOne, withAuthUser(au))
	return &AuthUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AuthUserClient) UpdateOneID(id int) *AuthUserUpdateOne {
	mutation := newAuthUserMutation(c.config, OpUpdateOne, withAuthUserID(id))
	return &AuthUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AuthUser.
func (c *AuthUserClient) Delete() *AuthUserDelete {
	mutation := newAuthUserMutation(c.config, OpDelete)
	return &AuthUserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AuthUserClient) DeleteOne(au *AuthUser) *AuthUserDeleteOne {
	return c.DeleteOneID(au.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AuthUserClient) DeleteOneID(id int) *AuthUserDeleteOne {
	builder := c.Delete().Where(authuser.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AuthUserDeleteOne{builder}
}

// Query returns a query builder for AuthUser.
func (c *AuthUserClient) Query() *AuthUserQuery {
	return &AuthUserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAuthUser},
		inters: c.Interceptors(),
	}
}

// Get returns a AuthUser entity by its id.
func (c *AuthUserClient) Get(ctx context.Context, id int) (*AuthUser, error) {
	return c.Query().Where(authuser.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AuthUserClient) GetX(ctx context.Context, id int) *AuthUser {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a AuthUser.
func (c *AuthUserClient) QueryUser(au *AuthUser) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := au.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(authuser.Table, authuser.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, authuser.UserTable, authuser.UserColumn),
		)
		fromV = sqlgraph.Neighbors(au.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AuthUserClient) Hooks() []Hook {
	return c.hooks.AuthUser
}

// Interceptors returns the client interceptors.
func (c *AuthUserClient) Interceptors() []Interceptor {
	return c.inters.AuthUser
}

func (c *AuthUserClient) mutate(ctx context.Context, m *AuthUserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AuthUserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AuthUserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AuthUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AuthUserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AuthUser mutation op: %q", m.Op())
	}
}

// DepartmentClient is a client for the Department schema.
type DepartmentClient struct {
	config
}

// NewDepartmentClient returns a client for the Department from the given config.
func NewDepartmentClient(c config) *DepartmentClient {
	return &DepartmentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `department.Hooks(f(g(h())))`.
func (c *DepartmentClient) Use(hooks ...Hook) {
	c.hooks.Department = append(c.hooks.Department, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `department.Intercept(f(g(h())))`.
func (c *DepartmentClient) Intercept(interceptors ...Interceptor) {
	c.inters.Department = append(c.inters.Department, interceptors...)
}

// Create returns a builder for creating a Department entity.
func (c *DepartmentClient) Create() *DepartmentCreate {
	mutation := newDepartmentMutation(c.config, OpCreate)
	return &DepartmentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Department entities.
func (c *DepartmentClient) CreateBulk(builders ...*DepartmentCreate) *DepartmentCreateBulk {
	return &DepartmentCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DepartmentClient) MapCreateBulk(slice any, setFunc func(*DepartmentCreate, int)) *DepartmentCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DepartmentCreateBulk{err: fmt.Errorf("calling to DepartmentClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DepartmentCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DepartmentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Department.
func (c *DepartmentClient) Update() *DepartmentUpdate {
	mutation := newDepartmentMutation(c.config, OpUpdate)
	return &DepartmentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DepartmentClient) UpdateOne(d *Department) *DepartmentUpdateOne {
	mutation := newDepartmentMutation(c.config, OpUpdateOne, withDepartment(d))
	return &DepartmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DepartmentClient) UpdateOneID(id uuid.UUID) *DepartmentUpdateOne {
	mutation := newDepartmentMutation(c.config, OpUpdateOne, withDepartmentID(id))
	return &DepartmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Department.
func (c *DepartmentClient) Delete() *DepartmentDelete {
	mutation := newDepartmentMutation(c.config, OpDelete)
	return &DepartmentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DepartmentClient) DeleteOne(d *Department) *DepartmentDeleteOne {
	return c.DeleteOneID(d.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DepartmentClient) DeleteOneID(id uuid.UUID) *DepartmentDeleteOne {
	builder := c.Delete().Where(department.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DepartmentDeleteOne{builder}
}

// Query returns a query builder for Department.
func (c *DepartmentClient) Query() *DepartmentQuery {
	return &DepartmentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDepartment},
		inters: c.Interceptors(),
	}
}

// Get returns a Department entity by its id.
func (c *DepartmentClient) Get(ctx context.Context, id uuid.UUID) (*Department, error) {
	return c.Query().Where(department.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DepartmentClient) GetX(ctx context.Context, id uuid.UUID) *Department {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUsers queries the users edge of a Department.
func (c *DepartmentClient) QueryUsers(d *Department) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := d.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(department.Table, department.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, department.UsersTable, department.UsersColumn),
		)
		fromV = sqlgraph.Neighbors(d.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DepartmentClient) Hooks() []Hook {
	return c.hooks.Department
}

// Interceptors returns the client interceptors.
func (c *DepartmentClient) Interceptors() []Interceptor {
	return c.inters.Department
}

func (c *DepartmentClient) mutate(ctx context.Context, m *DepartmentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DepartmentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DepartmentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DepartmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DepartmentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Department mutation op: %q", m.Op())
	}
}

// FileClient is a client for the File schema.
type FileClient struct {
	config
}

// NewFileClient returns a client for the File from the given config.
func NewFileClient(c config) *FileClient {
	return &FileClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `file.Hooks(f(g(h())))`.
func (c *FileClient) Use(hooks ...Hook) {
	c.hooks.File = append(c.hooks.File, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `file.Intercept(f(g(h())))`.
func (c *FileClient) Intercept(interceptors ...Interceptor) {
	c.inters.File = append(c.inters.File, interceptors...)
}

// Create returns a builder for creating a File entity.
func (c *FileClient) Create() *FileCreate {
	mutation := newFileMutation(c.config, OpCreate)
	return &FileCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of File entities.
func (c *FileClient) CreateBulk(builders ...*FileCreate) *FileCreateBulk {
	return &FileCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FileClient) MapCreateBulk(slice any, setFunc func(*FileCreate, int)) *FileCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FileCreateBulk{err: fmt.Errorf("calling to FileClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FileCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FileCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for File.
func (c *FileClient) Update() *FileUpdate {
	mutation := newFileMutation(c.config, OpUpdate)
	return &FileUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FileClient) UpdateOne(f *File) *FileUpdateOne {
	mutation := newFileMutation(c.config, OpUpdateOne, withFile(f))
	return &FileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FileClient) UpdateOneID(id uuid.UUID) *FileUpdateOne {
	mutation := newFileMutation(c.config, OpUpdateOne, withFileID(id))
	return &FileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for File.
func (c *FileClient) Delete() *FileDelete {
	mutation := newFileMutation(c.config, OpDelete)
	return &FileDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FileClient) DeleteOne(f *File) *FileDeleteOne {
	return c.DeleteOneID(f.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FileClient) DeleteOneID(id uuid.UUID) *FileDeleteOne {
	builder := c.Delete().Where(file.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FileDeleteOne{builder}
}

// Query returns a query builder for File.
func (c *FileClient) Query() *FileQuery {
	return &FileQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFile},
		inters: c.Interceptors(),
	}
}

// Get returns a File entity by its id.
func (c *FileClient) Get(ctx context.Context, id uuid.UUID) (*File, error) {
	return c.Query().Where(file.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FileClient) GetX(ctx context.Context, id uuid.UUID) *File {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryOwner queries the owner edge of a File.
func (c *FileClient) QueryOwner(f *File) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := f.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(file.Table, file.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, file.OwnerTable, file.OwnerColumn),
		)
		fromV = sqlgraph.Neighbors(f.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAchievementDocuments queries the achievement_documents edge of a File.
func (c *FileClient) QueryAchievementDocuments(f *File) *AchievementDocumentQuery {
	query := (&AchievementDocumentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := f.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(file.Table, file.FieldID, id),
			sqlgraph.To(achievementdocument.Table, achievementdocument.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, file.AchievementDocumentsTable, file.AchievementDocumentsColumn),
		)
		fromV = sqlgraph.Neighbors(f.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *FileClient) Hooks() []Hook {
	return c.hooks.File
}

// Interceptors returns the client interceptors.
func (c *FileClient) Interceptors() []Interceptor {
	return c.inters.File
}

func (c *FileClient) mutate(ctx context.Context, m *FileMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FileCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FileUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FileDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown File mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(u *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(u))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id uuid.UUID) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(u *User) *UserDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id uuid.UUID) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id uuid.UUID) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id uuid.UUID) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryDepartment queries the department edge of a User.
func (c *UserClient) QueryDepartment(u *User) *DepartmentQuery {
	query := (&DepartmentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(department.Table, department.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, user.DepartmentTable, user.DepartmentColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAuth queries the auth edge of a User.
func (c *UserClient) QueryAuth(u *User) *AuthUserQuery {
	query := (&AuthUserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(authuser.Table, authuser.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, user.AuthTable, user.AuthColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryFiles queries the files edge of a User.
func (c *UserClient) QueryFiles(u *User) *FileQuery {
	query := (&FileClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(file.Table, file.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.FilesTable, user.FilesColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryAchievements queries the achievements edge of a User.
func (c *UserClient) QueryAchievements(u *User) *AchievementQuery {
	query := (&AchievementClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(entachievement.Table, entachievement.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.AchievementsTable, user.AchievementsColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryReviews queries the reviews edge of a User.
func (c *UserClient) QueryReviews(u *User) *AchievementReviewQuery {
	query := (&AchievementReviewClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(achievementreview.Table, achievementreview.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.ReviewsTable, user.ReviewsColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Achievement, AchievementDocument, AchievementGroup, AchievementReview,
		AchievementTemplate, AuthUser, Department, File, User []ent.Hook
	}
	inters struct {
		Achievement, AchievementDocument, AchievementGroup, AchievementReview,
		AchievementTemplate, AuthUser, Department, File, User []ent.Interceptor
	}
)
