// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/kozlov-ma/sesc-backend/db/entdb/ent/file"
	"github.com/kozlov-ma/sesc-backend/db/entdb/ent/user"
)

// File is the model entity for the File schema.
type File struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// OwnerID holds the value of the "owner_id" field.
	OwnerID *uuid.UUID `json:"owner_id,omitempty"`
	// S3ObjectKey holds the value of the "s3_object_key" field.
	S3ObjectKey *string `json:"s3_object_key,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Size holds the value of the "size" field.
	Size int `json:"size,omitempty"`
	// FileDeleted holds the value of the "file_deleted" field.
	FileDeleted bool `json:"file_deleted,omitempty"`
	// DeletionScheduled holds the value of the "deletion_scheduled" field.
	DeletionScheduled bool `json:"deletion_scheduled,omitempty"`
	// ScheduledDeletionAt holds the value of the "scheduled_deletion_at" field.
	ScheduledDeletionAt *time.Time `json:"scheduled_deletion_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FileQuery when eager-loading is set.
	Edges        FileEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FileEdges holds the relations/edges for other nodes in the graph.
type FileEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// AchievementDocuments holds the value of the achievement_documents edge.
	AchievementDocuments []*AchievementDocument `json:"achievement_documents,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FileEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// AchievementDocumentsOrErr returns the AchievementDocuments value or an error if the edge
// was not loaded in eager-loading.
func (e FileEdges) AchievementDocumentsOrErr() ([]*AchievementDocument, error) {
	if e.loadedTypes[1] {
		return e.AchievementDocuments, nil
	}
	return nil, &NotLoadedError{edge: "achievement_documents"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*File) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case file.FieldOwnerID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case file.FieldFileDeleted, file.FieldDeletionScheduled:
			values[i] = new(sql.NullBool)
		case file.FieldSize:
			values[i] = new(sql.NullInt64)
		case file.FieldS3ObjectKey, file.FieldName:
			values[i] = new(sql.NullString)
		case file.FieldScheduledDeletionAt:
			values[i] = new(sql.NullTime)
		case file.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the File fields.
func (f *File) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case file.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				f.ID = *value
			}
		case file.FieldOwnerID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field owner_id", values[i])
			} else if value.Valid {
				f.OwnerID = new(uuid.UUID)
				*f.OwnerID = *value.S.(*uuid.UUID)
			}
		case file.FieldS3ObjectKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field s3_object_key", values[i])
			} else if value.Valid {
				f.S3ObjectKey = new(string)
				*f.S3ObjectKey = value.String
			}
		case file.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				f.Name = value.String
			}
		case file.FieldSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				f.Size = int(value.Int64)
			}
		case file.FieldFileDeleted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field file_deleted", values[i])
			} else if value.Valid {
				f.FileDeleted = value.Bool
			}
		case file.FieldDeletionScheduled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field deletion_scheduled", values[i])
			} else if value.Valid {
				f.DeletionScheduled = value.Bool
			}
		case file.FieldScheduledDeletionAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field scheduled_deletion_at", values[i])
			} else if value.Valid {
				f.ScheduledDeletionAt = new(time.Time)
				*f.ScheduledDeletionAt = value.Time
			}
		default:
			f.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the File.
// This includes values selected through modifiers, order, etc.
func (f *File) Value(name string) (ent.Value, error) {
	return f.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the File entity.
func (f *File) QueryOwner() *UserQuery {
	return NewFileClient(f.config).QueryOwner(f)
}

// QueryAchievementDocuments queries the "achievement_documents" edge of the File entity.
func (f *File) QueryAchievementDocuments() *AchievementDocumentQuery {
	return NewFileClient(f.config).QueryAchievementDocuments(f)
}

// Update returns a builder for updating this File.
// Note that you need to call File.Unwrap() before calling this method if this File
// was returned from a transaction, and the transaction was committed or rolled back.
func (f *File) Update() *FileUpdateOne {
	return NewFileClient(f.config).UpdateOne(f)
}

// Unwrap unwraps the File entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (f *File) Unwrap() *File {
	_tx, ok := f.config.driver.(*txDriver)
	if !ok {
		panic("ent: File is not a transactional entity")
	}
	f.config.driver = _tx.drv
	return f
}

// String implements the fmt.Stringer.
func (f *File) String() string {
	var builder strings.Builder
	builder.WriteString("File(")
	builder.WriteString(fmt.Sprintf("id=%v, ", f.ID))
	if v := f.OwnerID; v != nil {
		builder.WriteString("owner_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := f.S3ObjectKey; v != nil {
		builder.WriteString("s3_object_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(f.Name)
	builder.WriteString(", ")
	builder.WriteString("size=")
	builder.WriteString(fmt.Sprintf("%v", f.Size))
	builder.WriteString(", ")
	builder.WriteString("file_deleted=")
	builder.WriteString(fmt.Sprintf("%v", f.FileDeleted))
	builder.WriteString(", ")
	builder.WriteString("deletion_scheduled=")
	builder.WriteString(fmt.Sprintf("%v", f.DeletionScheduled))
	builder.WriteString(", ")
	if v := f.ScheduledDeletionAt; v != nil {
		builder.WriteString("scheduled_deletion_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Files is a parsable slice of File.
type Files []*File
