# Frontend deployment configuration
service: sesc-frontend

# Name of the container image.
image: kozlov-ma/sesc-backend/frontend

# Deploy to these servers.
servers:
  web:
    - 158.160.165.141

# Enable SSL auto certification via Let's Encrypt
proxy:
  ssl: true
  host: sesc-fiit.ru
  app_port: 3000

# Registry configuration for GitHub Container Registry
registry:
  server: ghcr.io
  username: kozlov-ma
  password: 
  - GITHUB_TOKEN

# Configure builder setup.
builder:
  arch: amd64
  context: ./web
  dockerfile: ./web/Dockerfile
  args:
    NEXT_PUBLIC_API_URL: https://api.sesc-fiit.ru

# Use a different ssh user than root
ssh:
  user: kanyewest
  keys: [ "~/.ssh/id_sesc" ]

