// Code generated by go-swagger; DO NOT EDIT.

package achievement_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kozlov-ma/sesc-backend/apiclient/models"
)

// GetAchievementTemplatesReader is a Reader for the GetAchievementTemplates structure.
type GetAchievementTemplatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAchievementTemplatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAchievementTemplatesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetAchievementTemplatesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAchievementTemplatesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /achievement-templates] GetAchievementTemplates", response, response.Code())
	}
}

// NewGetAchievementTemplatesOK creates a GetAchievementTemplatesOK with default headers values
func NewGetAchievementTemplatesOK() *GetAchievementTemplatesOK {
	return &GetAchievementTemplatesOK{}
}

/*
GetAchievementTemplatesOK describes a response with status code 200, with default header values.

OK
*/
type GetAchievementTemplatesOK struct {
	Payload []*models.APIAchievementTemplateResponse
}

// IsSuccess returns true when this get achievement templates o k response has a 2xx status code
func (o *GetAchievementTemplatesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get achievement templates o k response has a 3xx status code
func (o *GetAchievementTemplatesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get achievement templates o k response has a 4xx status code
func (o *GetAchievementTemplatesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get achievement templates o k response has a 5xx status code
func (o *GetAchievementTemplatesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get achievement templates o k response a status code equal to that given
func (o *GetAchievementTemplatesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get achievement templates o k response
func (o *GetAchievementTemplatesOK) Code() int {
	return 200
}

func (o *GetAchievementTemplatesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /achievement-templates][%d] getAchievementTemplatesOK %s", 200, payload)
}

func (o *GetAchievementTemplatesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /achievement-templates][%d] getAchievementTemplatesOK %s", 200, payload)
}

func (o *GetAchievementTemplatesOK) GetPayload() []*models.APIAchievementTemplateResponse {
	return o.Payload
}

func (o *GetAchievementTemplatesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAchievementTemplatesUnauthorized creates a GetAchievementTemplatesUnauthorized with default headers values
func NewGetAchievementTemplatesUnauthorized() *GetAchievementTemplatesUnauthorized {
	return &GetAchievementTemplatesUnauthorized{}
}

/*
GetAchievementTemplatesUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAchievementTemplatesUnauthorized struct {
	Payload *models.RespondError
}

// IsSuccess returns true when this get achievement templates unauthorized response has a 2xx status code
func (o *GetAchievementTemplatesUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get achievement templates unauthorized response has a 3xx status code
func (o *GetAchievementTemplatesUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get achievement templates unauthorized response has a 4xx status code
func (o *GetAchievementTemplatesUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get achievement templates unauthorized response has a 5xx status code
func (o *GetAchievementTemplatesUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get achievement templates unauthorized response a status code equal to that given
func (o *GetAchievementTemplatesUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get achievement templates unauthorized response
func (o *GetAchievementTemplatesUnauthorized) Code() int {
	return 401
}

func (o *GetAchievementTemplatesUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /achievement-templates][%d] getAchievementTemplatesUnauthorized %s", 401, payload)
}

func (o *GetAchievementTemplatesUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /achievement-templates][%d] getAchievementTemplatesUnauthorized %s", 401, payload)
}

func (o *GetAchievementTemplatesUnauthorized) GetPayload() *models.RespondError {
	return o.Payload
}

func (o *GetAchievementTemplatesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RespondError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAchievementTemplatesInternalServerError creates a GetAchievementTemplatesInternalServerError with default headers values
func NewGetAchievementTemplatesInternalServerError() *GetAchievementTemplatesInternalServerError {
	return &GetAchievementTemplatesInternalServerError{}
}

/*
GetAchievementTemplatesInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetAchievementTemplatesInternalServerError struct {
	Payload *models.RespondError
}

// IsSuccess returns true when this get achievement templates internal server error response has a 2xx status code
func (o *GetAchievementTemplatesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get achievement templates internal server error response has a 3xx status code
func (o *GetAchievementTemplatesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get achievement templates internal server error response has a 4xx status code
func (o *GetAchievementTemplatesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get achievement templates internal server error response has a 5xx status code
func (o *GetAchievementTemplatesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get achievement templates internal server error response a status code equal to that given
func (o *GetAchievementTemplatesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get achievement templates internal server error response
func (o *GetAchievementTemplatesInternalServerError) Code() int {
	return 500
}

func (o *GetAchievementTemplatesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /achievement-templates][%d] getAchievementTemplatesInternalServerError %s", 500, payload)
}

func (o *GetAchievementTemplatesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /achievement-templates][%d] getAchievementTemplatesInternalServerError %s", 500, payload)
}

func (o *GetAchievementTemplatesInternalServerError) GetPayload() *models.RespondError {
	return o.Payload
}

func (o *GetAchievementTemplatesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RespondError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
