// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIGroupNotFoundError api group not found error
//
// swagger:model api.GroupNotFoundError
type APIGroupNotFoundError struct {

	// code
	// Example: GROUP_NOT_FOUND
	Code string `json:"code,omitempty"`

	// details
	Details string `json:"details,omitempty"`

	// message
	// Example: Achievement group not found
	Message string `json:"message,omitempty"`

	// ru message
	// Example: Группа достижений не найдена
	RuMessage string `json:"ruMessage,omitempty"`
}

// Validate validates this api group not found error
func (m *APIGroupNotFoundError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api group not found error based on context it is used
func (m *APIGroupNotFoundError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIGroupNotFoundError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIGroupNotFoundError) UnmarshalBinary(b []byte) error {
	var res APIGroupNotFoundError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
