// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// APIPatchAchievementTemplateRequest api patch achievement template request
//
// swagger:model api.PatchAchievementTemplateRequest
type APIPatchAchievementTemplateRequest struct {

	// active
	// Example: true
	Active bool `json:"active,omitempty"`

	// description
	// Example: Публикация статьи в научном журнале
	Description string `json:"description,omitempty"`

	// kind
	// Enum: ["olympiad","development","scientific"]
	Kind struct {
		AchievementKind
	} `json:"kind,omitempty"`

	// name
	// Example: Публикация в журнале
	Name string `json:"name,omitempty"`

	// points limit
	// Example: 10
	PointsLimit int64 `json:"pointsLimit,omitempty"`
}

// Validate validates this api patch achievement template request
func (m *APIPatchAchievementTemplateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKind(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var apiPatchAchievementTemplateRequestTypeKindPropEnum []interface{}

func init() {
	var res []struct {
		AchievementKind
	}
	if err := json.Unmarshal([]byte(`["olympiad","development","scientific"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		apiPatchAchievementTemplateRequestTypeKindPropEnum = append(apiPatchAchievementTemplateRequestTypeKindPropEnum, v)
	}
}

// prop value enum
func (m *APIPatchAchievementTemplateRequest) validateKindEnum(path, location string, value *struct {
	AchievementKind
}) error {
	if err := validate.EnumCase(path, location, value, apiPatchAchievementTemplateRequestTypeKindPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *APIPatchAchievementTemplateRequest) validateKind(formats strfmt.Registry) error {
	if swag.IsZero(m.Kind) { // not required
		return nil
	}

	return nil
}

// ContextValidate validate this api patch achievement template request based on the context it is used
func (m *APIPatchAchievementTemplateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateKind(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIPatchAchievementTemplateRequest) contextValidateKind(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *APIPatchAchievementTemplateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIPatchAchievementTemplateRequest) UnmarshalBinary(b []byte) error {
	var res APIPatchAchievementTemplateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
