// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APICannotRemoveDepartmentError api cannot remove department error
//
// swagger:model api.CannotRemoveDepartmentError
type APICannotRemoveDepartmentError struct {

	// code
	// Example: CANNOT_REMOVE_DEPARTMENT
	Code string `json:"code,omitempty"`

	// details
	Details string `json:"details,omitempty"`

	// message
	// Example: Cannot remove department, it still has some users
	Message string `json:"message,omitempty"`

	// ru message
	// Example: Невозможно удалить кафедру, так как она содержит пользователей
	RuMessage string `json:"ruMessage,omitempty"`
}

// Validate validates this api cannot remove department error
func (m *APICannotRemoveDepartmentError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api cannot remove department error based on context it is used
func (m *APICannotRemoveDepartmentError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APICannotRemoveDepartmentError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APICannotRemoveDepartmentError) UnmarshalBinary(b []byte) error {
	var res APICannotRemoveDepartmentError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
