// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIInvalidDepartmentIDError api invalid department ID error
//
// swagger:model api.InvalidDepartmentIDError
type APIInvalidDepartmentIDError struct {

	// code
	// Example: INVALID_DEPARTMENT_ID
	Code string `json:"code,omitempty"`

	// details
	Details string `json:"details,omitempty"`

	// message
	// Example: Invalid department ID
	Message string `json:"message,omitempty"`

	// ru message
	// Example: Некорректный идентификатор кафедры
	RuMessage string `json:"ruMessage,omitempty"`
}

// Validate validates this api invalid department ID error
func (m *APIInvalidDepartmentIDError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api invalid department ID error based on context it is used
func (m *APIInvalidDepartmentIDError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIInvalidDepartmentIDError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIInvalidDepartmentIDError) UnmarshalBinary(b []byte) error {
	var res APIInvalidDepartmentIDError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
