// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIServerError api server error
//
// swagger:model api.ServerError
type APIServerError struct {

	// code
	// Example: SERVER_ERROR
	Code string `json:"code,omitempty"`

	// details
	Details string `json:"details,omitempty"`

	// message
	// Example: Internal server error
	Message string `json:"message,omitempty"`

	// ru message
	// Example: Внутренняя ошибка сервера
	RuMessage string `json:"ruMessage,omitempty"`
}

// Validate validates this api server error
func (m *APIServerError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api server error based on context it is used
func (m *APIServerError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIServerError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIServerError) UnmarshalBinary(b []byte) error {
	var res APIServerError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
