// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIDocumentNotFoundError api document not found error
//
// swagger:model api.DocumentNotFoundError
type APIDocumentNotFoundError struct {

	// code
	// Example: DOCUMENT_NOT_FOUND
	Code string `json:"code,omitempty"`

	// details
	Details string `json:"details,omitempty"`

	// message
	// Example: Document not found
	Message string `json:"message,omitempty"`

	// ru message
	// Example: Документ не найден
	RuMessage string `json:"ruMessage,omitempty"`
}

// Validate validates this api document not found error
func (m *APIDocumentNotFoundError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api document not found error based on context it is used
func (m *APIDocumentNotFoundError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIDocumentNotFoundError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIDocumentNotFoundError) UnmarshalBinary(b []byte) error {
	var res APIDocumentNotFoundError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
