// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// APIPatchUserRequest api patch user request
//
// swagger:model api.PatchUserRequest
type APIPatchUserRequest struct {

	// academic degree
	// Example: 2
	AcademicDegree int64 `json:"academicDegree,omitempty"`

	// academic title
	// Example: Профессор
	AcademicTitle string `json:"academicTitle,omitempty"`

	// category
	// Example: Высшая
	Category string `json:"category,omitempty"`

	// date of employment
	// Example: 2020-01-15T00:00:00Z
	DateOfEmployment string `json:"dateOfEmployment,omitempty"`

	// department Id
	// Example: 550e8400-e29b-41d4-a716-446655440000
	DepartmentID string `json:"departmentId,omitempty"`

	// employment rate
	// Example: 1
	EmploymentRate float64 `json:"employmentRate,omitempty"`

	// employment type
	// Example: 1
	EmploymentType int64 `json:"employmentType,omitempty"`

	// first name
	// Example: Ivan
	// Required: true
	FirstName *string `json:"firstName"`

	// honors
	// Example: Заслуженный деятель науки
	Honors string `json:"honors,omitempty"`

	// job title
	// Example: Профессор
	JobTitle string `json:"jobTitle,omitempty"`

	// last name
	// Example: Petrov
	// Required: true
	LastName *string `json:"lastName"`

	// middle name
	// Example: Sergeevich
	MiddleName string `json:"middleName,omitempty"`

	// personnel category
	// Example: 1
	PersonnelCategory int64 `json:"personnelCategory,omitempty"`

	// picture Url
	// Example: /images/users/ivan.jpg
	PictureURL string `json:"pictureUrl,omitempty"`

	// role Id
	// Example: 1
	// Required: true
	RoleID *int64 `json:"roleId"`

	// subdivision
	// Example: Кафедра информатики
	Subdivision string `json:"subdivision,omitempty"`

	// suspended
	// Example: false
	// Required: true
	Suspended *bool `json:"suspended"`

	// unemployment date
	// Example: 2023-12-31T00:00:00Z
	UnemploymentDate string `json:"unemploymentDate,omitempty"`
}

// Validate validates this api patch user request
func (m *APIPatchUserRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFirstName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRoleID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSuspended(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIPatchUserRequest) validateFirstName(formats strfmt.Registry) error {

	if err := validate.Required("firstName", "body", m.FirstName); err != nil {
		return err
	}

	return nil
}

func (m *APIPatchUserRequest) validateLastName(formats strfmt.Registry) error {

	if err := validate.Required("lastName", "body", m.LastName); err != nil {
		return err
	}

	return nil
}

func (m *APIPatchUserRequest) validateRoleID(formats strfmt.Registry) error {

	if err := validate.Required("roleId", "body", m.RoleID); err != nil {
		return err
	}

	return nil
}

func (m *APIPatchUserRequest) validateSuspended(formats strfmt.Registry) error {

	if err := validate.Required("suspended", "body", m.Suspended); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this api patch user request based on context it is used
func (m *APIPatchUserRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIPatchUserRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIPatchUserRequest) UnmarshalBinary(b []byte) error {
	var res APIPatchUserRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
