// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// APIAchievementTemplateResponse api achievement template response
//
// swagger:model api.AchievementTemplateResponse
type APIAchievementTemplateResponse struct {

	// active
	// Example: true
	// Required: true
	Active *bool `json:"active"`

	// description
	// Example: Публикация статьи в научном журнале
	// Required: true
	Description *string `json:"description"`

	// group Id
	// Example: 550e8400-e29b-41d4-a716-446655440000
	// Required: true
	GroupID *string `json:"groupId"`

	// id
	// Example: 550e8400-e29b-41d4-a716-446655440000
	// Required: true
	ID *string `json:"id"`

	// kind
	// Example: scientific
	// Required: true
	// Enum: ["olympiad","development","scientific"]
	Kind *string `json:"kind"`

	// name
	// Example: Публикация в журнале
	// Required: true
	Name *string `json:"name"`

	// points limit
	// Example: 10
	// Required: true
	PointsLimit *int64 `json:"pointsLimit"`
}

// Validate validates this api achievement template response
func (m *APIAchievementTemplateResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateActive(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGroupID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKind(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePointsLimit(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIAchievementTemplateResponse) validateActive(formats strfmt.Registry) error {

	if err := validate.Required("active", "body", m.Active); err != nil {
		return err
	}

	return nil
}

func (m *APIAchievementTemplateResponse) validateDescription(formats strfmt.Registry) error {

	if err := validate.Required("description", "body", m.Description); err != nil {
		return err
	}

	return nil
}

func (m *APIAchievementTemplateResponse) validateGroupID(formats strfmt.Registry) error {

	if err := validate.Required("groupId", "body", m.GroupID); err != nil {
		return err
	}

	return nil
}

func (m *APIAchievementTemplateResponse) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

var apiAchievementTemplateResponseTypeKindPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["olympiad","development","scientific"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		apiAchievementTemplateResponseTypeKindPropEnum = append(apiAchievementTemplateResponseTypeKindPropEnum, v)
	}
}

const (

	// APIAchievementTemplateResponseKindOlympiad captures enum value "olympiad"
	APIAchievementTemplateResponseKindOlympiad string = "olympiad"

	// APIAchievementTemplateResponseKindDevelopment captures enum value "development"
	APIAchievementTemplateResponseKindDevelopment string = "development"

	// APIAchievementTemplateResponseKindScientific captures enum value "scientific"
	APIAchievementTemplateResponseKindScientific string = "scientific"
)

// prop value enum
func (m *APIAchievementTemplateResponse) validateKindEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, apiAchievementTemplateResponseTypeKindPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *APIAchievementTemplateResponse) validateKind(formats strfmt.Registry) error {

	if err := validate.Required("kind", "body", m.Kind); err != nil {
		return err
	}

	// value enum
	if err := m.validateKindEnum("kind", "body", *m.Kind); err != nil {
		return err
	}

	return nil
}

func (m *APIAchievementTemplateResponse) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *APIAchievementTemplateResponse) validatePointsLimit(formats strfmt.Registry) error {

	if err := validate.Required("pointsLimit", "body", m.PointsLimit); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this api achievement template response based on context it is used
func (m *APIAchievementTemplateResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIAchievementTemplateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIAchievementTemplateResponse) UnmarshalBinary(b []byte) error {
	var res APIAchievementTemplateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
