// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ParamAddDocumentRequest param add document request
//
// swagger:model param.AddDocumentRequest
type ParamAddDocumentRequest struct {

	// file Id
	// Example: 550e8400-e29b-41d4-a716-446655440000
	// Required: true
	FileID *string `json:"fileId"`

	// name
	// Example: Publication proof
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this param add document request
func (m *ParamAddDocumentRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFileID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ParamAddDocumentRequest) validateFileID(formats strfmt.Registry) error {

	if err := validate.Required("fileId", "body", m.FileID); err != nil {
		return err
	}

	return nil
}

func (m *ParamAddDocumentRequest) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this param add document request based on context it is used
func (m *ParamAddDocumentRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ParamAddDocumentRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ParamAddDocumentRequest) UnmarshalBinary(b []byte) error {
	var res ParamAddDocumentRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
