// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ParamPatchAchievementTemplateRequest param patch achievement template request
//
// swagger:model param.PatchAchievementTemplateRequest
type ParamPatchAchievementTemplateRequest struct {

	// active
	// Example: true
	Active bool `json:"active,omitempty"`

	// description
	// Example: Публикация статьи в научном журнале
	Description string `json:"description,omitempty"`

	// name
	// Example: Публикация в журнале
	Name string `json:"name,omitempty"`

	// points limit
	// Example: 10
	PointsLimit int64 `json:"pointsLimit,omitempty"`

	// reviewer role
	// Example: dephead
	ReviewerRole string `json:"reviewerRole,omitempty"`
}

// Validate validates this param patch achievement template request
func (m *ParamPatchAchievementTemplateRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this param patch achievement template request based on context it is used
func (m *ParamPatchAchievementTemplateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ParamPatchAchievementTemplateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ParamPatchAchievementTemplateRequest) UnmarshalBinary(b []byte) error {
	var res ParamPatchAchievementTemplateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
