// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RespondError respond error
//
// swagger:model respond.Error
type RespondError struct {

	// code
	Code string `json:"code,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// status code
	StatusCode int64 `json:"statusCode,omitempty"`

	// trace Id
	TraceID string `json:"traceId,omitempty"`
}

// Validate validates this respond error
func (m *RespondError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this respond error based on context it is used
func (m *RespondError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RespondError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RespondError) UnmarshalBinary(b []byte) error {
	var res RespondError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
