// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RespondAccountingPeriods respond accounting periods
//
// swagger:model respond.AccountingPeriods
type RespondAccountingPeriods struct {

	// accounting periods
	// Required: true
	AccountingPeriods []*RespondAccountingPeriod `json:"accounting_periods"`

	// total
	// Required: true
	Total *int64 `json:"total"`
}

// Validate validates this respond accounting periods
func (m *RespondAccountingPeriods) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccountingPeriods(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTotal(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RespondAccountingPeriods) validateAccountingPeriods(formats strfmt.Registry) error {

	if err := validate.Required("accounting_periods", "body", m.AccountingPeriods); err != nil {
		return err
	}

	for i := 0; i < len(m.AccountingPeriods); i++ {
		if swag.IsZero(m.AccountingPeriods[i]) { // not required
			continue
		}

		if m.AccountingPeriods[i] != nil {
			if err := m.AccountingPeriods[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("accounting_periods" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("accounting_periods" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *RespondAccountingPeriods) validateTotal(formats strfmt.Registry) error {

	if err := validate.Required("total", "body", m.Total); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this respond accounting periods based on the context it is used
func (m *RespondAccountingPeriods) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAccountingPeriods(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RespondAccountingPeriods) contextValidateAccountingPeriods(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.AccountingPeriods); i++ {

		if m.AccountingPeriods[i] != nil {

			if swag.IsZero(m.AccountingPeriods[i]) { // not required
				return nil
			}

			if err := m.AccountingPeriods[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("accounting_periods" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("accounting_periods" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *RespondAccountingPeriods) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RespondAccountingPeriods) UnmarshalBinary(b []byte) error {
	var res RespondAccountingPeriods
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
