// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RespondUser respond user
//
// swagger:model respond.User
type RespondUser struct {

	// academic degree
	// Example: Доктор наук
	AcademicDegree string `json:"academicDegree,omitempty"`

	// academic title
	// Example: Профессор
	AcademicTitle string `json:"academicTitle,omitempty"`

	// category
	// Example: Высшая
	Category string `json:"category,omitempty"`

	// date of employment
	// Example: 24.02.2022
	DateOfEmployment string `json:"dateOfEmployment,omitempty"`

	// department Id
	DepartmentID string `json:"departmentId,omitempty"`

	// employment rate
	// Example: 1.0
	// Required: true
	EmploymentRate *string `json:"employmentRate"`

	// employment type
	// Example: Внешнее совместительство
	// Required: true
	EmploymentType *string `json:"employmentType"`

	// full name
	// Example: Ivanov Ivan Ivanovich
	// Required: true
	FullName *string `json:"fullName"`

	// honors
	// Example: Заслуженный деятель науки
	Honors string `json:"honors,omitempty"`

	// id
	// Example: ivanivanov
	// Required: true
	ID *string `json:"id"`

	// job title
	// Example: Профессор
	// Required: true
	JobTitle *string `json:"jobTitle"`

	// personnel category
	// Example: Административно-управленческий персонал
	// Required: true
	PersonnelCategory *string `json:"personnelCategory"`

	// picture Url
	// Example: /images/users/ivan.jpg
	// Required: true
	PictureURL *string `json:"pictureUrl"`

	// roles
	// Required: true
	Roles []*RespondRole `json:"roles"`
}

// Validate validates this respond user
func (m *RespondUser) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEmploymentRate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEmploymentType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFullName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateJobTitle(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePersonnelCategory(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePictureURL(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRoles(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RespondUser) validateEmploymentRate(formats strfmt.Registry) error {

	if err := validate.Required("employmentRate", "body", m.EmploymentRate); err != nil {
		return err
	}

	return nil
}

func (m *RespondUser) validateEmploymentType(formats strfmt.Registry) error {

	if err := validate.Required("employmentType", "body", m.EmploymentType); err != nil {
		return err
	}

	return nil
}

func (m *RespondUser) validateFullName(formats strfmt.Registry) error {

	if err := validate.Required("fullName", "body", m.FullName); err != nil {
		return err
	}

	return nil
}

func (m *RespondUser) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *RespondUser) validateJobTitle(formats strfmt.Registry) error {

	if err := validate.Required("jobTitle", "body", m.JobTitle); err != nil {
		return err
	}

	return nil
}

func (m *RespondUser) validatePersonnelCategory(formats strfmt.Registry) error {

	if err := validate.Required("personnelCategory", "body", m.PersonnelCategory); err != nil {
		return err
	}

	return nil
}

func (m *RespondUser) validatePictureURL(formats strfmt.Registry) error {

	if err := validate.Required("pictureUrl", "body", m.PictureURL); err != nil {
		return err
	}

	return nil
}

func (m *RespondUser) validateRoles(formats strfmt.Registry) error {

	if err := validate.Required("roles", "body", m.Roles); err != nil {
		return err
	}

	for i := 0; i < len(m.Roles); i++ {
		if swag.IsZero(m.Roles[i]) { // not required
			continue
		}

		if m.Roles[i] != nil {
			if err := m.Roles[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("roles" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("roles" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this respond user based on the context it is used
func (m *RespondUser) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRoles(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RespondUser) contextValidateRoles(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Roles); i++ {

		if m.Roles[i] != nil {

			if swag.IsZero(m.Roles[i]) { // not required
				return nil
			}

			if err := m.Roles[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("roles" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("roles" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *RespondUser) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RespondUser) UnmarshalBinary(b []byte) error {
	var res RespondUser
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
