// This file is auto-generated by @hey-api/openapi-ts

import {
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";
import type { AxiosError } from "axios";

import { client } from "../client.gen";
import {
  deleteAchievementsById,
  deleteAchievementsByIdDocumentsByDocumentId,
  deleteFilesById,
  getAchievementGroups,
  getAchievements,
  getAchievementsById,
  getAchievementsUsers,
  getAchievementTemplates,
  getAuthValidate,
  getDepartments,
  getDepartmentsById,
  getFiles,
  getFilesById,
  getFilesByIdDownload,
  getReportsUserPoints,
  getRoles,
  getUsers,
  getUsersById,
  getUsersMe,
  type Options,
  patchAchievementGroupsById,
  patchAchievementTemplatesById,
  postAchievementGroups,
  postAchievements,
  postAchievementsByIdDocuments,
  postAchievementsByIdReview,
  postAchievementsByIdSubmit,
  postAchievementsByIdSubmitWithNewPoints,
  postAchievementTemplates,
  postAuthLogin,
  postFiles,
  postReportsMarkAllAccounted,
} from "../sdk.gen";
import type {
  DeleteAchievementsByIdData,
  DeleteAchievementsByIdDocumentsByDocumentIdData,
  DeleteAchievementsByIdDocumentsByDocumentIdError,
  DeleteAchievementsByIdError,
  DeleteFilesByIdData,
  DeleteFilesByIdError,
  GetAchievementGroupsData,
  GetAchievementGroupsError,
  GetAchievementGroupsResponse,
  GetAchievementsByIdData,
  GetAchievementsByIdError,
  GetAchievementsByIdResponse,
  GetAchievementsData,
  GetAchievementsError,
  GetAchievementsResponse,
  GetAchievementsUsersData,
  GetAchievementsUsersError,
  GetAchievementsUsersResponse,
  GetAchievementTemplatesData,
  GetAchievementTemplatesError,
  GetAchievementTemplatesResponse,
  GetAuthValidateData,
  GetAuthValidateError,
  GetAuthValidateResponse,
  GetDepartmentsByIdData,
  GetDepartmentsByIdError,
  GetDepartmentsByIdResponse,
  GetDepartmentsData,
  GetDepartmentsError,
  GetDepartmentsResponse,
  GetFilesByIdData,
  GetFilesByIdDownloadData,
  GetFilesByIdDownloadError,
  GetFilesByIdError,
  GetFilesByIdResponse,
  GetFilesData,
  GetFilesError,
  GetFilesResponse,
  GetReportsUserPointsData,
  GetReportsUserPointsError,
  GetRolesData,
  GetRolesError,
  GetRolesResponse,
  GetUsersByIdData,
  GetUsersByIdError,
  GetUsersByIdResponse,
  GetUsersData,
  GetUsersError,
  GetUsersMeData,
  GetUsersMeError,
  GetUsersMeResponse,
  GetUsersResponse,
  PatchAchievementGroupsByIdData,
  PatchAchievementGroupsByIdError,
  PatchAchievementGroupsByIdResponse,
  PatchAchievementTemplatesByIdData,
  PatchAchievementTemplatesByIdError,
  PatchAchievementTemplatesByIdResponse,
  PostAchievementGroupsData,
  PostAchievementGroupsError,
  PostAchievementGroupsResponse,
  PostAchievementsByIdDocumentsData,
  PostAchievementsByIdDocumentsError,
  PostAchievementsByIdDocumentsResponse,
  PostAchievementsByIdReviewData,
  PostAchievementsByIdReviewError,
  PostAchievementsByIdReviewResponse,
  PostAchievementsByIdSubmitData,
  PostAchievementsByIdSubmitError,
  PostAchievementsByIdSubmitResponse,
  PostAchievementsByIdSubmitWithNewPointsData,
  PostAchievementsByIdSubmitWithNewPointsError,
  PostAchievementsByIdSubmitWithNewPointsResponse,
  PostAchievementsData,
  PostAchievementsError,
  PostAchievementsResponse,
  PostAchievementTemplatesData,
  PostAchievementTemplatesError,
  PostAchievementTemplatesResponse,
  PostAuthLoginData,
  PostAuthLoginError,
  PostAuthLoginResponse,
  PostFilesData,
  PostFilesError,
  PostFilesResponse,
  PostReportsMarkAllAccountedData,
  PostReportsMarkAllAccountedError,
  PostReportsMarkAllAccountedResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseURL" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL:
      options?.baseURL || (options?.client ?? client).getConfig().baseURL,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getAchievementGroupsQueryKey = (
  options?: Options<GetAchievementGroupsData>,
) => createQueryKey("getAchievementGroups", options);

/**
 * Get all achievement groups
 *
 * Retrieves all achievement groups with filtering options
 */
export const getAchievementGroupsOptions = (
  options?: Options<GetAchievementGroupsData>,
) =>
  queryOptions<
    GetAchievementGroupsResponse,
    AxiosError<GetAchievementGroupsError>,
    GetAchievementGroupsResponse,
    ReturnType<typeof getAchievementGroupsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAchievementGroups({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAchievementGroupsQueryKey(options),
  });

/**
 * Create new achievement group
 *
 * Creates a new achievement group
 */
export const postAchievementGroupsMutation = (
  options?: Partial<Options<PostAchievementGroupsData>>,
): UseMutationOptions<
  PostAchievementGroupsResponse,
  AxiosError<PostAchievementGroupsError>,
  Options<PostAchievementGroupsData>
> => {
  const mutationOptions: UseMutationOptions<
    PostAchievementGroupsResponse,
    AxiosError<PostAchievementGroupsError>,
    Options<PostAchievementGroupsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postAchievementGroups({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update achievement group
 *
 * Updates an achievement group
 */
export const patchAchievementGroupsByIdMutation = (
  options?: Partial<Options<PatchAchievementGroupsByIdData>>,
): UseMutationOptions<
  PatchAchievementGroupsByIdResponse,
  AxiosError<PatchAchievementGroupsByIdError>,
  Options<PatchAchievementGroupsByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchAchievementGroupsByIdResponse,
    AxiosError<PatchAchievementGroupsByIdError>,
    Options<PatchAchievementGroupsByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await patchAchievementGroupsById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getAchievementTemplatesQueryKey = (
  options?: Options<GetAchievementTemplatesData>,
) => createQueryKey("getAchievementTemplates", options);

/**
 * Get all achievement templates
 *
 * Retrieves all achievement templates
 */
export const getAchievementTemplatesOptions = (
  options?: Options<GetAchievementTemplatesData>,
) =>
  queryOptions<
    GetAchievementTemplatesResponse,
    AxiosError<GetAchievementTemplatesError>,
    GetAchievementTemplatesResponse,
    ReturnType<typeof getAchievementTemplatesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAchievementTemplates({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAchievementTemplatesQueryKey(options),
  });

/**
 * Create new achievement template
 *
 * Creates a new achievement template
 */
export const postAchievementTemplatesMutation = (
  options?: Partial<Options<PostAchievementTemplatesData>>,
): UseMutationOptions<
  PostAchievementTemplatesResponse,
  AxiosError<PostAchievementTemplatesError>,
  Options<PostAchievementTemplatesData>
> => {
  const mutationOptions: UseMutationOptions<
    PostAchievementTemplatesResponse,
    AxiosError<PostAchievementTemplatesError>,
    Options<PostAchievementTemplatesData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postAchievementTemplates({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update achievement template
 *
 * Updates an achievement template
 */
export const patchAchievementTemplatesByIdMutation = (
  options?: Partial<Options<PatchAchievementTemplatesByIdData>>,
): UseMutationOptions<
  PatchAchievementTemplatesByIdResponse,
  AxiosError<PatchAchievementTemplatesByIdError>,
  Options<PatchAchievementTemplatesByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchAchievementTemplatesByIdResponse,
    AxiosError<PatchAchievementTemplatesByIdError>,
    Options<PatchAchievementTemplatesByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await patchAchievementTemplatesById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getAchievementsQueryKey = (
  options?: Options<GetAchievementsData>,
) => createQueryKey("getAchievements", options);

/**
 * Get all achievements for the current user
 *
 * Retrieves all achievements for the current user with pagination
 */
export const getAchievementsOptions = (
  options?: Options<GetAchievementsData>,
) =>
  queryOptions<
    GetAchievementsResponse,
    AxiosError<GetAchievementsError>,
    GetAchievementsResponse,
    ReturnType<typeof getAchievementsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAchievements({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAchievementsQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const getAchievementsInfiniteQueryKey = (
  options?: Options<GetAchievementsData>,
): QueryKey<Options<GetAchievementsData>> =>
  createQueryKey("getAchievements", options, true);

/**
 * Get all achievements for the current user
 *
 * Retrieves all achievements for the current user with pagination
 */
export const getAchievementsInfiniteOptions = (
  options?: Options<GetAchievementsData>,
) =>
  infiniteQueryOptions<
    GetAchievementsResponse,
    AxiosError<GetAchievementsError>,
    InfiniteData<GetAchievementsResponse>,
    QueryKey<Options<GetAchievementsData>>,
    | number
    | Pick<
        QueryKey<Options<GetAchievementsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetAchievementsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getAchievements({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getAchievementsInfiniteQueryKey(options),
    },
  );

/**
 * Create a new achievement
 *
 * Creates a new achievement for the current user
 */
export const postAchievementsMutation = (
  options?: Partial<Options<PostAchievementsData>>,
): UseMutationOptions<
  PostAchievementsResponse,
  AxiosError<PostAchievementsError>,
  Options<PostAchievementsData>
> => {
  const mutationOptions: UseMutationOptions<
    PostAchievementsResponse,
    AxiosError<PostAchievementsError>,
    Options<PostAchievementsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postAchievements({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getAchievementsUsersQueryKey = (
  options?: Options<GetAchievementsUsersData>,
) => createQueryKey("getAchievementsUsers", options);

/**
 * Get users with achievements
 *
 * Retrieves users with achievements based on role permissions
 */
export const getAchievementsUsersOptions = (
  options?: Options<GetAchievementsUsersData>,
) =>
  queryOptions<
    GetAchievementsUsersResponse,
    AxiosError<GetAchievementsUsersError>,
    GetAchievementsUsersResponse,
    ReturnType<typeof getAchievementsUsersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAchievementsUsers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAchievementsUsersQueryKey(options),
  });

export const getAchievementsUsersInfiniteQueryKey = (
  options?: Options<GetAchievementsUsersData>,
): QueryKey<Options<GetAchievementsUsersData>> =>
  createQueryKey("getAchievementsUsers", options, true);

/**
 * Get users with achievements
 *
 * Retrieves users with achievements based on role permissions
 */
export const getAchievementsUsersInfiniteOptions = (
  options?: Options<GetAchievementsUsersData>,
) =>
  infiniteQueryOptions<
    GetAchievementsUsersResponse,
    AxiosError<GetAchievementsUsersError>,
    InfiniteData<GetAchievementsUsersResponse>,
    QueryKey<Options<GetAchievementsUsersData>>,
    | number
    | Pick<
        QueryKey<Options<GetAchievementsUsersData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetAchievementsUsersData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getAchievementsUsers({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getAchievementsUsersInfiniteQueryKey(options),
    },
  );

/**
 * Delete an achievement
 *
 * Deletes an achievement
 */
export const deleteAchievementsByIdMutation = (
  options?: Partial<Options<DeleteAchievementsByIdData>>,
): UseMutationOptions<
  unknown,
  AxiosError<DeleteAchievementsByIdError>,
  Options<DeleteAchievementsByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<DeleteAchievementsByIdError>,
    Options<DeleteAchievementsByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteAchievementsById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getAchievementsByIdQueryKey = (
  options: Options<GetAchievementsByIdData>,
) => createQueryKey("getAchievementsById", options);

/**
 * Get a specific achievement
 *
 * Retrieves a specific achievement by ID
 */
export const getAchievementsByIdOptions = (
  options: Options<GetAchievementsByIdData>,
) =>
  queryOptions<
    GetAchievementsByIdResponse,
    AxiosError<GetAchievementsByIdError>,
    GetAchievementsByIdResponse,
    ReturnType<typeof getAchievementsByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAchievementsById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAchievementsByIdQueryKey(options),
  });

/**
 * Add a document to an achievement
 *
 * Adds a document to an achievement
 */
export const postAchievementsByIdDocumentsMutation = (
  options?: Partial<Options<PostAchievementsByIdDocumentsData>>,
): UseMutationOptions<
  PostAchievementsByIdDocumentsResponse,
  AxiosError<PostAchievementsByIdDocumentsError>,
  Options<PostAchievementsByIdDocumentsData>
> => {
  const mutationOptions: UseMutationOptions<
    PostAchievementsByIdDocumentsResponse,
    AxiosError<PostAchievementsByIdDocumentsError>,
    Options<PostAchievementsByIdDocumentsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postAchievementsByIdDocuments({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Remove a document from an achievement
 *
 * Removes a document from an achievement
 */
export const deleteAchievementsByIdDocumentsByDocumentIdMutation = (
  options?: Partial<Options<DeleteAchievementsByIdDocumentsByDocumentIdData>>,
): UseMutationOptions<
  unknown,
  AxiosError<DeleteAchievementsByIdDocumentsByDocumentIdError>,
  Options<DeleteAchievementsByIdDocumentsByDocumentIdData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<DeleteAchievementsByIdDocumentsByDocumentIdError>,
    Options<DeleteAchievementsByIdDocumentsByDocumentIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteAchievementsByIdDocumentsByDocumentId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Review an achievement
 *
 * Reviews an achievement with approve, disapprove, or request changes action
 */
export const postAchievementsByIdReviewMutation = (
  options?: Partial<Options<PostAchievementsByIdReviewData>>,
): UseMutationOptions<
  PostAchievementsByIdReviewResponse,
  AxiosError<PostAchievementsByIdReviewError>,
  Options<PostAchievementsByIdReviewData>
> => {
  const mutationOptions: UseMutationOptions<
    PostAchievementsByIdReviewResponse,
    AxiosError<PostAchievementsByIdReviewError>,
    Options<PostAchievementsByIdReviewData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postAchievementsByIdReview({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Submit an achievement for review
 *
 * Submits an achievement for review
 */
export const postAchievementsByIdSubmitMutation = (
  options?: Partial<Options<PostAchievementsByIdSubmitData>>,
): UseMutationOptions<
  PostAchievementsByIdSubmitResponse,
  AxiosError<PostAchievementsByIdSubmitError>,
  Options<PostAchievementsByIdSubmitData>
> => {
  const mutationOptions: UseMutationOptions<
    PostAchievementsByIdSubmitResponse,
    AxiosError<PostAchievementsByIdSubmitError>,
    Options<PostAchievementsByIdSubmitData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postAchievementsByIdSubmit({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Submit achievement with updated points
 *
 * Allows teachers to submit achievement with updated points when changes are requested by reviewers
 */
export const postAchievementsByIdSubmitWithNewPointsMutation = (
  options?: Partial<Options<PostAchievementsByIdSubmitWithNewPointsData>>,
): UseMutationOptions<
  PostAchievementsByIdSubmitWithNewPointsResponse,
  AxiosError<PostAchievementsByIdSubmitWithNewPointsError>,
  Options<PostAchievementsByIdSubmitWithNewPointsData>
> => {
  const mutationOptions: UseMutationOptions<
    PostAchievementsByIdSubmitWithNewPointsResponse,
    AxiosError<PostAchievementsByIdSubmitWithNewPointsError>,
    Options<PostAchievementsByIdSubmitWithNewPointsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postAchievementsByIdSubmitWithNewPoints({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * User login
 *
 * Verifies user credentials and returns a JWT token
 */
export const postAuthLoginMutation = (
  options?: Partial<Options<PostAuthLoginData>>,
): UseMutationOptions<
  PostAuthLoginResponse,
  AxiosError<PostAuthLoginError>,
  Options<PostAuthLoginData>
> => {
  const mutationOptions: UseMutationOptions<
    PostAuthLoginResponse,
    AxiosError<PostAuthLoginError>,
    Options<PostAuthLoginData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postAuthLogin({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getAuthValidateQueryKey = (
  options?: Options<GetAuthValidateData>,
) => createQueryKey("getAuthValidate", options);

/**
 * Validate JWT token
 *
 * Validates a JWT token and returns the identity information
 */
export const getAuthValidateOptions = (
  options?: Options<GetAuthValidateData>,
) =>
  queryOptions<
    GetAuthValidateResponse,
    AxiosError<GetAuthValidateError>,
    GetAuthValidateResponse,
    ReturnType<typeof getAuthValidateQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAuthValidate({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAuthValidateQueryKey(options),
  });

export const getDepartmentsQueryKey = (options?: Options<GetDepartmentsData>) =>
  createQueryKey("getDepartments", options);

/**
 * List all departments
 *
 * Retrieves list of all registered departments
 */
export const getDepartmentsOptions = (options?: Options<GetDepartmentsData>) =>
  queryOptions<
    GetDepartmentsResponse,
    AxiosError<GetDepartmentsError>,
    GetDepartmentsResponse,
    ReturnType<typeof getDepartmentsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getDepartments({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getDepartmentsQueryKey(options),
  });

export const getDepartmentsByIdQueryKey = (
  options: Options<GetDepartmentsByIdData>,
) => createQueryKey("getDepartmentsById", options);

/**
 * Get department details
 *
 * Retrieves detailed information about a department
 */
export const getDepartmentsByIdOptions = (
  options: Options<GetDepartmentsByIdData>,
) =>
  queryOptions<
    GetDepartmentsByIdResponse,
    AxiosError<GetDepartmentsByIdError>,
    GetDepartmentsByIdResponse,
    ReturnType<typeof getDepartmentsByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getDepartmentsById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getDepartmentsByIdQueryKey(options),
  });

export const getFilesQueryKey = (options?: Options<GetFilesData>) =>
  createQueryKey("getFiles", options);

/**
 * Search files
 *
 * Returns a list of files based on search criteria
 */
export const getFilesOptions = (options?: Options<GetFilesData>) =>
  queryOptions<
    GetFilesResponse,
    AxiosError<GetFilesError>,
    GetFilesResponse,
    ReturnType<typeof getFilesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getFiles({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getFilesQueryKey(options),
  });

export const getFilesInfiniteQueryKey = (
  options?: Options<GetFilesData>,
): QueryKey<Options<GetFilesData>> => createQueryKey("getFiles", options, true);

/**
 * Search files
 *
 * Returns a list of files based on search criteria
 */
export const getFilesInfiniteOptions = (options?: Options<GetFilesData>) =>
  infiniteQueryOptions<
    GetFilesResponse,
    AxiosError<GetFilesError>,
    InfiniteData<GetFilesResponse>,
    QueryKey<Options<GetFilesData>>,
    | number
    | Pick<
        QueryKey<Options<GetFilesData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetFilesData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getFiles({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getFilesInfiniteQueryKey(options),
    },
  );

/**
 * Upload a file
 *
 * Uploads a new file. Admin users create common files, regular users create files owned by themselves.
 */
export const postFilesMutation = (
  options?: Partial<Options<PostFilesData>>,
): UseMutationOptions<
  PostFilesResponse,
  AxiosError<PostFilesError>,
  Options<PostFilesData>
> => {
  const mutationOptions: UseMutationOptions<
    PostFilesResponse,
    AxiosError<PostFilesError>,
    Options<PostFilesData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postFiles({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete file
 *
 * Deletes a file by ID
 */
export const deleteFilesByIdMutation = (
  options?: Partial<Options<DeleteFilesByIdData>>,
): UseMutationOptions<
  unknown,
  AxiosError<DeleteFilesByIdError>,
  Options<DeleteFilesByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<DeleteFilesByIdError>,
    Options<DeleteFilesByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteFilesById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getFilesByIdQueryKey = (options: Options<GetFilesByIdData>) =>
  createQueryKey("getFilesById", options);

/**
 * Get file by ID
 *
 * Returns a file by ID with download URL
 */
export const getFilesByIdOptions = (options: Options<GetFilesByIdData>) =>
  queryOptions<
    GetFilesByIdResponse,
    AxiosError<GetFilesByIdError>,
    GetFilesByIdResponse,
    ReturnType<typeof getFilesByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getFilesById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getFilesByIdQueryKey(options),
  });

export const getFilesByIdDownloadQueryKey = (
  options: Options<GetFilesByIdDownloadData>,
) => createQueryKey("getFilesByIdDownload", options);

/**
 * Download file
 *
 * Redirects to a pre-signed URL for downloading the file
 */
export const getFilesByIdDownloadOptions = (
  options: Options<GetFilesByIdDownloadData>,
) =>
  queryOptions<
    unknown,
    AxiosError<GetFilesByIdDownloadError>,
    unknown,
    ReturnType<typeof getFilesByIdDownloadQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getFilesByIdDownload({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getFilesByIdDownloadQueryKey(options),
  });

/**
 * Mark all done achievements as accounted
 *
 * Marks all achievements with "done" status as "accounted" in the system
 */
export const postReportsMarkAllAccountedMutation = (
  options?: Partial<Options<PostReportsMarkAllAccountedData>>,
): UseMutationOptions<
  PostReportsMarkAllAccountedResponse,
  AxiosError<PostReportsMarkAllAccountedError>,
  Options<PostReportsMarkAllAccountedData>
> => {
  const mutationOptions: UseMutationOptions<
    PostReportsMarkAllAccountedResponse,
    AxiosError<PostReportsMarkAllAccountedError>,
    Options<PostReportsMarkAllAccountedData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postReportsMarkAllAccounted({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getReportsUserPointsQueryKey = (
  options?: Options<GetReportsUserPointsData>,
) => createQueryKey("getReportsUserPoints", options);

/**
 * Generate user points report
 *
 * Generates an Excel report containing all users with their achievement points summary
 */
export const getReportsUserPointsOptions = (
  options?: Options<GetReportsUserPointsData>,
) =>
  queryOptions<
    unknown,
    AxiosError<GetReportsUserPointsError>,
    unknown,
    ReturnType<typeof getReportsUserPointsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getReportsUserPoints({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getReportsUserPointsQueryKey(options),
  });

export const getRolesQueryKey = (options?: Options<GetRolesData>) =>
  createQueryKey("getRoles", options);

/**
 * List all roles
 *
 * Retrieves all system roles with their permissions
 */
export const getRolesOptions = (options?: Options<GetRolesData>) =>
  queryOptions<
    GetRolesResponse,
    AxiosError<GetRolesError>,
    GetRolesResponse,
    ReturnType<typeof getRolesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRoles({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRolesQueryKey(options),
  });

export const getUsersQueryKey = (options?: Options<GetUsersData>) =>
  createQueryKey("getUsers", options);

/**
 * Get all users registered in the system
 *
 * Retrieves detailed information about all users
 */
export const getUsersOptions = (options?: Options<GetUsersData>) =>
  queryOptions<
    GetUsersResponse,
    AxiosError<GetUsersError>,
    GetUsersResponse,
    ReturnType<typeof getUsersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUsers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUsersQueryKey(options),
  });

export const getUsersMeQueryKey = (options?: Options<GetUsersMeData>) =>
  createQueryKey("getUsersMe", options);

/**
 * Get current user information
 *
 * Returns information about the current authenticated user
 */
export const getUsersMeOptions = (options?: Options<GetUsersMeData>) =>
  queryOptions<
    GetUsersMeResponse,
    AxiosError<GetUsersMeError>,
    GetUsersMeResponse,
    ReturnType<typeof getUsersMeQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUsersMe({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUsersMeQueryKey(options),
  });

export const getUsersByIdQueryKey = (options: Options<GetUsersByIdData>) =>
  createQueryKey("getUsersById", options);

/**
 * Get user details
 *
 * Retrieves detailed information about a user
 */
export const getUsersByIdOptions = (options: Options<GetUsersByIdData>) =>
  queryOptions<
    GetUsersByIdResponse,
    AxiosError<GetUsersByIdError>,
    GetUsersByIdResponse,
    ReturnType<typeof getUsersByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUsersById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUsersByIdQueryKey(options),
  });
