// Code generated by go-swagger; DO NOT EDIT.

package reports

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kozlov-ma/sesc-backend/apiclient/models"
)

// GetReportsUserPointsReader is a Reader for the GetReportsUserPoints structure.
type GetReportsUserPointsReader struct {
	formats strfmt.Registry
	writer  io.Writer
}

// ReadResponse reads a server response into the received o.
func (o *GetReportsUserPointsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetReportsUserPointsOK(o.writer)
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetReportsUserPointsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetReportsUserPointsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetReportsUserPointsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /reports/user-points] GetReportsUserPoints", response, response.Code())
	}
}

// NewGetReportsUserPointsOK creates a GetReportsUserPointsOK with default headers values
func NewGetReportsUserPointsOK(writer io.Writer) *GetReportsUserPointsOK {
	return &GetReportsUserPointsOK{

		Payload: writer,
	}
}

/*
GetReportsUserPointsOK describes a response with status code 200, with default header values.

Excel file with user points report
*/
type GetReportsUserPointsOK struct {
	Payload io.Writer
}

// IsSuccess returns true when this get reports user points o k response has a 2xx status code
func (o *GetReportsUserPointsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get reports user points o k response has a 3xx status code
func (o *GetReportsUserPointsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get reports user points o k response has a 4xx status code
func (o *GetReportsUserPointsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get reports user points o k response has a 5xx status code
func (o *GetReportsUserPointsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get reports user points o k response a status code equal to that given
func (o *GetReportsUserPointsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get reports user points o k response
func (o *GetReportsUserPointsOK) Code() int {
	return 200
}

func (o *GetReportsUserPointsOK) Error() string {
	return fmt.Sprintf("[GET /reports/user-points][%d] getReportsUserPointsOK", 200)
}

func (o *GetReportsUserPointsOK) String() string {
	return fmt.Sprintf("[GET /reports/user-points][%d] getReportsUserPointsOK", 200)
}

func (o *GetReportsUserPointsOK) GetPayload() io.Writer {
	return o.Payload
}

func (o *GetReportsUserPointsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetReportsUserPointsUnauthorized creates a GetReportsUserPointsUnauthorized with default headers values
func NewGetReportsUserPointsUnauthorized() *GetReportsUserPointsUnauthorized {
	return &GetReportsUserPointsUnauthorized{}
}

/*
GetReportsUserPointsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetReportsUserPointsUnauthorized struct {
	Payload *models.RespondError
}

// IsSuccess returns true when this get reports user points unauthorized response has a 2xx status code
func (o *GetReportsUserPointsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get reports user points unauthorized response has a 3xx status code
func (o *GetReportsUserPointsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get reports user points unauthorized response has a 4xx status code
func (o *GetReportsUserPointsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get reports user points unauthorized response has a 5xx status code
func (o *GetReportsUserPointsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get reports user points unauthorized response a status code equal to that given
func (o *GetReportsUserPointsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get reports user points unauthorized response
func (o *GetReportsUserPointsUnauthorized) Code() int {
	return 401
}

func (o *GetReportsUserPointsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /reports/user-points][%d] getReportsUserPointsUnauthorized %s", 401, payload)
}

func (o *GetReportsUserPointsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /reports/user-points][%d] getReportsUserPointsUnauthorized %s", 401, payload)
}

func (o *GetReportsUserPointsUnauthorized) GetPayload() *models.RespondError {
	return o.Payload
}

func (o *GetReportsUserPointsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RespondError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetReportsUserPointsForbidden creates a GetReportsUserPointsForbidden with default headers values
func NewGetReportsUserPointsForbidden() *GetReportsUserPointsForbidden {
	return &GetReportsUserPointsForbidden{}
}

/*
GetReportsUserPointsForbidden describes a response with status code 403, with default header values.

Forbidden - Admin access required
*/
type GetReportsUserPointsForbidden struct {
	Payload *models.RespondError
}

// IsSuccess returns true when this get reports user points forbidden response has a 2xx status code
func (o *GetReportsUserPointsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get reports user points forbidden response has a 3xx status code
func (o *GetReportsUserPointsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get reports user points forbidden response has a 4xx status code
func (o *GetReportsUserPointsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get reports user points forbidden response has a 5xx status code
func (o *GetReportsUserPointsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get reports user points forbidden response a status code equal to that given
func (o *GetReportsUserPointsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get reports user points forbidden response
func (o *GetReportsUserPointsForbidden) Code() int {
	return 403
}

func (o *GetReportsUserPointsForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /reports/user-points][%d] getReportsUserPointsForbidden %s", 403, payload)
}

func (o *GetReportsUserPointsForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /reports/user-points][%d] getReportsUserPointsForbidden %s", 403, payload)
}

func (o *GetReportsUserPointsForbidden) GetPayload() *models.RespondError {
	return o.Payload
}

func (o *GetReportsUserPointsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RespondError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetReportsUserPointsInternalServerError creates a GetReportsUserPointsInternalServerError with default headers values
func NewGetReportsUserPointsInternalServerError() *GetReportsUserPointsInternalServerError {
	return &GetReportsUserPointsInternalServerError{}
}

/*
GetReportsUserPointsInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetReportsUserPointsInternalServerError struct {
	Payload *models.RespondError
}

// IsSuccess returns true when this get reports user points internal server error response has a 2xx status code
func (o *GetReportsUserPointsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get reports user points internal server error response has a 3xx status code
func (o *GetReportsUserPointsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get reports user points internal server error response has a 4xx status code
func (o *GetReportsUserPointsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get reports user points internal server error response has a 5xx status code
func (o *GetReportsUserPointsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get reports user points internal server error response a status code equal to that given
func (o *GetReportsUserPointsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get reports user points internal server error response
func (o *GetReportsUserPointsInternalServerError) Code() int {
	return 500
}

func (o *GetReportsUserPointsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /reports/user-points][%d] getReportsUserPointsInternalServerError %s", 500, payload)
}

func (o *GetReportsUserPointsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /reports/user-points][%d] getReportsUserPointsInternalServerError %s", 500, payload)
}

func (o *GetReportsUserPointsInternalServerError) GetPayload() *models.RespondError {
	return o.Payload
}

func (o *GetReportsUserPointsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RespondError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
