// Code generated by ent, DO NOT EDIT.

package file

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	uuid "github.com/gofrs/uuid/v5"
	"github.com/kozlov-ma/sesc-backend/db/entdb/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.File {
	return predicate.File(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.File {
	return predicate.File(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.File {
	return predicate.File(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.File {
	return predicate.File(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.File {
	return predicate.File(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.File {
	return predicate.File(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.File {
	return predicate.File(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.File {
	return predicate.File(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.File {
	return predicate.File(sql.FieldLTE(FieldID, id))
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v uuid.UUID) predicate.File {
	return predicate.File(sql.FieldEQ(FieldOwnerID, v))
}

// S3ObjectKey applies equality check predicate on the "s3_object_key" field. It's identical to S3ObjectKeyEQ.
func S3ObjectKey(v string) predicate.File {
	return predicate.File(sql.FieldEQ(FieldS3ObjectKey, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.File {
	return predicate.File(sql.FieldEQ(FieldName, v))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v int) predicate.File {
	return predicate.File(sql.FieldEQ(FieldSize, v))
}

// FileDeleted applies equality check predicate on the "file_deleted" field. It's identical to FileDeletedEQ.
func FileDeleted(v bool) predicate.File {
	return predicate.File(sql.FieldEQ(FieldFileDeleted, v))
}

// DeletionScheduled applies equality check predicate on the "deletion_scheduled" field. It's identical to DeletionScheduledEQ.
func DeletionScheduled(v bool) predicate.File {
	return predicate.File(sql.FieldEQ(FieldDeletionScheduled, v))
}

// ScheduledDeletionAt applies equality check predicate on the "scheduled_deletion_at" field. It's identical to ScheduledDeletionAtEQ.
func ScheduledDeletionAt(v time.Time) predicate.File {
	return predicate.File(sql.FieldEQ(FieldScheduledDeletionAt, v))
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v uuid.UUID) predicate.File {
	return predicate.File(sql.FieldEQ(FieldOwnerID, v))
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v uuid.UUID) predicate.File {
	return predicate.File(sql.FieldNEQ(FieldOwnerID, v))
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...uuid.UUID) predicate.File {
	return predicate.File(sql.FieldIn(FieldOwnerID, vs...))
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...uuid.UUID) predicate.File {
	return predicate.File(sql.FieldNotIn(FieldOwnerID, vs...))
}

// OwnerIDIsNil applies the IsNil predicate on the "owner_id" field.
func OwnerIDIsNil() predicate.File {
	return predicate.File(sql.FieldIsNull(FieldOwnerID))
}

// OwnerIDNotNil applies the NotNil predicate on the "owner_id" field.
func OwnerIDNotNil() predicate.File {
	return predicate.File(sql.FieldNotNull(FieldOwnerID))
}

// S3ObjectKeyEQ applies the EQ predicate on the "s3_object_key" field.
func S3ObjectKeyEQ(v string) predicate.File {
	return predicate.File(sql.FieldEQ(FieldS3ObjectKey, v))
}

// S3ObjectKeyNEQ applies the NEQ predicate on the "s3_object_key" field.
func S3ObjectKeyNEQ(v string) predicate.File {
	return predicate.File(sql.FieldNEQ(FieldS3ObjectKey, v))
}

// S3ObjectKeyIn applies the In predicate on the "s3_object_key" field.
func S3ObjectKeyIn(vs ...string) predicate.File {
	return predicate.File(sql.FieldIn(FieldS3ObjectKey, vs...))
}

// S3ObjectKeyNotIn applies the NotIn predicate on the "s3_object_key" field.
func S3ObjectKeyNotIn(vs ...string) predicate.File {
	return predicate.File(sql.FieldNotIn(FieldS3ObjectKey, vs...))
}

// S3ObjectKeyGT applies the GT predicate on the "s3_object_key" field.
func S3ObjectKeyGT(v string) predicate.File {
	return predicate.File(sql.FieldGT(FieldS3ObjectKey, v))
}

// S3ObjectKeyGTE applies the GTE predicate on the "s3_object_key" field.
func S3ObjectKeyGTE(v string) predicate.File {
	return predicate.File(sql.FieldGTE(FieldS3ObjectKey, v))
}

// S3ObjectKeyLT applies the LT predicate on the "s3_object_key" field.
func S3ObjectKeyLT(v string) predicate.File {
	return predicate.File(sql.FieldLT(FieldS3ObjectKey, v))
}

// S3ObjectKeyLTE applies the LTE predicate on the "s3_object_key" field.
func S3ObjectKeyLTE(v string) predicate.File {
	return predicate.File(sql.FieldLTE(FieldS3ObjectKey, v))
}

// S3ObjectKeyContains applies the Contains predicate on the "s3_object_key" field.
func S3ObjectKeyContains(v string) predicate.File {
	return predicate.File(sql.FieldContains(FieldS3ObjectKey, v))
}

// S3ObjectKeyHasPrefix applies the HasPrefix predicate on the "s3_object_key" field.
func S3ObjectKeyHasPrefix(v string) predicate.File {
	return predicate.File(sql.FieldHasPrefix(FieldS3ObjectKey, v))
}

// S3ObjectKeyHasSuffix applies the HasSuffix predicate on the "s3_object_key" field.
func S3ObjectKeyHasSuffix(v string) predicate.File {
	return predicate.File(sql.FieldHasSuffix(FieldS3ObjectKey, v))
}

// S3ObjectKeyIsNil applies the IsNil predicate on the "s3_object_key" field.
func S3ObjectKeyIsNil() predicate.File {
	return predicate.File(sql.FieldIsNull(FieldS3ObjectKey))
}

// S3ObjectKeyNotNil applies the NotNil predicate on the "s3_object_key" field.
func S3ObjectKeyNotNil() predicate.File {
	return predicate.File(sql.FieldNotNull(FieldS3ObjectKey))
}

// S3ObjectKeyEqualFold applies the EqualFold predicate on the "s3_object_key" field.
func S3ObjectKeyEqualFold(v string) predicate.File {
	return predicate.File(sql.FieldEqualFold(FieldS3ObjectKey, v))
}

// S3ObjectKeyContainsFold applies the ContainsFold predicate on the "s3_object_key" field.
func S3ObjectKeyContainsFold(v string) predicate.File {
	return predicate.File(sql.FieldContainsFold(FieldS3ObjectKey, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.File {
	return predicate.File(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.File {
	return predicate.File(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.File {
	return predicate.File(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.File {
	return predicate.File(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.File {
	return predicate.File(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.File {
	return predicate.File(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.File {
	return predicate.File(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.File {
	return predicate.File(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.File {
	return predicate.File(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.File {
	return predicate.File(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.File {
	return predicate.File(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.File {
	return predicate.File(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.File {
	return predicate.File(sql.FieldContainsFold(FieldName, v))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v int) predicate.File {
	return predicate.File(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v int) predicate.File {
	return predicate.File(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...int) predicate.File {
	return predicate.File(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...int) predicate.File {
	return predicate.File(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v int) predicate.File {
	return predicate.File(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v int) predicate.File {
	return predicate.File(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v int) predicate.File {
	return predicate.File(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v int) predicate.File {
	return predicate.File(sql.FieldLTE(FieldSize, v))
}

// FileDeletedEQ applies the EQ predicate on the "file_deleted" field.
func FileDeletedEQ(v bool) predicate.File {
	return predicate.File(sql.FieldEQ(FieldFileDeleted, v))
}

// FileDeletedNEQ applies the NEQ predicate on the "file_deleted" field.
func FileDeletedNEQ(v bool) predicate.File {
	return predicate.File(sql.FieldNEQ(FieldFileDeleted, v))
}

// DeletionScheduledEQ applies the EQ predicate on the "deletion_scheduled" field.
func DeletionScheduledEQ(v bool) predicate.File {
	return predicate.File(sql.FieldEQ(FieldDeletionScheduled, v))
}

// DeletionScheduledNEQ applies the NEQ predicate on the "deletion_scheduled" field.
func DeletionScheduledNEQ(v bool) predicate.File {
	return predicate.File(sql.FieldNEQ(FieldDeletionScheduled, v))
}

// ScheduledDeletionAtEQ applies the EQ predicate on the "scheduled_deletion_at" field.
func ScheduledDeletionAtEQ(v time.Time) predicate.File {
	return predicate.File(sql.FieldEQ(FieldScheduledDeletionAt, v))
}

// ScheduledDeletionAtNEQ applies the NEQ predicate on the "scheduled_deletion_at" field.
func ScheduledDeletionAtNEQ(v time.Time) predicate.File {
	return predicate.File(sql.FieldNEQ(FieldScheduledDeletionAt, v))
}

// ScheduledDeletionAtIn applies the In predicate on the "scheduled_deletion_at" field.
func ScheduledDeletionAtIn(vs ...time.Time) predicate.File {
	return predicate.File(sql.FieldIn(FieldScheduledDeletionAt, vs...))
}

// ScheduledDeletionAtNotIn applies the NotIn predicate on the "scheduled_deletion_at" field.
func ScheduledDeletionAtNotIn(vs ...time.Time) predicate.File {
	return predicate.File(sql.FieldNotIn(FieldScheduledDeletionAt, vs...))
}

// ScheduledDeletionAtGT applies the GT predicate on the "scheduled_deletion_at" field.
func ScheduledDeletionAtGT(v time.Time) predicate.File {
	return predicate.File(sql.FieldGT(FieldScheduledDeletionAt, v))
}

// ScheduledDeletionAtGTE applies the GTE predicate on the "scheduled_deletion_at" field.
func ScheduledDeletionAtGTE(v time.Time) predicate.File {
	return predicate.File(sql.FieldGTE(FieldScheduledDeletionAt, v))
}

// ScheduledDeletionAtLT applies the LT predicate on the "scheduled_deletion_at" field.
func ScheduledDeletionAtLT(v time.Time) predicate.File {
	return predicate.File(sql.FieldLT(FieldScheduledDeletionAt, v))
}

// ScheduledDeletionAtLTE applies the LTE predicate on the "scheduled_deletion_at" field.
func ScheduledDeletionAtLTE(v time.Time) predicate.File {
	return predicate.File(sql.FieldLTE(FieldScheduledDeletionAt, v))
}

// ScheduledDeletionAtIsNil applies the IsNil predicate on the "scheduled_deletion_at" field.
func ScheduledDeletionAtIsNil() predicate.File {
	return predicate.File(sql.FieldIsNull(FieldScheduledDeletionAt))
}

// ScheduledDeletionAtNotNil applies the NotNil predicate on the "scheduled_deletion_at" field.
func ScheduledDeletionAtNotNil() predicate.File {
	return predicate.File(sql.FieldNotNull(FieldScheduledDeletionAt))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.File {
	return predicate.File(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.File {
	return predicate.File(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAchievementDocuments applies the HasEdge predicate on the "achievement_documents" edge.
func HasAchievementDocuments() predicate.File {
	return predicate.File(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AchievementDocumentsTable, AchievementDocumentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAchievementDocumentsWith applies the HasEdge predicate on the "achievement_documents" edge with a given conditions (other predicates).
func HasAchievementDocumentsWith(preds ...predicate.AchievementDocument) predicate.File {
	return predicate.File(func(s *sql.Selector) {
		step := newAchievementDocumentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.File) predicate.File {
	return predicate.File(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.File) predicate.File {
	return predicate.File(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.File) predicate.File {
	return predicate.File(sql.NotPredicates(p))
}
