// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AccountingPeriod is the predicate function for accountingperiod builders.
type AccountingPeriod func(*sql.Selector)

// Achievement is the predicate function for achievement builders.
type Achievement func(*sql.Selector)

// AchievementDocument is the predicate function for achievementdocument builders.
type AchievementDocument func(*sql.Selector)

// AchievementGroup is the predicate function for achievementgroup builders.
type AchievementGroup func(*sql.Selector)

// AchievementReview is the predicate function for achievementreview builders.
type AchievementReview func(*sql.Selector)

// AchievementTemplate is the predicate function for achievementtemplate builders.
type AchievementTemplate func(*sql.Selector)

// AuthUser is the predicate function for authuser builders.
type AuthUser func(*sql.Selector)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// File is the predicate function for file builders.
type File func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
