// Code generated by go-swagger; DO NOT EDIT.

package departments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kozlov-ma/sesc-backend/apiclient/models"
)

// DeleteDepartmentsIDReader is a Reader for the DeleteDepartmentsID structure.
type DeleteDepartmentsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDepartmentsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteDepartmentsIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteDepartmentsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteDepartmentsIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteDepartmentsIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteDepartmentsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewDeleteDepartmentsIDConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteDepartmentsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /departments/{id}] DeleteDepartmentsID", response, response.Code())
	}
}

// NewDeleteDepartmentsIDNoContent creates a DeleteDepartmentsIDNoContent with default headers values
func NewDeleteDepartmentsIDNoContent() *DeleteDepartmentsIDNoContent {
	return &DeleteDepartmentsIDNoContent{}
}

/*
DeleteDepartmentsIDNoContent describes a response with status code 204, with default header values.

No content
*/
type DeleteDepartmentsIDNoContent struct {
}

// IsSuccess returns true when this delete departments Id no content response has a 2xx status code
func (o *DeleteDepartmentsIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete departments Id no content response has a 3xx status code
func (o *DeleteDepartmentsIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete departments Id no content response has a 4xx status code
func (o *DeleteDepartmentsIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete departments Id no content response has a 5xx status code
func (o *DeleteDepartmentsIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete departments Id no content response a status code equal to that given
func (o *DeleteDepartmentsIDNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete departments Id no content response
func (o *DeleteDepartmentsIDNoContent) Code() int {
	return 204
}

func (o *DeleteDepartmentsIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /departments/{id}][%d] deleteDepartmentsIdNoContent", 204)
}

func (o *DeleteDepartmentsIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /departments/{id}][%d] deleteDepartmentsIdNoContent", 204)
}

func (o *DeleteDepartmentsIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDepartmentsIDBadRequest creates a DeleteDepartmentsIDBadRequest with default headers values
func NewDeleteDepartmentsIDBadRequest() *DeleteDepartmentsIDBadRequest {
	return &DeleteDepartmentsIDBadRequest{}
}

/*
DeleteDepartmentsIDBadRequest describes a response with status code 400, with default header values.

Invalid UUID format
*/
type DeleteDepartmentsIDBadRequest struct {
	Payload *models.APIInvalidDepartmentIDError
}

// IsSuccess returns true when this delete departments Id bad request response has a 2xx status code
func (o *DeleteDepartmentsIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete departments Id bad request response has a 3xx status code
func (o *DeleteDepartmentsIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete departments Id bad request response has a 4xx status code
func (o *DeleteDepartmentsIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete departments Id bad request response has a 5xx status code
func (o *DeleteDepartmentsIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete departments Id bad request response a status code equal to that given
func (o *DeleteDepartmentsIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete departments Id bad request response
func (o *DeleteDepartmentsIDBadRequest) Code() int {
	return 400
}

func (o *DeleteDepartmentsIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /departments/{id}][%d] deleteDepartmentsIdBadRequest %s", 400, payload)
}

func (o *DeleteDepartmentsIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /departments/{id}][%d] deleteDepartmentsIdBadRequest %s", 400, payload)
}

func (o *DeleteDepartmentsIDBadRequest) GetPayload() *models.APIInvalidDepartmentIDError {
	return o.Payload
}

func (o *DeleteDepartmentsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIInvalidDepartmentIDError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDepartmentsIDUnauthorized creates a DeleteDepartmentsIDUnauthorized with default headers values
func NewDeleteDepartmentsIDUnauthorized() *DeleteDepartmentsIDUnauthorized {
	return &DeleteDepartmentsIDUnauthorized{}
}

/*
DeleteDepartmentsIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteDepartmentsIDUnauthorized struct {
	Payload *models.APIUnauthorizedError
}

// IsSuccess returns true when this delete departments Id unauthorized response has a 2xx status code
func (o *DeleteDepartmentsIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete departments Id unauthorized response has a 3xx status code
func (o *DeleteDepartmentsIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete departments Id unauthorized response has a 4xx status code
func (o *DeleteDepartmentsIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete departments Id unauthorized response has a 5xx status code
func (o *DeleteDepartmentsIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete departments Id unauthorized response a status code equal to that given
func (o *DeleteDepartmentsIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the delete departments Id unauthorized response
func (o *DeleteDepartmentsIDUnauthorized) Code() int {
	return 401
}

func (o *DeleteDepartmentsIDUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /departments/{id}][%d] deleteDepartmentsIdUnauthorized %s", 401, payload)
}

func (o *DeleteDepartmentsIDUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /departments/{id}][%d] deleteDepartmentsIdUnauthorized %s", 401, payload)
}

func (o *DeleteDepartmentsIDUnauthorized) GetPayload() *models.APIUnauthorizedError {
	return o.Payload
}

func (o *DeleteDepartmentsIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIUnauthorizedError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDepartmentsIDForbidden creates a DeleteDepartmentsIDForbidden with default headers values
func NewDeleteDepartmentsIDForbidden() *DeleteDepartmentsIDForbidden {
	return &DeleteDepartmentsIDForbidden{}
}

/*
DeleteDepartmentsIDForbidden describes a response with status code 403, with default header values.

Forbidden - admin role required
*/
type DeleteDepartmentsIDForbidden struct {
	Payload *models.APIForbiddenError
}

// IsSuccess returns true when this delete departments Id forbidden response has a 2xx status code
func (o *DeleteDepartmentsIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete departments Id forbidden response has a 3xx status code
func (o *DeleteDepartmentsIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete departments Id forbidden response has a 4xx status code
func (o *DeleteDepartmentsIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete departments Id forbidden response has a 5xx status code
func (o *DeleteDepartmentsIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this delete departments Id forbidden response a status code equal to that given
func (o *DeleteDepartmentsIDForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the delete departments Id forbidden response
func (o *DeleteDepartmentsIDForbidden) Code() int {
	return 403
}

func (o *DeleteDepartmentsIDForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /departments/{id}][%d] deleteDepartmentsIdForbidden %s", 403, payload)
}

func (o *DeleteDepartmentsIDForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /departments/{id}][%d] deleteDepartmentsIdForbidden %s", 403, payload)
}

func (o *DeleteDepartmentsIDForbidden) GetPayload() *models.APIForbiddenError {
	return o.Payload
}

func (o *DeleteDepartmentsIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIForbiddenError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDepartmentsIDNotFound creates a DeleteDepartmentsIDNotFound with default headers values
func NewDeleteDepartmentsIDNotFound() *DeleteDepartmentsIDNotFound {
	return &DeleteDepartmentsIDNotFound{}
}

/*
DeleteDepartmentsIDNotFound describes a response with status code 404, with default header values.

Department not found
*/
type DeleteDepartmentsIDNotFound struct {
	Payload *models.APIDepartmentNotFoundError
}

// IsSuccess returns true when this delete departments Id not found response has a 2xx status code
func (o *DeleteDepartmentsIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete departments Id not found response has a 3xx status code
func (o *DeleteDepartmentsIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete departments Id not found response has a 4xx status code
func (o *DeleteDepartmentsIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete departments Id not found response has a 5xx status code
func (o *DeleteDepartmentsIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete departments Id not found response a status code equal to that given
func (o *DeleteDepartmentsIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete departments Id not found response
func (o *DeleteDepartmentsIDNotFound) Code() int {
	return 404
}

func (o *DeleteDepartmentsIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /departments/{id}][%d] deleteDepartmentsIdNotFound %s", 404, payload)
}

func (o *DeleteDepartmentsIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /departments/{id}][%d] deleteDepartmentsIdNotFound %s", 404, payload)
}

func (o *DeleteDepartmentsIDNotFound) GetPayload() *models.APIDepartmentNotFoundError {
	return o.Payload
}

func (o *DeleteDepartmentsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIDepartmentNotFoundError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDepartmentsIDConflict creates a DeleteDepartmentsIDConflict with default headers values
func NewDeleteDepartmentsIDConflict() *DeleteDepartmentsIDConflict {
	return &DeleteDepartmentsIDConflict{}
}

/*
DeleteDepartmentsIDConflict describes a response with status code 409, with default header values.

Cannot remove department, it still has some users
*/
type DeleteDepartmentsIDConflict struct {
	Payload *models.APICannotRemoveDepartmentError
}

// IsSuccess returns true when this delete departments Id conflict response has a 2xx status code
func (o *DeleteDepartmentsIDConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete departments Id conflict response has a 3xx status code
func (o *DeleteDepartmentsIDConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete departments Id conflict response has a 4xx status code
func (o *DeleteDepartmentsIDConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete departments Id conflict response has a 5xx status code
func (o *DeleteDepartmentsIDConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this delete departments Id conflict response a status code equal to that given
func (o *DeleteDepartmentsIDConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the delete departments Id conflict response
func (o *DeleteDepartmentsIDConflict) Code() int {
	return 409
}

func (o *DeleteDepartmentsIDConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /departments/{id}][%d] deleteDepartmentsIdConflict %s", 409, payload)
}

func (o *DeleteDepartmentsIDConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /departments/{id}][%d] deleteDepartmentsIdConflict %s", 409, payload)
}

func (o *DeleteDepartmentsIDConflict) GetPayload() *models.APICannotRemoveDepartmentError {
	return o.Payload
}

func (o *DeleteDepartmentsIDConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APICannotRemoveDepartmentError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDepartmentsIDInternalServerError creates a DeleteDepartmentsIDInternalServerError with default headers values
func NewDeleteDepartmentsIDInternalServerError() *DeleteDepartmentsIDInternalServerError {
	return &DeleteDepartmentsIDInternalServerError{}
}

/*
DeleteDepartmentsIDInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type DeleteDepartmentsIDInternalServerError struct {
	Payload *models.APIServerError
}

// IsSuccess returns true when this delete departments Id internal server error response has a 2xx status code
func (o *DeleteDepartmentsIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete departments Id internal server error response has a 3xx status code
func (o *DeleteDepartmentsIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete departments Id internal server error response has a 4xx status code
func (o *DeleteDepartmentsIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete departments Id internal server error response has a 5xx status code
func (o *DeleteDepartmentsIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete departments Id internal server error response a status code equal to that given
func (o *DeleteDepartmentsIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete departments Id internal server error response
func (o *DeleteDepartmentsIDInternalServerError) Code() int {
	return 500
}

func (o *DeleteDepartmentsIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /departments/{id}][%d] deleteDepartmentsIdInternalServerError %s", 500, payload)
}

func (o *DeleteDepartmentsIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /departments/{id}][%d] deleteDepartmentsIdInternalServerError %s", 500, payload)
}

func (o *DeleteDepartmentsIDInternalServerError) GetPayload() *models.APIServerError {
	return o.Payload
}

func (o *DeleteDepartmentsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
