// Code generated by go-swagger; DO NOT EDIT.

package departments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kozlov-ma/sesc-backend/apiclient/models"
)

// GetDepartmentsReader is a Reader for the GetDepartments structure.
type GetDepartmentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDepartmentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDepartmentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetDepartmentsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /departments] GetDepartments", response, response.Code())
	}
}

// NewGetDepartmentsOK creates a GetDepartmentsOK with default headers values
func NewGetDepartmentsOK() *GetDepartmentsOK {
	return &GetDepartmentsOK{}
}

/*
GetDepartmentsOK describes a response with status code 200, with default header values.

OK
*/
type GetDepartmentsOK struct {
	Payload *models.APIDepartmentsResponse
}

// IsSuccess returns true when this get departments o k response has a 2xx status code
func (o *GetDepartmentsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get departments o k response has a 3xx status code
func (o *GetDepartmentsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get departments o k response has a 4xx status code
func (o *GetDepartmentsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get departments o k response has a 5xx status code
func (o *GetDepartmentsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get departments o k response a status code equal to that given
func (o *GetDepartmentsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get departments o k response
func (o *GetDepartmentsOK) Code() int {
	return 200
}

func (o *GetDepartmentsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /departments][%d] getDepartmentsOK %s", 200, payload)
}

func (o *GetDepartmentsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /departments][%d] getDepartmentsOK %s", 200, payload)
}

func (o *GetDepartmentsOK) GetPayload() *models.APIDepartmentsResponse {
	return o.Payload
}

func (o *GetDepartmentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIDepartmentsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDepartmentsInternalServerError creates a GetDepartmentsInternalServerError with default headers values
func NewGetDepartmentsInternalServerError() *GetDepartmentsInternalServerError {
	return &GetDepartmentsInternalServerError{}
}

/*
GetDepartmentsInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetDepartmentsInternalServerError struct {
	Payload *models.APIServerError
}

// IsSuccess returns true when this get departments internal server error response has a 2xx status code
func (o *GetDepartmentsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get departments internal server error response has a 3xx status code
func (o *GetDepartmentsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get departments internal server error response has a 4xx status code
func (o *GetDepartmentsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get departments internal server error response has a 5xx status code
func (o *GetDepartmentsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get departments internal server error response a status code equal to that given
func (o *GetDepartmentsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get departments internal server error response
func (o *GetDepartmentsInternalServerError) Code() int {
	return 500
}

func (o *GetDepartmentsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /departments][%d] getDepartmentsInternalServerError %s", 500, payload)
}

func (o *GetDepartmentsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /departments][%d] getDepartmentsInternalServerError %s", 500, payload)
}

func (o *GetDepartmentsInternalServerError) GetPayload() *models.APIServerError {
	return o.Payload
}

func (o *GetDepartmentsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
