// Code generated by go-swagger; DO NOT EDIT.

package departments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kozlov-ma/sesc-backend/apiclient/models"
)

// NewPostDepartmentsParams creates a new PostDepartmentsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostDepartmentsParams() *PostDepartmentsParams {
	return &PostDepartmentsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostDepartmentsParamsWithTimeout creates a new PostDepartmentsParams object
// with the ability to set a timeout on a request.
func NewPostDepartmentsParamsWithTimeout(timeout time.Duration) *PostDepartmentsParams {
	return &PostDepartmentsParams{
		timeout: timeout,
	}
}

// NewPostDepartmentsParamsWithContext creates a new PostDepartmentsParams object
// with the ability to set a context for a request.
func NewPostDepartmentsParamsWithContext(ctx context.Context) *PostDepartmentsParams {
	return &PostDepartmentsParams{
		Context: ctx,
	}
}

// NewPostDepartmentsParamsWithHTTPClient creates a new PostDepartmentsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostDepartmentsParamsWithHTTPClient(client *http.Client) *PostDepartmentsParams {
	return &PostDepartmentsParams{
		HTTPClient: client,
	}
}

/*
PostDepartmentsParams contains all the parameters to send to the API endpoint

	for the post departments operation.

	Typically these are written to a http.Request.
*/
type PostDepartmentsParams struct {

	/* Authorization.

	   Bearer JWT token
	*/
	Authorization *string

	/* Request.

	   Department details
	*/
	Request *models.APICreateDepartmentRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post departments params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostDepartmentsParams) WithDefaults() *PostDepartmentsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post departments params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostDepartmentsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post departments params
func (o *PostDepartmentsParams) WithTimeout(timeout time.Duration) *PostDepartmentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post departments params
func (o *PostDepartmentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post departments params
func (o *PostDepartmentsParams) WithContext(ctx context.Context) *PostDepartmentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post departments params
func (o *PostDepartmentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post departments params
func (o *PostDepartmentsParams) WithHTTPClient(client *http.Client) *PostDepartmentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post departments params
func (o *PostDepartmentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the post departments params
func (o *PostDepartmentsParams) WithAuthorization(authorization *string) *PostDepartmentsParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the post departments params
func (o *PostDepartmentsParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WithRequest adds the request to the post departments params
func (o *PostDepartmentsParams) WithRequest(request *models.APICreateDepartmentRequest) *PostDepartmentsParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post departments params
func (o *PostDepartmentsParams) SetRequest(request *models.APICreateDepartmentRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostDepartmentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
